In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

warnings.filterwarnings("ignore")

%matplotlib inline

In [30]:
df = pd.read_csv('cardekho_dataset.csv', index_col=[0])

In [31]:
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

# Data Cleaning

## Handling Missing Values

In [32]:
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [33]:
df.drop('car_name', axis=1, inplace=True)
df.drop('brand', axis=1, inplace=True)

In [34]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [35]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [36]:
num_features = [feature for feature in df.columns if df[feature].dtype != 'O'] ## Numerical features
print('Num of Numerical Features : ', len(num_features))
cat_features = [feature for feature in df.columns if df[feature].dtype == 'O'] ## Categorical features
print('Num of Categorical Features : ', len(cat_features))

## Now in numerical features how many of them are discrete and continuous features 
discrete_features = [feature for feature in num_features if len(df[feature].unique()) <= 25]
print('Num of Discrete Features : ', len(discrete_features))
continuous_features = [feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features : ', len(continuous_features))

Num of Numerical Features :  7
Num of Categorical Features :  4
Num of Discrete Features :  2
Num of Continuous Features :  5

In [37]:
from sklearn.model_selection import train_test_split
X = df.drop(['selling_price'], axis=1)
y = df['selling_price']

In [38]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
19537,i10,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
19540,Ertiga,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
19541,Rapid,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
19542,XUV500,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
19543,City,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [39]:
y

0         120000
1         550000
2         215000
3         226000
4         570000
          ...
19537     250000
19540     925000
19541     425000
19542    1225000
19543    1200000
Name: selling_price, Length: 15411, dtype: int64

# Feature Encoding and Scaling

### One hot encoding for columns which had lesser unique values and not ordinal
#### - One hot coding is a process by which categorical variables are converted into a form that could be provided to ML algorithms to do a better job in predicition

In [40]:
len(df['model'].unique())

120

In [41]:
df['model'].value_counts()

model
i20            906
Swift Dzire    890
Swift          781
Alto           778
City           757
              ...
Ghibli           1
Altroz           1
GTC4Lusso        1
Aura             1
Gurkha           1
Name: count, Length: 120, dtype: int64

In [42]:
X.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [43]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
X['model'] = le.fit_transform(X['model'])

In [44]:
X

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5
...,...,...,...,...,...,...,...,...,...,...
19537,117,9,10723,Dealer,Petrol,Manual,19.81,1086,68.05,5
19540,42,2,18000,Dealer,Petrol,Manual,17.50,1373,91.10,7
19541,77,6,67000,Dealer,Diesel,Manual,21.14,1498,103.52,5
19542,114,5,3800000,Dealer,Diesel,Manual,16.00,2179,140.00,7
19543,25,2,13000,Dealer,Petrol,Automatic,18.00,1497,117.60,5

In [45]:
len(df['seller_type'].unique()), len(df['fuel_type'].unique()), len(df['transmission_type'].unique())

X['model'] = le.fit_transform(X['model'])

In [46]:
num_features = X.select_dtypes(exclude="object").columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop = 'first')

preprocessor = ColumnTransformer(
  [
    ("OneHotEncoder", oh_transformer, onehot_columns),
    ('StandardScaler', numeric_transformer, num_features)
  ], remainder='passthrough' ## this means other features will reamin as they are
)

In [47]:
X = preprocessor.fit_transform(X)

In [48]:
pd.DataFrame(X)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15406,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.508844,0.983562,-0.869744,0.026096,-0.767733,-0.757204,-0.403022
15407,0.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.556082,-1.339555,-0.728763,-0.527711,-0.216964,-0.220803,2.073444
15408,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.407551,-0.012060,0.220539,0.344954,0.022918,0.068225,-0.403022
15409,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.426247,-0.343933,72.541850,-0.887326,1.329794,0.917158,2.073444
15410,0.0,0.0,0.0,0.0,0.0,1.0,0.0,-1.024131,-1.339555,-0.825631,-0.407839,0.020999,0.395884,-0.403022

In [49]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
X_train.shape, X_test.shape

((12328, 14), (3083, 14))

In [50]:
X_train

array([[ 0.        ,  0.        ,  1.        , ...,  1.75390551,
         2.66249771, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.55087963,
        -0.38602844, -0.40302241],
       [ 0.        ,  0.        ,  1.        , ...,  0.89033072,
         3.27453006, -0.40302241],
       ...,
       [ 1.        ,  0.        ,  0.        , ..., -0.9366097 ,
        -0.78070786, -0.40302241],
       [ 0.        ,  0.        ,  0.        , ..., -0.55471774,
        -0.43582879, -0.40302241],
       [ 1.        ,  0.        ,  0.        , ..., -0.04616815,
         0.06194201, -0.40302241]])

# Model Training and Model Selection

In [51]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error

In [52]:
def evaluate_model(true, predicted):
  mae = mean_absolute_error(true, predicted)
  mse = mean_squared_error(true, predicted)
  rmse = np.sqrt(mean_squared_error(true, predicted))
  r2 = r2_score(true, predicted)

  return mae, rmse, r2

In [53]:
models = {
    'Linear Regression': LinearRegression(),
    'Lasso': Lasso(),
    'Ridge': Ridge(),
    'KNeighborsRegressor': KNeighborsRegressor(),
    'DecisionTreeRegressor': DecisionTreeRegressor(),
    'RandomForestRegressor': RandomForestRegressor()
}

for model_name, model in models.items():
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(f"\n================ {model_name} =================")
    print(f"Training Set: RMSE = {model_train_rmse:.4f}, MAE = {model_train_mae:.4f}, R2 Score = {model_train_r2:.4f}")
    print(f"Test Set: RMSE = {model_test_rmse:.4f}, MAE = {model_test_mae:.4f}, R2 Score = {model_test_r2:.4f}")
    print("--------------------------------------------------------")

================ Linear Regression =================
Training Set: RMSE = 553855.6665, MAE = 268101.6071, R2 Score = 0.6218
Test Set: RMSE = 502543.5930, MAE = 279618.5794, R2 Score = 0.6645
--------------------------------------------------------

================ Lasso =================
Training Set: RMSE = 553855.6710, MAE = 268099.2226, R2 Score = 0.6218
Test Set: RMSE = 502542.6696, MAE = 279614.7461, R2 Score = 0.6645
--------------------------------------------------------

================ Ridge =================
Training Set: RMSE = 553856.3160, MAE = 268059.8015, R2 Score = 0.6218
Test Set: RMSE = 502533.8230, MAE = 279557.2169, R2 Score = 0.6645
--------------------------------------------------------

================ KNeighborsRegressor =================
Training Set: RMSE = 325873.0088, MAE = 91425.4705, R2 Score = 0.8691
Test Set: RMSE = 253024.3951, MAE = 112526.3461, R2 Score = 0.9150
--------------------------------------------------------

================ DecisionTreeRegressor =================
Training Set: RMSE = 20797.2352, MAE = 5164.8199, R2 Score = 0.9995
Test Set: RMSE = 313484.3729, MAE = 126930.1465, R2 Score = 0.8695
--------------------------------------------------------

================ RandomForestRegressor =================
Training Set: RMSE = 126260.2090, MAE = 39746.4449, R2 Score = 0.9803
Test Set: RMSE = 228006.4363, MAE = 101995.2080, R2 Score = 0.9309
--------------------------------------------------------

In [54]:
## Hyperparameter Tuning
knn_params = {"n_neighbors" : [2, 3, 10, 20, 40, 50]}
rf_params = {
  "max_depth" : [5, 8, 15 ,None ,10],
  "max_depth" : [5 ,7 ,"auto", 8],
  "min_samples_split" : [2, 8, 15, 20],
  "n_estimators" : [100, 200, 500, 1000]
}

In [55]:
randomcv_models = [
  ('KNN', KNeighborsRegressor(), knn_params),
  ('RF', RandomForestRegressor(), rf_params)
]

In [57]:
from sklearn.model_selection import RandomizedSearchCV

model_param = {}
for name, model, params in randomcv_models:
  random = RandomizedSearchCV(
    estimator=model,
    param_distributions=params,
    n_iter=50,
    cv=3,
    n_jobs=-1,
    verbose=2  # Shows progress
)

  random.fit(X_train, y_train)
  model_param[name] = random.best_params_

for model_name in model_param:
  print(f"======== Best Params for {model_name} ================")
  print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
Fitting 3 folds for each of 50 candidates, totalling 150 fits

KeyboardInterrupt:

In [ ]:
# Output

## ===================== Best Params for KNN =====================================
## {'n_neighbors' : 10}
## ===================== Best Params for RF ======================================
## {'n_estimators' : 100, 'min_samples_split' : 2, 'max_features' : 'sqrt', 'max_depth' : None}

In [66]:
## Retrain the models with best parameters
models = {
  "Random Forest Regressor" : RandomForestRegressor(
    n_estimators=100, min_samples_split=2, max_features='sqrt', max_depth=None, n_jobs=-1
  ),
  "K-Neighbors Regressor" : KNeighborsRegressor(
    n_neighbors=10, n_jobs=-1
  )
}

In [ ]:
for model_name, model in models.items():  # Iterate correctly over dict items
    model.fit(X_train, y_train)

    y_train_pred = model.predict(X_train)
    y_test_pred = model.predict(X_test)

    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print(f"\n================ {model_name} =================")  # Now prints correct model name
    print(f"Training Set: RMSE = {model_train_rmse:.4f}, MAE = {model_train_mae:.4f}, R2 Score = {model_train_r2:.4f}")
    print(f"Test Set: RMSE = {model_test_rmse:.4f}, MAE = {model_test_mae:.4f}, R2 Score = {model_test_r2:.4f}")
    print("--------------------------------------------------------")

================ Random Forest Regressor =================
Training Set: RMSE = 119984.9206, MAE = 39849.1936, R2 Score = 0.9822
Test Set: RMSE = 203392.6791, MAE = 97678.0506, R2 Score = 0.9450
--------------------------------------------------------

================ K-Neighbors Regressor =================
Training Set: RMSE = 363460.7706, MAE = 103472.0474, R2 Score = 0.8371
Test Set: RMSE = 263888.0623, MAE = 117496.2131, R2 Score = 0.9075
--------------------------------------------------------