
About Dataset
Context
This is a small subset of dataset of Book reviews from Amazon Kindle Store category.

Content
5-core dataset of product reviews from Amazon Kindle Store category from May 1996 - July 2014. Contains total of 982619 entries. Each reviewer has at least 5 reviews and each product has at least 5 reviews in this dataset.
Columns

asin - ID of the product, like B000FA64PK
-helpful - helpfulness rating of the review - example: 2/3.
-overall - rating of the product.
-reviewText - text of the review (heading).
-reviewTime - time of the review (raw).
-reviewerID - ID of the reviewer, like A3SPTOKDG7WBLN
-reviewerName - name of the reviewer.
-summary - summary of the review (description).
-unixReviewTime - unix timestamp.
Which file to use?
There are two files one is preprocessed ready for sentiment analysis and other is unprocessed to you basically have to process the dataset and then perform sentiment analysis

Acknowledgements
This dataset is taken from Amazon product data, Julian McAuley, UCSD website. http://jmcauley.ucsd.edu/data/amazon/

License to the data files belong to them.

Inspiration
-Sentiment analysis on reviews.
-Understanding how people rate usefulness of a review/ What factors influence helpfulness of a review.
-Fake reviews/ outliers.
-Best rated product IDs, or similarity between products based on reviews alone (not the best idea ikr).
-Any other interesting analysis

In [1]:
## Best Practices
## 1. Pre-Processing and Cleaning (removing stopwords, stemming/lemmatization, lower-casing, etc.)
## 2. Train-Test Split
## 3. Vector Embeddings using : BOW, TF-IDF, Word2Vec
## 4. Train using ML algorithms

In [2]:
import pandas as pd

data = pd.read_csv('all_kindle_review .csv')
data.head()

,Unnamed: 0.1,Unnamed: 0,asin,helpful,rating,reviewText,reviewTime,reviewerID,reviewerName,summary,unixReviewTime
0,0,11539,B0033UV8HI,"[8, 10]",3,"Jace Rankin may be short, but he's nothing to ...","09 2, 2010",A3HHXRELK8BHQG,Ridley,Entertaining But Average,1283385600
1,1,5957,B002HJV4DE,"[1, 1]",5,Great short read. I didn't want to put it dow...,"10 8, 2013",A2RGNZ0TRF578I,Holly Butler,Terrific menage scenes!,1381190400
2,2,9146,B002ZG96I4,"[0, 0]",3,I'll start by saying this is the first of four...,"04 11, 2014",A3S0H2HV6U1I7F,Merissa,Snapdragon Alley,1397174400
3,3,7038,B002QHWOEU,"[1, 3]",3,Aggie is Angela Lansbury who carries pocketboo...,"07 5, 2014",AC4OQW3GZ919J,Cleargrace,very light murder cozy,1404518400
4,4,1776,B001A06VJ8,"[0, 1]",4,I did not expect this type of book to be in li...,"12 31, 2012",A3C9V987IQHOQD,Rjostler,Book,1356912000

In [3]:
data = data[['reviewText', 'rating']]
data.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       3
1  Great short read.  I didn't want to put it dow...       5
2  I'll start by saying this is the first of four...       3
3  Aggie is Angela Lansbury who carries pocketboo...       3
4  I did not expect this type of book to be in li...       4

In [4]:
data.shape

(12000, 2)

In [5]:
## Missing values
data.isnull().sum()

reviewText    0
rating        0
dtype: int64

In [6]:
data['rating'].unique()

array([3, 5, 4, 2, 1], dtype=int64)

In [7]:
data['rating'].value_counts()

rating
5    3000
4    3000
3    2000
2    2000
1    2000
Name: count, dtype: int64

In [8]:
## Positive review => 1, Negative Review => 0
data['rating'] = data['rating'].apply(
  lambda x : 0 if x < 3 else 1
)
data.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [9]:
df = pd.DataFrame(data)

In [10]:
df.head()

                                          reviewText  rating
0  Jace Rankin may be short, but he's nothing to ...       1
1  Great short read.  I didn't want to put it dow...       1
2  I'll start by saying this is the first of four...       1
3  Aggie is Angela Lansbury who carries pocketboo...       1
4  I did not expect this type of book to be in li...       1

In [11]:
df['rating'].value_counts()

rating
1    8000
0    4000
Name: count, dtype: int64

In [12]:
## 1. Pre-Processing and Cleaning (removing stopwords, stemming/lemmatization, lower-casing, removing non alpha chars, etc.)
df['reviewText'] = df['reviewText'].str.lower()
df

                                              reviewText  rating
0      jace rankin may be short, but he's nothing to ...       1
1      great short read.  i didn't want to put it dow...       1
2      i'll start by saying this is the first of four...       1
3      aggie is angela lansbury who carries pocketboo...       1
4      i did not expect this type of book to be in li...       1
...                                                  ...     ...
11995  valentine cupid is a vampire- jena and ian ano...       1
11996  i have read all seven books in this series. ap...       1
11997  this book really just wasn't my cuppa.  the si...       1
11998  tried to use it to charge my kindle, it didn't...       0
11999  taking instruction is a look into the often hi...       1

[12000 rows x 2 columns]

In [ ]:
import re
import nltk
nltk.download('stopwords')
from nltk.corpus import stopwords
from bs4 import BeautifulSoup

df['reviewText'] = df['reviewText'].apply(
  lambda x : re.sub('[^a-z A-Z 0-9]+', '', x) ## remove special characters
)
df['reviewText'] = df['reviewText'].apply(
  lambda x : " ".join([y for y in x.split() if y not in stopwords.words('english')]) ## remove stopwords
)
df['reviewText'] = df['reviewText'].apply(  ## handle urls
  lambda x : re.sub(r'(http|https|ftp|ssh)://([\w_-]+(?:(?:\.[\w_-]+)+))([\w.,@?^=%&:/~+#-]*[\w@?^=%&/~+#-])?', '', str(x))
)
df['reviewText'] = df['reviewText'].apply(  ## remove html tags
    lambda x: BeautifulSoup(str(x), 'html.parser').get_text()
)
df['reviewText'] = df['reviewText'].apply( ## remove additional spaces
    lambda x: " ".join(x.split())
)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [14]:
df['reviewText']

0        jace rankin may short hes nothing mess man hau...
1        great short read didnt want put read one sitti...
2        ill start saying first four books wasnt expect...
3        aggie angela lansbury carries pocketbooks inst...
4        expect type book library pleased find price right
                               ...
11995    valentine cupid vampire jena ian another vampi...
11996    read seven books series apocalypticadventure o...
11997    book really wasnt cuppa situation man capturin...
11998    tried use charge kindle didnt even register ch...
11999    taking instruction look often hidden world sex...
Name: reviewText, Length: 12000, dtype: object

In [16]:
df

                                              reviewText  rating
0      jace rankin may short hes nothing mess man hau...       1
1      great short read didnt want put read one sitti...       1
2      ill start saying first four books wasnt expect...       1
3      aggie angela lansbury carries pocketbooks inst...       1
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire jena ian another vampi...       1
11996  read seven books series apocalypticadventure o...       1
11997  book really wasnt cuppa situation man capturin...       1
11998  tried use charge kindle didnt even register ch...       0
11999  taking instruction look often hidden world sex...       1

[12000 rows x 2 columns]

In [17]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

def lemmatize_words(text):
  return " ".join([lemmatizer.lemmatize(word) for word in text.split()])

In [18]:
df['reviewText'] = df['reviewText'].apply(
  lambda x : lemmatize_words(x)
)

In [19]:
df

                                              reviewText  rating
0      jace rankin may short he nothing mess man haul...       1
1      great short read didnt want put read one sitti...       1
2      ill start saying first four book wasnt expecti...       1
3      aggie angela lansbury carry pocketbook instead...       1
4      expect type book library pleased find price right       1
...                                                  ...     ...
11995  valentine cupid vampire jena ian another vampi...       1
11996  read seven book series apocalypticadventure on...       1
11997  book really wasnt cuppa situation man capturin...       1
11998  tried use charge kindle didnt even register ch...       0
11999  taking instruction look often hidden world sex...       1

[12000 rows x 2 columns]

In [57]:
## 2. Train-Test Split
from sklearn.model_selection import train_test_split

X = df['reviewText']
y = df['rating']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [58]:
X_train

565      ok one better read choice would want take chan...
9138     touching story favorite bdb couple zsadist bel...
7664     didnt find good read reviewer pointed good pre...
11881    standalong book really enjoyed twelve lie chri...
2799     never knew harlequin teen series maybe new cas...
                               ...
1410     loved thispossible spoilershere meet mav duke ...
7829     punny cute cozy mystery left unsolved anyway e...
5896     enjoyed way major work filling remaining gap r...
4318     first time read book scrayton bit thriller cha...
4393     really needed editor good concept belowaverage...
Name: reviewText, Length: 9600, dtype: object

In [59]:
X_test

3616     short sweet victorian widow meet wyoming sheri...
1928     nice buildup chase relationship heroine likabl...
7694     wow chute action romance one hot outlaw named ...
4433     read 1115 westmoreland book cant pick favorite...
9860     still wasted precious time life review stated ...
                               ...
7676     courtesy ck2s kwips kritiquesabby brook expect...
1107     major issue work start stop three separate tim...
9252     first many possible book told make point veiw ...
10743    great history ottawa chippewa indian enlighten...
7520     looking forward reading started look dialogue ...
Name: reviewText, Length: 2400, dtype: object

In [68]:
## 3. Vector Embeddings using : BOW, TF-IDF, Word2Vec
## 4. Train using ML algorithms

## Create BOG
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
## Here we go with non-binary that means count of words (ex. [2, 1, 0] count is considered here) will be considered
cv = CountVectorizer()

In [70]:
X_train_bow = cv.fit_transform(X_train).toarray()
X_test_bow = cv.transform(X_test).toarray() ## to avoid data leakage

In [73]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer

tv = TfidfVectorizer()

In [71]:
X_train_tfidf = tv.fit_transform(X_train).toarray()
X_test_tfidf = tv.transform(X_test).toarray() ## to avoid data leakage

In [74]:
X_train_tfidf

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [76]:
from sklearn.naive_bayes import GaussianNB

nb_model_bow = GaussianNB().fit(X_train_bow, y_train)

In [77]:
nb_model_tfidf = GaussianNB().fit(X_train_tfidf, y_train)

In [78]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [79]:
y_pred_bow = nb_model_bow.predict(X_test_bow)

In [80]:
y_pred_tfidf = nb_model_tfidf.predict(X_test_tfidf)

In [83]:
print(f"BOW Accuracy : {accuracy_score(y_test, y_pred_bow)}")

BOW Accuracy : 0.5779166666666666

In [84]:
print(f"TF-IDF Accuracy : {accuracy_score(y_test, y_pred_tfidf)}")

TF-IDF Accuracy : 0.5758333333333333

In [85]:
confusion_matrix(y_test, y_pred_bow)

array([[510, 276],
       [737, 877]], dtype=int64)

In [86]:
confusion_matrix(y_test, y_pred_tfidf)

array([[491, 295],
       [723, 891]], dtype=int64)

## Word2Vec

In [88]:
import gensim
from gensim.models import Word2Vec, KeyedVectors

In [89]:
import gensim.downloader as api

wv = api.load('word2vec-google-news-300')

In [90]:
corpus = df['reviewText']

In [91]:
corpus

0        jace rankin may short he nothing mess man haul...
1        great short read didnt want put read one sitti...
2        ill start saying first four book wasnt expecti...
3        aggie angela lansbury carry pocketbook instead...
4        expect type book library pleased find price right
                               ...
11995    valentine cupid vampire jena ian another vampi...
11996    read seven book series apocalypticadventure on...
11997    book really wasnt cuppa situation man capturin...
11998    tried use charge kindle didnt even register ch...
11999    taking instruction look often hidden world sex...
Name: reviewText, Length: 12000, dtype: object

In [92]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess

words = []
for sent in corpus:
  sent_token = sent_tokenize(sent)
  for sent in sent_token:
    words.append(simple_preprocess(sent))

In [93]:
words

[['jace',
  'rankin',
  'may',
  'short',
  'he',
  'nothing',
  'mess',
  'man',
  'hauled',
  'saloon',
  'undertaker',
  'know',
  'he',
  'famous',
  'bounty',
  'hunter',
  'oregon',
  'shot',
  'man',
  'saloon',
  'finished',
  'year',
  'long',
  'quest',
  'avenge',
  'sister',
  'murder',
  'trying',
  'figure',
  'next',
  'snottynosed',
  'farm',
  'boy',
  'rescued',
  'gang',
  'bully',
  'offer',
  'money',
  'kill',
  'man',
  'forced',
  'ranch',
  'reluctantly',
  'agrees',
  'bring',
  'man',
  'justice',
  'kill',
  'outright',
  'first',
  'need',
  'tell',
  'sister',
  'widower',
  'newskyla',
  'kyle',
  'springer',
  'bailey',
  'riding',
  'trail',
  'sleeping',
  'ground',
  'past',
  'month',
  'trying',
  'find',
  'jace',
  'want',
  'revenge',
  'man',
  'killed',
  'husband',
  'took',
  'ranch',
  'amongst',
  'crime',
  'shes',
  'keen',
  'detour',
  'jace',
  'want',
  'take',
  'realizes',
  'shes',
  'option',
  'hide',
  'behind',
  'boy',
  'persona',
  'best',
  'try',
  'keep',
  'pace',
  'confrontation',
  'along',
  'way',
  'get',
  'shot',
  'jace',
  'discovers',
  'kyles',
  'kyla',
  'come',
  'clean',
  'whole',
  'reason',
  'need',
  'scoundrel',
  'dead',
  'hope',
  'hell',
  'still',
  'help',
  'herthe',
  'book',
  'share',
  'touching',
  'moment',
  'slowblooming',
  'romance',
  'kyla',
  'find',
  'good',
  'reason',
  'fear',
  'men',
  'hide',
  'behind',
  'boy',
  'persona',
  'watching',
  'jace',
  'slowly',
  'pull',
  'shell',
  'help',
  'conquer',
  'fear',
  'endearing',
  'pain',
  'real',
  'deeplyrooted',
  'didnt',
  'disappear',
  'face',
  'sexiness',
  'neither',
  'understandable',
  'aversion',
  'marriage',
  'magically',
  'disappear',
  'round',
  'nookie',
  'would',
  'man',
  'who',
  'drifted',
  'town',
  'town',
  'entire',
  'adult',
  'life',
  'man',
  'who',
  'killed',
  'fair',
  'share',
  'men',
  'along',
  'way',
  'feel',
  'hed',
  'make',
  'good',
  'husband',
  'father',
  'theyre',
  'walking',
  'wounded',
  'unique',
  'position',
  'help',
  'need',
  'time',
  'realize',
  'ithowever',
  'packed',
  'bursting',
  'favorite',
  'theme',
  'old',
  'west',
  'setting',
  'heroine',
  'passing',
  'male',
  'morally',
  'ambiguous',
  'hero',
  'wounded',
  'soul',
  'road',
  'romance',
  'kitchen',
  'sink',
  'certaindistance',
  'writing',
  'kept',
  'getting',
  'carried',
  'away',
  'character',
  'distinct',
  'fullyformed',
  'couldnt',
  'point',
  'glaring',
  'instance',
  'bland',
  'telling',
  'anything',
  'never',
  'felt',
  'really',
  'invested',
  'enjoyed',
  'quite',
  'bit',
  'exciting',
  'trip',
  'watching',
  'far',
  'away',
  'definitely',
  'wasnt',
  'run',
  'alongside',
  'add',
  'hasty',
  'tidy',
  'ending',
  'book',
  'left',
  'feeling',
  'bit',
  'le',
  'completely',
  'satisfiedi',
  'enjoyed',
  'book',
  'cant',
  'say',
  'average',
  'id',
  'still',
  'read',
  'another',
  'book',
  'authornote',
  'read',
  'rereleased',
  'ebook',
  'version',
  'noticed',
  'lot',
  'formatting',
  'error',
  'missing',
  'word',
  'mentally',
  'edit',
  'read',
  'sentence',
  'make',
  'sense',
  'wasnt',
  'bad',
  'little',
  'distracting'],
 ['great',
  'short',
  'read',
  'didnt',
  'want',
  'put',
  'read',
  'one',
  'sitting',
  'sex',
  'scene',
  'great',
  'two',
  'male',
  'one',
  'female',
  'charactera',
  'bit',
  'surprising',
  'never',
  'thought',
  'could',
  'learned',
  'something',
  'new',
  'really',
  'enjoyed',
  'reading',
  'book',
  'great',
  'way',
  'get',
  'hot',
  'bothered',
  'take',
  'advantage',
  'significant',
  'others'],
 ['ill',
  'start',
  'saying',
  'first',
  'four',
  'book',
  'wasnt',
  'expecting',
  'conclude',
  'center',
  'child',
  'alex',
  'younger',
  'brother',
  'argus',
  'alexs',
  'friend',
  'sapphire',
  'find',
  'name',
  'bus',
  'map',
  'cant',
  'find',
  'mystery',
  'start',
  'well',
  'written',
  'good',
  'character',
  'development',
  'although',
  'lot',
  'room',
  'still',
  'moreits',
  'quite',
  'short',
  'book',
  'moving',
  'onto',
  'book',
  'swiftly'],
 ['aggie',
  'angela',
  'lansbury',
  'carry',
  'pocketbook',
  'instead',
  'writing',
  'light',
  'murder',
  'mystery',
  'laced',
  'misdirection',
  'clue',
  'lead',
  'rather',
  'obvious',
  'cliche',
  'ending',
  'setting',
  'view',
  'described',
  'story',
  'best',
  'believable',
  'part',
  'aggie',
  'wellwritten',
  'character',
  'light',
  'reading'],
 ['expect', 'type', 'book', 'library', 'pleased', 'find', 'price', 'right'],
 ['aislinn',
  'little',
  'girl',
  'big',
  'dream',
  'death',
  'older',
  'brother',
  'decides',
  'follow',
  'footstep',
  'become',
  'lady',
  'knight',
  'quest',
  'knighthood',
  'brings',
  'many',
  'challenge',
  'temptation',
  'forbidden',
  'love',
  'aislinn',
  'learns',
  'knight',
  'mean',
  'putting',
  'kingdom',
  'front',
  'personal',
  'concern',
  'helping',
  'cannot',
  'help',
  'journey',
  'fraught',
  'danger',
  'filled',
  'adventure',
  'aislinn',
  'forced',
  'grow',
  'fast',
  'must',
  'stay',
  'strong',
  'develop',
  'skill',
  'necessary',
  'realize',
  'lifelong',
  'dreamwith',
  'sword',
  'fight',
  'passionate',
  'love',
  'mythical',
  'creature',
  'courtly',
  'game',
  'woman',
  'honor',
  'kind',
  'book',
  'love',
  'idea',
  'incorporating',
  'real',
  'history',
  'fantasy',
  'zoltacks',
  'book',
  'based',
  'real',
  'life',
  'story',
  'group',
  'female',
  'knight',
  'blending',
  'history',
  'fiction',
  'writing',
  'full',
  'plot',
  'adventure',
  'character',
  'strong',
  'believable',
  'grew',
  'love',
  'cared',
  'hardship',
  'quite',
  'main',
  'protagonist',
  'shes',
  'tenacious',
  'bold',
  'beautiful',
  'strong',
  'romance',
  'bloom',
  'prince',
  'well',
  'developed',
  'year',
  'solid',
  'friendship',
  'teasing',
  'enjoyed',
  'reading',
  'secret',
  'courtship',
  'idea',
  'romance',
  'would',
  'turn',
  'zoltack',
  'twist',
  'store',
  'shock',
  'startle',
  'well',
  'pleasein',
  'conclusion',
  'thoroughly',
  'recommend',
  'book',
  'everyone',
  'enjoys',
  'fantasy',
  'romance',
  'adventure',
  'eagerly',
  'awaiting',
  'sequel',
  'knight',
  'glory'],
 ['making',
  'good',
  'story',
  'unfortunately',
  'disappointsit',
  'tell',
  'two',
  'alpha',
  'member',
  'unfriendly',
  'pack',
  'grown',
  'together',
  'one',
  'gay',
  'straight',
  'seems',
  'get',
  'together',
  'something',
  'happens',
  'story',
  'told',
  'alternating',
  'chapter',
  'past',
  'present',
  'story',
  'couple',
  'fall',
  'apart',
  'switch',
  'time',
  'lack',
  'sustainable',
  'reason',
  'break'],
 ['got',
  'like',
  'collaborated',
  'short',
  'story',
  'alot',
  'time',
  'two',
  'good',
  'writer',
  'put',
  'head',
  'together',
  'result',
  'turn',
  'well',
  'case',
  'short',
  'story',
  'writer',
  'take',
  'age',
  'old',
  'lesson',
  'turn',
  'good',
  'read',
  'begin',
  'call',
  'crazy',
  'picking',
  'hitchhiker',
  'get',
  'graphic',
  'little',
  'much',
  'taste',
  'cut',
  'nutcase',
  'hitchhiking',
  'inevitably',
  'get',
  'together',
  'result',
  'suspenseful',
  'ending',
  'felt',
  'well',
  'deserved',
  'accountsi',
  'also',
  'watched',
  'video',
  'two',
  'author',
  'decided',
  'break',
  'short',
  'story',
  'idea',
  'cool',
  'one',
  'wrote',
  'side',
  'scenario',
  'scenario',
  'without',
  'talking',
  'tier',
  'side',
  'going',
  'came',
  'bring',
  'two',
  'piece',
  'together',
  'made',
  'fit',
  'perfectly',
  'think',
  'took',
  'great',
  'talent',
  'two',
  'author',
  'take',
  'two',
  'seperate',
  'story',
  'merge',
  'well',
  'didthe',
  'story',
  'pretty',
  'graphic',
  'detail',
  'forwarned',
  'dont',
  'mind',
  'little',
  'detail',
  'short',
  'story',
  'definitely',
  'pick',
  'one'],
 ['loved',
  'book',
  'hooked',
  'series',
  'hope',
  'kelsey',
  'maxwell',
  'really',
  'made',
  'character',
  'couldnt',
  'get',
  'enough'],
 ['thats',
  'good',
  'thing',
  'short',
  'sweet',
  'tease',
  'give',
  'everything',
  'quick',
  'kick',
  'kick',
  'come',
  'dark'],
 ['received',
  'copy',
  'book',
  'review',
  'secret',
  'society',
  'fanatical',
  'cult',
  'telepathic',
  'girl',
  'cup',
  'tea',
  'expected',
  'really',
  'dont',
  'need',
  'another',
  'continuational',
  'book',
  'still',
  'havent',
  'read',
  'catching',
  'fire',
  'hunger',
  'game',
  'dont',
  'get',
  'scifi',
  'stuff',
  'cup',
  'tea',
  'sorry'],
 ['even',
  'though',
  'already',
  'know',
  'outcome',
  'still',
  'enjoyable',
  'erotic',
  'read',
  'little',
  'short',
  'taste'],
 ['read',
  'review',
  'decided',
  'give',
  'try',
  'despite',
  'review',
  'labeling',
  'brutal',
  'believe',
  'reviewer',
  'called',
  'brutal',
  'beyond',
  'disturbing',
  'read',
  'almost',
  'anything',
  'recognizing',
  'fiction',
  'returned',
  'le',
  'star',
  'rating',
  'available',
  'would',
  'used'],
 ['finished',
  'reread',
  'wicked',
  'garden',
  'say',
  'wow',
  'even',
  'novella',
  'lorelei',
  'james',
  'write',
  'story',
  'hot',
  'ereader',
  'start',
  'smokinwicked',
  'garden',
  'short',
  'story',
  'lost',
  'love',
  'reuniting',
  'little',
  'extra',
  'sumthin',
  'sumthin',
  'billy',
  'buchanan',
  'return',
  'spearfish',
  'favor',
  'business',
  'associate',
  'agreed',
  'favor',
  'also',
  'would',
  'give',
  'chance',
  'reignite',
  'spark',
  'high',
  'school',
  'flame',
  'eden',
  'lacroix',
  'past',
  'ten',
  'year',
  'regretted',
  'walking',
  'away',
  'eden',
  'eden',
  'spent',
  'last',
  'ten',
  'year',
  'building',
  'career',
  'dedicated',
  'local',
  'community',
  'center',
  'helping',
  'risk',
  'kid',
  'hasnt',
  'time',
  'real',
  'relationship',
  'occasional',
  'string',
  'attached',
  'hook',
  'ups',
  'sexy',
  'native',
  'american',
  'rock',
  'star',
  'jon',
  'white',
  'featherwhen',
  'billy',
  'eden',
  'see',
  'first',
  'time',
  'ten',
  'year',
  'chemistry',
  'spike',
  'chart',
  'eden',
  'determined',
  'fight',
  'billy',
  'working',
  'project',
  'could',
  'destroy',
  'job',
  'quickly',
  'sweet',
  'talk',
  'seeing',
  'side',
  'project',
  'thing',
  'heat',
  'eden',
  'billy',
  'realizing',
  'still',
  'strong',
  'feeling',
  'otherdunh',
  'dunh',
  'dunhjon',
  'come',
  'home',
  'couple',
  'day',
  'billy',
  'jon',
  'decide',
  'want',
  'give',
  'eden',
  'one',
  'darkest',
  'fantasy',
  'boy',
  'boy',
  'hot',
  'menagei',
  'really',
  'like',
  'eden',
  'even',
  'though',
  'worried',
  'heart',
  'billy',
  'leaving',
  'take',
  'charge',
  'sexuality',
  'scared',
  'go',
  'want',
  'sexually',
  'much',
  'liked',
  'eden',
  'story',
  'billy',
  'jon',
  'stole',
  'story',
  'men',
  'sexy',
  'strong',
  'billy',
  'possessive',
  'sexy',
  'dominant',
  'vulnerable',
  'absolutely',
  'adore',
  'way',
  'treat',
  'eden',
  'insecurity',
  'display',
  'jonoh',
  'favorite',
  'dont',
  'get',
  'wrong',
  'love',
  'billy',
  'way',
  'jon',
  'treat',
  'eden',
  'menage',
  'melt',
  'heart',
  'among',
  'thing',
  'mention',
  'jon',
  'sexy',
  'rock',
  'star',
  'moon',
  'excited',
  'jon',
  'getting',
  'novella',
  'ballroom',
  'blitz',
  'release',
  'date',
  'folkslet',
  'tell',
  'youif',
  'could',
  'get',
  'action',
  'went',
  'work',
  'room',
  'wicked',
  'garden',
  'would',
  'work',
  'room',
  'five',
  'ten',
  'time',
  'daywicked',
  'garden',
  'great',
  'novella',
  'perfect',
  'afternoon',
  'want',
  'escape',
  'hour',
  'bonus',
  'get',
  'see',
  'sexy',
  'lorelei',
  'writes',
  'noncowboys',
  'yep',
  'cowboy',
  'hat',
  'suit',
  'james',
  'know',
  'write',
  'sexy',
  'hell',
  'hero'],
 ['king',
  'james',
  'version',
  'far',
  'tell',
  'may',
  'know',
  'kjv',
  'published',
  'book',
  'included',
  'get',
  'ebook',
  'kjv',
  'apocrypha',
  'kindlebible',
  'kjv',
  'apocrypha',
  'best',
  'navigation',
  'direct',
  'verse',
  'jumporking',
  'james',
  'bible',
  'apocryphaorking',
  'james',
  'bible',
  'apocryphafor',
  'want',
  'read',
  'commentary',
  'book',
  'provided',
  'short',
  'intro',
  'misbach',
  'refer',
  'either',
  'halley',
  'bible',
  'handbookhalleys',
  'bible',
  'handbook',
  'new',
  'international',
  'versiondeluxe',
  'editionor',
  'new',
  'ungers',
  'bible',
  'handbookthe',
  'new',
  'ungers',
  'bible',
  'handbook',
  'available',
  'kindle',
  'ebooks'],
 ['disappointed',
  'book',
  'anything',
  'blond',
  'one',
  'figured',
  'joke',
  'good',
  'laugh',
  'wrong',
  'first',
  'didnt',
  'count',
  'id',
  'real',
  'surprised',
  'even',
  'joke',
  'book',
  'second',
  'among',
  'possible',
  'joke',
  'least',
  'repeated',
  'time',
  'different',
  'part',
  'book',
  'almost',
  'writer',
  'kept',
  'running',
  'list',
  'joke',
  'heard',
  'real',
  'concern',
  'whether',
  'might',
  'already',
  'recorded',
  'decided',
  'must',
  'least',
  'joke',
  'finally',
  'perfectly',
  'frank',
  'recall',
  'laughing',
  'single',
  'one',
  'joke',
  'better',
  'described',
  'insult',
  'mistaking',
  'degradation',
  'group',
  'people',
  'humor',
  'th',
  'grade',
  'material',
  'dont',
  'bother',
  'one',
  'worth',
  'cent',
  'even',
  'worth',
  'free'],
 ['super',
  'quick',
  'book',
  'wish',
  'would',
  'longer',
  'really',
  'liked',
  'character',
  'sexy',
  'bedroom',
  'pool',
  'table',
  'sex',
  'good',
  'author'],
 ['many',
  'time',
  'author',
  'going',
  'get',
  'amazon',
  'delete',
  'add',
  'comment',
  'alleged',
  'conspiracy',
  'people',
  'get',
  'fin',
  'delusional',
  'reviewi',
  'agree',
  'previous',
  'reviewer',
  'author',
  'doesnt',
  'know',
  'basic',
  'mechanic',
  'writing',
  'world',
  'he',
  'written',
  'full',
  'star',
  'there',
  'page',
  'isnt',
  'filled',
  'grammar',
  'problem',
  'story',
  'suffers',
  'problem',
  'author',
  'inattention',
  'detail',
  'character',
  'inconsistent',
  'action',
  'like',
  'theyre',
  'interchangeable',
  'peg',
  'board',
  'author',
  'put',
  'place',
  'need'],
 ['love',
  'jr',
  'ward',
  'book',
  'story',
  'completely',
  'awsome',
  'zsadist',
  'favorite',
  'series'],
 ['first',
  'author',
  'thoroughly',
  'enjoyed',
  'iti',
  'say',
  'concept',
  'dragon',
  'elf',
  'djinn',
  'war',
  'new',
  'there',
  'usually',
  'truce',
  'place',
  'elf',
  'djinn',
  'team',
  'eliminate',
  'dragon',
  'mate',
  'attempt',
  'wipe',
  'dragon',
  'race',
  'refreshing',
  'read',
  'story',
  'wise',
  'meanscarlet',
  'pop',
  'star',
  'hiding',
  'yearsjanos',
  'dragon',
  'also',
  'elderscarlet',
  'mate',
  'janos',
  'must',
  'protect',
  'till',
  'impregnate',
  'accomplished',
  'change',
  'thus',
  'giving',
  'way',
  'protect',
  'herselfthe',
  'story',
  'short',
  'page',
  'still',
  'lot',
  'told',
  'short',
  'space',
  'looking',
  'forward',
  'continuing',
  'saga',
  'next',
  'book'],
 ['first',
  'anya',
  'bast',
  'book',
  'really',
  'liked',
  'looked',
  'read',
  'book',
  'seems',
  'little',
  'far',
  'fetched',
  'make',
  'book',
  'different',
  'menage',
  'story',
  'author',
  'took',
  'time',
  'really',
  'develop',
  'character',
  'men',
  'got',
  'know',
  'woman',
  'claim',
  'wisk',
  'screw',
  'like',
  'bunny',
  'took',
  'time',
  'woo',
  'loved',
  'respected',
  'honored',
  'also',
  'loved',
  'fact',
  'quite',
  'way',
  'book',
  'actually',
  'sex',
  'great',
  'read',
  'one',
  'would',
  'highly',
  'recommend',
  'would',
  'loved',
  'action',
  'intrigue',
  'part',
  'loved',
  'hope',
  'book',
  'becomes',
  'series',
  'great',
  'job',
  'bast'],
 ['love',
  'reading',
  'mini',
  'novel',
  'cant',
  'go',
  'wrong',
  'jane',
  'porter',
  'yet',
  'another',
  'great',
  'read',
  'amazingly',
  'talented',
  'author',
  'fell',
  'love',
  'estrella',
  'beautiful',
  'strong',
  'compassionate',
  'determined',
  'carlo',
  'man',
  'want',
  'hate',
  'instead',
  'end',
  'wishing',
  'enjoyed',
  'book',
  'beginning',
  'end',
  'character',
  'personality',
  'draw',
  'storyline',
  'make',
  'want',
  'reach',
  'help',
  'le',
  'fortunate',
  'highly',
  'recommend',
  'mini',
  'novel',
  'perfect',
  'marriage',
  'love',
  'hate',
  'romance',
  'philanthropy'],
 ['book',
  'extremely',
  'incredible',
  'read',
  'much',
  'heated',
  'passion',
  'describe',
  'every',
  'steele',
  'relationship',
  'im',
  'glad',
  'brother',
  'cousin',
  'found',
  'passionate',
  'love',
  'last'],
 ['whats',
  'difference',
  'guy',
  'man',
  'willingness',
  'take',
  'risk',
  'relationship',
  'woman',
  'course',
  'he',
  'hot',
  'shes',
  'hot',
  'physical',
  'attraction',
  'explosive',
  'enjoyable',
  'earn',
  'star',
  'genre',
  'earned',
  'th',
  'star',
  'quality',
  'interaction',
  'various',
  'character',
  'bookthe',
  'book',
  'quick',
  'short',
  'read',
  'right',
  'palate',
  'pleaser',
  'want',
  'bit',
  'romance',
  'sex',
  'dont',
  'want',
  'commit'],
 ['gave',
  'half',
  'way',
  'much',
  'repetition',
  'much',
  'didnt',
  'make',
  'sense',
  'hard',
  'follow'],
 ['dont',
  'know',
  'expecting',
  'way',
  'form',
  'fashion',
  'book',
  'exciting',
  'think',
  'ordered',
  'wrong',
  'book',
  'accident'],
 ['love',
  'read',
  'simon',
  'wood',
  'book',
  'one',
  'morbid',
  'make',
  'reader',
  'victim',
  'skin',
  'crawl',
  'much',
  'guessing',
  'outright',
  'gruesome'],
 ['short',
  'story',
  'confusingi',
  'issue',
  'unreliable',
  'narrator',
  'difficult',
  'tell',
  'happening',
  'story',
  'writing',
  'poor',
  'reader',
  'able',
  'draw',
  'conclusion',
  'virtually',
  'everybody',
  'story',
  'difficulty',
  'relating',
  'others',
  'conversation',
  'begin',
  'trail',
  'without',
  'important',
  'information',
  'related',
  'author',
  'doesnt',
  'prevent',
  'normal',
  'interaction',
  'able',
  'judge',
  'character',
  'one',
  'difficult',
  'understanding',
  'normal',
  'human',
  'interaction',
  'problem',
  'actually',
  'assumed',
  'main',
  'character',
  'mentally',
  'unbalanced',
  'waiting',
  'develop',
  'throughout',
  'story',
  'however',
  'story',
  'ended',
  'apparently',
  'become',
  'normal',
  'making',
  'unfulfilling',
  'conclusion',
  'set',
  'weird',
  'situation',
  'short',
  'story',
  'foreshadowing',
  'leave',
  'unexplored',
  'unexplained',
  'way',
  'author',
  'advance',
  'story',
  'tell',
  'simple',
  'sentence',
  'type',
  'people',
  'character',
  'thing',
  'like',
  'nice',
  'person',
  'liked',
  'people',
  'didnt',
  'know',
  'way',
  'never',
  'shown',
  'anything',
  'action',
  'story',
  'people',
  'put',
  'situation',
  'weird',
  'trailingoff',
  'conversation',
  'subjected',
  'basic',
  'statement',
  'type',
  'people',
  'arethe',
  'environment',
  'isnt',
  'realistic',
  'either',
  'odd',
  'wording',
  'thought',
  'first',
  'maybe',
  'story',
  'set',
  'another',
  'country',
  'character',
  'mention',
  'michigan',
  'sense',
  'place',
  'got',
  'story',
  'know',
  'michigan',
  'city',
  'dont',
  'hope',
  'anything',
  'specific',
  'place',
  'independent',
  'office',
  'supply',
  'story',
  'still',
  'business',
  'afford',
  'pay',
  'ten',
  'dollar',
  'hour',
  'part',
  'time',
  'help',
  'modern',
  'time',
  'dont',
  'hope',
  'anything',
  'specific',
  'wont',
  'happeningthe',
  'character',
  'seem',
  'know',
  'thing',
  'would',
  'know',
  'example',
  'character',
  'war',
  'returned',
  'home',
  'worked',
  'another',
  'type',
  'job',
  'later',
  'old',
  'bruise',

In [130]:
import gensim

model = gensim.models.Word2Vec(
  sentences = words,
  vector_size = 300,
)

In [132]:
## To get all the vocabulary
model.wv.index_to_key

['book',
 'story',
 'read',
 'one',
 'character',
 'like',
 'good',
 'would',
 'really',
 'love',
 'time',
 'get',
 'author',
 'reading',
 'series',
 'much',
 'first',
 'well',
 'even',
 'didnt',
 'short',
 'know',
 'way',
 'could',
 'great',
 'make',
 'sex',
 'little',
 'dont',
 'thing',
 'want',
 'two',
 'think',
 'find',
 'plot',
 'also',
 'romance',
 'end',
 'life',
 'im',
 'see',
 'enjoyed',
 'go',
 'scene',
 'never',
 'take',
 'woman',
 'many',
 'lot',
 'written',
 'kindle',
 'say',
 'work',
 'thought',
 'bit',
 'found',
 'year',
 'going',
 'give',
 'interesting',
 'liked',
 'writing',
 'novel',
 'loved',
 'another',
 'feel',
 'better',
 'got',
 'come',
 'man',
 'hot',
 'still',
 'enough',
 'back',
 'though',
 'people',
 'reader',
 'made',
 'star',
 'review',
 'something',
 'part',
 'friend',
 'cant',
 'page',
 'need',
 'bad',
 'keep',
 'new',
 'wasnt',
 'free',
 'world',
 'doesnt',
 'relationship',
 'enjoy',
 'recommend',
 'together',
 'next',
 'start',
 'felt',
 'best',
 'put',
 'main',
 'word',
 'guy',
 'looking',
 'fun',
 'since',
 'however',
 'hard',
 'long',
 'day',
 'line',
 'real',
 'ive',
 'sure',
 'couldnt',
 'different',
 'point',
 'without',
 'right',
 'ending',
 'wanted',
 'family',
 'nothing',
 'shes',
 'always',
 'anything',
 'every',
 'definitely',
 'hero',
 'ever',
 'look',
 'men',
 'heroine',
 'help',
 'he',
 'worth',
 'actually',
 'action',
 'fact',
 'pretty',
 'quite',
 'let',
 'three',
 'left',
 'old',
 'whole',
 'feeling',
 'around',
 'problem',
 'place',
 'seemed',
 'idea',
 'tell',
 'second',
 'try',
 'might',
 'nice',
 'sexy',
 'someone',
 'brother',
 'away',
 'kind',
 'getting',
 'isnt',
 'thats',
 'vampire',
 'started',
 'may',
 'chapter',
 'almost',
 'mystery',
 'far',
 'issue',
 'novella',
 'turn',
 'done',
 'couple',
 'yet',
 'tale',
 'seems',
 'kept',
 'set',
 'girl',
 'last',
 'past',
 'everything',
 'others',
 'reason',
 'maybe',
 'quick',
 'finish',
 'trying',
 'beginning',
 'mind',
 'said',
 'wish',
 'writer',
 'description',
 'job',
 'hope',
 'strong',
 'full',
 'believe',
 'fantasy',
 'mate',
 'meet',
 'must',
 'night',
 'father',
 'development',
 'least',
 'there',
 'erotic',
 'sweet',
 'fan',
 'care',
 'easy',
 'mean',
 'anyone',
 'able',
 'home',
 'wont',
 'especially',
 'although',
 'human',
 'understand',
 'happy',
 'money',
 'big',
 'forward',
 'id',
 'buy',
 'young',
 'show',
 'detail',
 'went',
 'used',
 'person',
 'fast',
 'took',
 'storyline',
 'sexual',
 'disappointed',
 'style',
 'seem',
 'probably',
 'gave',
 'child',
 'write',
 'wait',
 'rather',
 'favorite',
 'instead',
 'sense',
 'true',
 'interest',
 'rest',
 'use',
 'case',
 'along',
 'price',
 'heart',
 'type',
 'given',
 'le',
 'high',
 'several',
 'lost',
 'longer',
 'wonderful',
 'wrong',
 'else',
 'male',
 'told',
 'female',
 'came',
 'change',
 'twist',
 'fall',
 'knew',
 'error',
 'perfect',
 'cover',
 'ok',
 'alpha',
 'either',
 'finally',
 'side',
 'completely',
 'glad',
 'course',
 'stop',
 'developed',
 'later',
 'lead',
 'husband',
 'overall',
 'light',
 'enjoyable',
 'happened',
 'making',
 'happens',
 'half',
 'name',
 'order',
 'youre',
 'future',
 'waste',
 'quickly',
 'fiction',
 'wolf',
 'interested',
 'premise',
 'bought',
 'everyone',
 'already',
 'boring',
 'finished',
 'okay',
 'become',
 'situation',
 'wife',
 'attention',
 'needed',
 'happen',
 'believable',
 'ill',
 'sister',
 'steamy',
 'amazon',
 'entire',
 'wouldnt',
 'eye',
 'lover',
 'truly',
 'chance',
 'highly',
 'moment',
 'town',
 'boy',
 'mother',
 'guess',
 'sometimes',
 'ended',
 'school',
 'thinking',
 'funny',
 'dialogue',
 'dark',
 'call',
 'yes',
 'werewolf',
 'follow',
 'title',
 'genre',
 'move',
 'totally',
 'leave',
 'live',
 'head',
 'paranormal',
 'lack',
 'entertaining',
 'sort',
 'romantic',
 'house',
 'length',
 'war',
 'pick',
 'version',
 'coming',
 'sorry',
 'add',
 'language',
 'age',
 'hand',
 'usually',
 'editing',
 'reviewer',
 'deal',
 'run',
 'pack',
 'experience',
 'stand',
 'expected',
 'turned',
 'expect',
 'secret',
 'giving',
 'begin',
 'soon',
 'matter',
 'potential',
 'month',
 'save',
 'depth',
 'erotica',
 'figure',
 'throughout',
 'adult',
 'wanting',
 'dream',
 'ago',
 'alone',
 'simply',
 'absolutely',
 'hour',
 'decided',
 'oh',
 'unfortunately',
 'death',
 'collection',
 'often',
 'poor',
 'theyre',
 'third',
 'small',
 'difficult',
 'emotion',
 'adventure',
 'gay',
 'history',
 'certainly',
 'hold',
 'hate',
 'excellent',
 'supposed',
 'setting',
 'event',
 'face',
 'stay',
 'bed',
 'called',
 'spent',
 'humor',
 'movie',
 'talk',
 'easily',
 'top',
 'complete',
 'dragon',
 'opinion',
 'slow',
 'missing',
 'perhaps',
 'four',
 'shifter',
 'rating',
 'learn',
 'continue',
 'suspense',
 'tried',
 'attraction',
 'group',
 'across',
 'minute',
 'cute',
 'fight',
 'plan',
 'living',
 'god',
 'killer',
 'beautiful',
 'sentence',
 'marriage',
 'list',
 'realize',
 'play',
 'soul',
 'pay',
 'information',
 'finding',
 'break',
 'power',
 'question',
 'kill',
 'married',
 'extremely',
 'based',
 'involved',
 'background',
 'week',
 'predictable',
 'five',
 'mr',
 'kid',
 'taking',
 'surprised',
 'remember',
 'behind',
 'seen',
 'within',
 'body',
 'amazing',
 'surprise',
 'murder',
 'beyond',
 'son',
 'hell',
 'middle',
 'waiting',
 'became',
 'daughter',
 'stuff',
 'magic',
 'level',
 'desire',
 'met',
 'concept',
 'example',
 'known',
 'content',
 'youll',
 'emotional',
 'saying',
 'fit',
 'immediately',
 'heat',
 'aspect',
 'form',
 'mistake',
 'business',
 'view',
 'force',
 'etc',
 'lady',
 'trouble',
 'choice',
 'early',
 'fell',
 'saw',
 'hunter',
 'exactly',
 'seeing',
 'number',
 'working',
 'loving',
 'downloaded',
 'close',
 'ability',
 'james',
 'spoiler',
 'room',
 'mark',
 'admit',
 'science',
 'connection',
 'bring',
 'chemistry',
 'original',
 'due',
 'seriously',
 'wonder',
 'share',
 'editor',
 'taken',
 'christmas',
 'huge',
 'cannot',
 'picture',
 'brought',
 'willing',
 'open',
 'hoping',
 'somewhat',
 'clear',
 'becomes',
 'important',
 'paid',
 'previous',
 'simple',
 'alex',
 'drawn',
 'leaf',
 'check',
 'havent',
 'return',
 'building',
 'forced',
 'ready',
 'special',
 'expecting',
 'sequel',
 'tension',
 'reviewed',
 'demon',
 'older',
 'offer',
 'despite',
 'arent',
 'partner',
 'realistic',
 'unique',
 'element',
 'spend',
 'mostly',
 'black',
 'annoying',
 'using',
 'hurt',
 'fine',
 'dead',
 'mention',
 'bdsm',
 'personal',
 'space',
 'evil',
 'serial',
 'bother',
 'decides',
 'trust',
 'conflict',
 'piece',
 'note',
 'classic',
 'weak',
 'serious',
 'present',
 'passion',
 'earth',
 'please',
 'quality',
 'caught',
 'telling',
 'decent',
 'taste',
 'fairy',
 'described',
 'download',
 'fairly',
 'except',
 'picked',
 'worked',
 'upon',
 'strange',
 'flow',
 'rushed',
 'mentioned',
 'certain',
 'none',
 'act',
 'graphic',
 'christian',
 'filled',
 'control',
 'grammar',
 'plus',
 'honest',
 'ebook',
 'zombie',
 'lose',
 'build',
 'paragraph',
 'buying',
 'basically',
 'stupid',
 'exciting',
 'writes',
 'agree',
 'amount',
 'historical',
 'sad',
 'fear',
 'major',
 'horror',
 'knowing',
 'crazy',
 'car',
 'police',
 'menage',
 'straight',
 'including',
 'date',
 'parent',
 'blake',
 'thoroughly',
 'drama',
 'available',
 'neither',
 'wrote',
 'alien',
 'ghost',
 'gone',
 'typo',
 'touch',
 'king',
 'scifi',
 'copy',
 'whats',
 'particularly',
 'paper',
 'blog',
 'normally',
 'thrown',
 'game',
 'purchased',
 'purchase',
 'talking',
 'nature',
 'confusing',
 'whether',
 'honestly',
 'added',
 'angel',
 'accept',
 'club',
 'held',
 'intriguing',
 'single',
 'cat',
 'hit',
 'protagonist',
 'sound',
 'theme',
 'personality',
 'marry',
 'fully',
 'poorly',
 'unless',
 'attempt',
 'super',
 'determined',
 'promise',
 'miss',
 'worst',
 'john',
 'meeting',
 'recommended',
 'knight',
 'basic',
 'wedding',
 'boyfriend',
 'baby',
 'struggle',
 'kate',
 'edition',
 'encounter',
 'blood',
 'suddenly',
 'joyfully',
 'typical',
 'lord',
 'master',
 'pas',
 'horrible',
 'actual',
 'published',
 'term',
 'thank',
 'awesome',
 'introduced',
 'deep',
 'fighting',
 'fantastic',
 'hooked',
 'develop',
 'possible',
 'escape',
 'silly',
 'thriller',
 'flat',
 'animal',
 'imagine',
 'effort',
 'focus',
 'trilogy',
 'cause',
 'sample',
 'voice',
 'decision',
 'belief',
 'pace',
 'th',
 'near',
 'prequel',
 'stopped',
 'interaction',
 'kelly',
 'cut',
 'otherwise',
 'ridiculous',
 'moved',
 'modern',
 'conversation',
 'max',
 'jane',
 'odd',
 'leaving',
 'moving',
 'edge',
 'realized',
 'pleasure',
 'step',
 'reality',
 'plenty',
 'anyway',
 'truth',
 'area',
 'self',
 'apparently',
 'running',
 'st',
 'paced',
 'protect',
 'subject',
 'watching',
 'created',
 'period',
 'reread',
 'difference',
 'article',
 'changed',
 'confused',
 'missed',
 'jump',
 'unbelievable',
 'pull',
 'werent',
 'engaging',
 'consider',
 'turning',
 'worse',
 'land',
 'rich',
 'american',
 'simon',
 'jack',
 'wow',
 'disappointing',
 'particular',
 'wondering',
 'detective',
 'afraid',
 'city',
 'decide',
 'familiar',
 'danger',
 'nearly',
 'looked',
 'rape',
 'english',
 'fire',
 'satisfying',
 'pain',
 'explanation',
 'mm',
 'draw',
 'door',
 'today',
 'company',
 'journey',
 'violence',
 'skip',
 'ask',
 'beauty',
 'happily',
 'reference',
 'party',
 'battle',
 'falling',
 'weird',
 'location',
 'explicit',
 'crime',
 'throw',
 'lust',
 'appreciate',
 'bored',
 'normal',
 'late',
 'literally',
 'final',
 'grab',
 'society',
 'state',
 'lacking',
 'answer',
 'warning',
 'laugh',
 'west',
 'magazine',
 'jake',
 'keeping',
 'us',
 'killed',
 'cop',
 'solid',
 'slave',
 'conclusion',
 'brings',
 'similar',
 'killing',
 'hadnt',
 'obviously',
 'towards',
 'terrible',
 'news',
 'outside',
 'eventually',
 'cold',
 'doubt',
 'starting',
 'apart',
 'meant',
 'product',
 'race',
 'imagination',
 'likable',
 'ex',
 'mysterious',
 'college',
 'claim',
 'current',
 'speak',
 'ship',
 'purpose',
 'realizes',
 'comment',
 'inside',
 'trip',
 'wild',
 'emma',
 'law',
 'role',
 'introduction',
 'research',
 'formatting',
 'barely',
 'red',
 'yeah',
 'attracted',
 'result',
 'holly',
 'member',
 'obvious',
 'section',
 'physical',
 'team',
 'owner',
 'lie',
 'following',
 'adam',
 'henry',
 'smart',
 'happening',
 'enjoying',
 'usual',
 'win',
 'complaint',
 'incredibly',
 'tired',
 'travel',
 'hea',
 'intense',
 'received',
 'continues',
 'walk',
 'installment',
 'bond',
 'putting',
 'younger',
 'freebie',
 'included',
 'constantly',
 'rough',
 'describe',
 'letter',
 'ride',
 'lived',
 'white',
 'country',
 'military',
 'appears',
 'rate',
 'verne',
 'cousin',
 'catch',
 'awful',
 'handsome',
 'likeable',
 'front',
 'forever',
 'friendship',
 'sounded',
 'island',
 'witch',
 'victim',
 'cowboy',
 'nicely',
 'format',
 'general',
 'began',
 'memory',
 'creature',
 'explained',
 'powerful',
 'detailed',
 'whose',
 ...]

In [133]:
model.corpus_count

12000

In [134]:
model.epochs

5

In [135]:
model.wv.similar_by_word('book')

[('booki', 0.8218869566917419),
 ('probably', 0.8109612464904785),
 ('disappointed', 0.8104057908058167),
 ('onei', 0.809932291507721),
 ('reviewer', 0.8073897361755371),
 ('sequel', 0.8049461245536804),
 ('chapter', 0.7993682026863098),
 ('reel', 0.7942773699760437),
 ('title', 0.7929509878158569),
 ('hooked', 0.7913963794708252)]

In [136]:
model.wv.similar_by_word('kindle')

[('version', 0.9462564587593079),
 ('amazon', 0.931168258190155),
 ('edition', 0.9143654108047485),
 ('blog', 0.8915932178497314),
 ('available', 0.8872676491737366),
 ('ebook', 0.8795143961906433),
 ('print', 0.878328263759613),
 ('price', 0.870414137840271),
 ('copy', 0.8696362376213074),
 ('article', 0.8623635768890381)]

In [137]:
import numpy as np

vocabulary = model.wv.index_to_key

def avg_word2vec(doc):

  # Remove Out-Of-Vocabulary words
  # sent = [word for word in doc if word not in model.wv.index_to_key] # vocabulary = model.wv.index_to_key 
  # print(sent)

  return np.mean([model.wv[word] for word in doc if word in vocabulary], axis=0)

In [138]:
from tqdm import tqdm

## apply for the entire sentence

X = []

for i in tqdm(range(len(words))):
  print("Hello", i)
  X.append(avg_word2vec(words[i]))

  1%|          | 98/12000 [00:00<00:24, 488.70it/s]

Hello 0
Hello 1
Hello 2
Hello 3
Hello 4
Hello 5
Hello 6
Hello 7
Hello 8
Hello 9
Hello 10
Hello 11
Hello 12
Hello 13
Hello 14
Hello 15
Hello 16
Hello 17
Hello 18
Hello 19
Hello 20
Hello 21
Hello 22
Hello 23
Hello 24
Hello 25
Hello 26
Hello 27
Hello 28
Hello 29
Hello 30
Hello 31
Hello 32
Hello 33
Hello 34
Hello 35
Hello 36
Hello 37
Hello 38
Hello 39
Hello 40
Hello 41
Hello 42
Hello 43
Hello 44
Hello 45
Hello 46
Hello 47
Hello 48
Hello 49
Hello 50
Hello 51
Hello 52
Hello 53
Hello 54
Hello 55
Hello 56
Hello 57
Hello 58
Hello 59
Hello 60
Hello 61
Hello 62
Hello 63
Hello 64
Hello 65
Hello 66
Hello 67
Hello 68
Hello 69
Hello 70
Hello 71
Hello 72
Hello 73
Hello 74
Hello 75
Hello 76
Hello 77
Hello 78
Hello 79
Hello 80
Hello 81
Hello 82
Hello 83
Hello 84
Hello 85
Hello 86
Hello 87
Hello 88
Hello 89
Hello 90
Hello 91
Hello 92
Hello 93
Hello 94
Hello 95
Hello 96
Hello 97

  1%|          | 149/12000 [00:00<00:24, 477.80it/s]

Hello 98
Hello 99
Hello 100
Hello 101
Hello 102
Hello 103
Hello 104
Hello 105
Hello 106
Hello 107
Hello 108
Hello 109
Hello 110
Hello 111
Hello 112
Hello 113
Hello 114
Hello 115
Hello 116
Hello 117
Hello 118
Hello 119
Hello 120
Hello 121
Hello 122
Hello 123
Hello 124
Hello 125
Hello 126
Hello 127
Hello 128
Hello 129
Hello 130
Hello 131
Hello 132
Hello 133
Hello 134
Hello 135
Hello 136
Hello 137
Hello 138
Hello 139
Hello 140
Hello 141
Hello 142
Hello 143
Hello 144
Hello 145
Hello 146
Hello 147
Hello 148
Hello 149
Hello 150
Hello 151
Hello 152
Hello 153
Hello 154
Hello 155
Hello 156
Hello 157
Hello 158
Hello 159
Hello 160
Hello 161
Hello 162
Hello 163
Hello 164
Hello 165
Hello 166
Hello 167
Hello 168
Hello 169
Hello 170
Hello 171
Hello 172
Hello 173
Hello 174
Hello 175
Hello 176
Hello 177
Hello 178
Hello 179
Hello 180
Hello 181
Hello 182
Hello 183
Hello 184
Hello 185
Hello 186
Hello 187
Hello 188
Hello 189
Hello 190

  2%|▏         | 279/12000 [00:00<00:20, 561.45it/s]

Hello 191
Hello 192
Hello 193
Hello 194
Hello 195
Hello 196
Hello 197
Hello 198
Hello 199
Hello 200
Hello 201
Hello 202
Hello 203
Hello 204
Hello 205
Hello 206
Hello 207
Hello 208
Hello 209
Hello 210
Hello 211
Hello 212
Hello 213
Hello 214
Hello 215
Hello 216
Hello 217
Hello 218
Hello 219
Hello 220
Hello 221
Hello 222
Hello 223
Hello 224
Hello 225
Hello 226
Hello 227
Hello 228
Hello 229
Hello 230
Hello 231
Hello 232
Hello 233
Hello 234
Hello 235
Hello 236
Hello 237
Hello 238
Hello 239
Hello 240
Hello 241
Hello 242
Hello 243
Hello 244
Hello 245
Hello 246
Hello 247
Hello 248
Hello 249
Hello 250
Hello 251
Hello 252
Hello 253
Hello 254
Hello 255
Hello 256
Hello 257
Hello 258
Hello 259
Hello 260
Hello 261
Hello 262
Hello 263
Hello 264
Hello 265
Hello 266
Hello 267
Hello 268
Hello 269
Hello 270
Hello 271
Hello 272
Hello 273
Hello 274
Hello 275
Hello 276
Hello 277
Hello 278
Hello 279
Hello 280
Hello 281
Hello 282
Hello 283
Hello 284
Hello 285
Hello 286
Hello 287
Hello 288
Hello 289
Hello 290
Hello 291
Hello 292
Hello 293
Hello 294
Hello 295
Hello 296
Hello 297
Hello 298
Hello 299
Hello 300
Hello 301
Hello 302
Hello 303
Hello 304
Hello 305
Hello 306
Hello 307
Hello 308
Hello 309
Hello 310
Hello 311
Hello 312
Hello 313
Hello 314
Hello 315
Hello 316
Hello 317
Hello 318
Hello 319
Hello 320
Hello 321
Hello 322
Hello 323
Hello 324

  3%|▎         | 392/12000 [00:00<00:24, 477.44it/s]

Hello 325
Hello 326
Hello 327
Hello 328
Hello 329
Hello 330
Hello 331
Hello 332
Hello 333
Hello 334
Hello 335
Hello 336
Hello 337
Hello 338
Hello 339
Hello 340
Hello 341
Hello 342
Hello 343
Hello 344
Hello 345
Hello 346
Hello 347
Hello 348
Hello 349
Hello 350
Hello 351
Hello 352
Hello 353
Hello 354
Hello 355
Hello 356
Hello 357
Hello 358
Hello 359
Hello 360
Hello 361
Hello 362
Hello 363
Hello 364
Hello 365
Hello 366
Hello 367
Hello 368
Hello 369
Hello 370
Hello 371
Hello 372
Hello 373
Hello 374
Hello 375
Hello 376
Hello 377
Hello 378
Hello 379
Hello 380
Hello 381
Hello 382
Hello 383
Hello 384
Hello 385
Hello 386
Hello 387
Hello 388
Hello 389
Hello 390
Hello 391
Hello 392
Hello 393
Hello 394
Hello 395
Hello 396
Hello 397
Hello 398
Hello 399
Hello 400
Hello 401
Hello 402
Hello 403
Hello 404
Hello 405
Hello 406
Hello 407
Hello 408
Hello 409
Hello 410
Hello 411
Hello 412
Hello 413
Hello 414
Hello 415
Hello 416
Hello 417
Hello 418
Hello 419
Hello 420
Hello 421
Hello 422

  4%|▍         | 457/12000 [00:00<00:24, 471.84it/s]

Hello 423
Hello 424
Hello 425
Hello 426
Hello 427
Hello 428
Hello 429
Hello 430
Hello 431
Hello 432
Hello 433
Hello 434
Hello 435
Hello 436
Hello 437
Hello 438
Hello 439
Hello 440
Hello 441
Hello 442
Hello 443
Hello 444
Hello 445
Hello 446
Hello 447
Hello 448
Hello 449
Hello 450
Hello 451
Hello 452
Hello 453
Hello 454
Hello 455
Hello 456
Hello 457
Hello 458
Hello 459
Hello 460
Hello 461
Hello 462
Hello 463
Hello 464
Hello 465
Hello 466
Hello 467
Hello 468
Hello 469
Hello 470
Hello 471
Hello 472
Hello 473
Hello 474
Hello 475
Hello 476
Hello 477
Hello 478
Hello 479
Hello 480
Hello 481
Hello 482
Hello 483
Hello 484
Hello 485
Hello 486
Hello 487
Hello 488
Hello 489
Hello 490
Hello 491
Hello 492
Hello 493
Hello 494
Hello 495
Hello 496

  5%|▍         | 550/12000 [00:01<00:27, 420.55it/s]

Hello 497
Hello 498
Hello 499
Hello 500
Hello 501
Hello 502
Hello 503
Hello 504
Hello 505
Hello 506
Hello 507
Hello 508
Hello 509
Hello 510
Hello 511
Hello 512
Hello 513
Hello 514
Hello 515
Hello 516
Hello 517
Hello 518
Hello 519
Hello 520
Hello 521
Hello 522
Hello 523
Hello 524
Hello 525
Hello 526
Hello 527
Hello 528
Hello 529
Hello 530
Hello 531
Hello 532
Hello 533
Hello 534
Hello 535
Hello 536
Hello 537
Hello 538
Hello 539
Hello 540
Hello 541
Hello 542
Hello 543
Hello 544
Hello 545
Hello 546
Hello 547
Hello 548
Hello 549
Hello 550
Hello 551
Hello 552
Hello 553
Hello 554
Hello 555
Hello 556
Hello 557
Hello 558
Hello 559
Hello 560
Hello 561
Hello 562
Hello 563
Hello 564
Hello 565
Hello 566
Hello 567
Hello 568
Hello 569
Hello 570
Hello 571
Hello 572
Hello 573
Hello 574
Hello 575
Hello 576
Hello 577
Hello 578
Hello 579
Hello 580
Hello 581
Hello 582
Hello 583
Hello 584
Hello 585

  5%|▌         | 652/12000 [00:01<00:24, 460.87it/s]

Hello 586
Hello 587
Hello 588
Hello 589
Hello 590
Hello 591
Hello 592
Hello 593
Hello 594
Hello 595
Hello 596
Hello 597
Hello 598
Hello 599
Hello 600
Hello 601
Hello 602
Hello 603
Hello 604
Hello 605
Hello 606
Hello 607
Hello 608
Hello 609
Hello 610
Hello 611
Hello 612
Hello 613
Hello 614
Hello 615
Hello 616
Hello 617
Hello 618
Hello 619
Hello 620
Hello 621
Hello 622
Hello 623
Hello 624
Hello 625
Hello 626
Hello 627
Hello 628
Hello 629
Hello 630
Hello 631
Hello 632
Hello 633
Hello 634
Hello 635
Hello 636
Hello 637
Hello 638
Hello 639
Hello 640
Hello 641
Hello 642
Hello 643
Hello 644
Hello 645
Hello 646
Hello 647
Hello 648
Hello 649
Hello 650
Hello 651
Hello 652
Hello 653
Hello 654
Hello 655
Hello 656
Hello 657
Hello 658
Hello 659
Hello 660
Hello 661
Hello 662
Hello 663
Hello 664
Hello 665
Hello 666
Hello 667
Hello 668
Hello 669
Hello 670
Hello 671
Hello 672
Hello 673
Hello 674
Hello 675
Hello 676
Hello 677
Hello 678
Hello 679
Hello 680
Hello 681

  6%|▌         | 747/12000 [00:01<00:24, 459.53it/s]

Hello 682
Hello 683
Hello 684
Hello 685
Hello 686
Hello 687
Hello 688
Hello 689
Hello 690
Hello 691
Hello 692
Hello 693
Hello 694
Hello 695
Hello 696
Hello 697
Hello 698
Hello 699
Hello 700
Hello 701
Hello 702
Hello 703
Hello 704
Hello 705
Hello 706
Hello 707
Hello 708
Hello 709
Hello 710
Hello 711
Hello 712
Hello 713
Hello 714
Hello 715
Hello 716
Hello 717
Hello 718
Hello 719
Hello 720
Hello 721
Hello 722
Hello 723
Hello 724
Hello 725
Hello 726
Hello 727
Hello 728
Hello 729
Hello 730
Hello 731
Hello 732
Hello 733
Hello 734
Hello 735
Hello 736
Hello 737
Hello 738
Hello 739
Hello 740
Hello 741
Hello 742
Hello 743
Hello 744
Hello 745
Hello 746
Hello 747
Hello 748
Hello 749
Hello 750
Hello 751
Hello 752
Hello 753
Hello 754
Hello 755
Hello 756
Hello 757
Hello 758
Hello 759
Hello 760
Hello 761
Hello 762
Hello 763

  7%|▋         | 849/12000 [00:01<00:25, 442.91it/s]

Hello 764
Hello 765
Hello 766
Hello 767
Hello 768
Hello 769
Hello 770
Hello 771
Hello 772
Hello 773
Hello 774
Hello 775
Hello 776
Hello 777
Hello 778
Hello 779
Hello 780
Hello 781
Hello 782
Hello 783
Hello 784
Hello 785
Hello 786
Hello 787
Hello 788
Hello 789
Hello 790
Hello 791
Hello 792
Hello 793
Hello 794
Hello 795
Hello 796
Hello 797
Hello 798
Hello 799
Hello 800
Hello 801
Hello 802
Hello 803
Hello 804
Hello 805
Hello 806
Hello 807
Hello 808
Hello 809
Hello 810
Hello 811
Hello 812
Hello 813
Hello 814
Hello 815
Hello 816
Hello 817
Hello 818
Hello 819
Hello 820
Hello 821
Hello 822
Hello 823
Hello 824
Hello 825
Hello 826
Hello 827
Hello 828
Hello 829
Hello 830
Hello 831
Hello 832
Hello 833
Hello 834
Hello 835
Hello 836
Hello 837
Hello 838
Hello 839
Hello 840
Hello 841
Hello 842
Hello 843
Hello 844
Hello 845
Hello 846
Hello 847
Hello 848
Hello 849
Hello 850
Hello 851
Hello 852
Hello 853
Hello 854
Hello 855
Hello 856
Hello 857
Hello 858
Hello 859

  7%|▋         | 895/12000 [00:01<00:26, 426.39it/s]

Hello 860
Hello 861
Hello 862
Hello 863
Hello 864
Hello 865
Hello 866
Hello 867
Hello 868
Hello 869
Hello 870
Hello 871
Hello 872
Hello 873
Hello 874
Hello 875
Hello 876
Hello 877
Hello 878
Hello 879
Hello 880
Hello 881
Hello 882
Hello 883
Hello 884
Hello 885
Hello 886
Hello 887
Hello 888
Hello 889
Hello 890
Hello 891
Hello 892
Hello 893
Hello 894
Hello 895
Hello 896
Hello 897
Hello 898
Hello 899
Hello 900
Hello 901
Hello 902
Hello 903
Hello 904
Hello 905
Hello 906
Hello 907
Hello 908
Hello 909
Hello 910
Hello 911
Hello 912
Hello 913
Hello 914
Hello 915
Hello 916
Hello 917
Hello 918
Hello 919
Hello 920
Hello 921
Hello 922
Hello 923
Hello 924
Hello 925
Hello 926
Hello 927
Hello 928
Hello 929
Hello 930
Hello 931
Hello 932
Hello 933
Hello 934
Hello 935
Hello 936
Hello 937
Hello 938

  8%|▊         | 981/12000 [00:02<00:32, 341.55it/s]

Hello 939
Hello 940
Hello 941
Hello 942
Hello 943
Hello 944
Hello 945
Hello 946
Hello 947
Hello 948
Hello 949
Hello 950
Hello 951
Hello 952
Hello 953
Hello 954
Hello 955
Hello 956
Hello 957
Hello 958
Hello 959
Hello 960
Hello 961
Hello 962
Hello 963
Hello 964
Hello 965
Hello 966
Hello 967
Hello 968
Hello 969
Hello 970
Hello 971
Hello 972
Hello 973
Hello 974
Hello 975
Hello 976
Hello 977
Hello 978
Hello 979
Hello 980
Hello 981
Hello 982
Hello 983
Hello 984
Hello 985
Hello 986
Hello 987
Hello 988
Hello 989
Hello 990
Hello 991
Hello 992
Hello 993

  8%|▊         | 1018/12000 [00:02<00:32, 337.36it/s]

Hello 994
Hello 995
Hello 996
Hello 997
Hello 998
Hello 999
Hello 1000
Hello 1001
Hello 1002
Hello 1003
Hello 1004
Hello 1005
Hello 1006
Hello 1007
Hello 1008
Hello 1009
Hello 1010
Hello 1011
Hello 1012
Hello 1013
Hello 1014
Hello 1015
Hello 1016
Hello 1017
Hello 1018
Hello 1019
Hello 1020
Hello 1021
Hello 1022
Hello 1023
Hello 1024
Hello 1025
Hello 1026
Hello 1027
Hello 1028
Hello 1029
Hello 1030
Hello 1031
Hello 1032
Hello 1033
Hello 1034
Hello 1035
Hello 1036
Hello 1037
Hello 1038
Hello 1039
Hello 1040
Hello 1041
Hello 1042
Hello 1043
Hello 1044
Hello 1045
Hello 1046
Hello 1047
Hello 1048
Hello 1049
Hello 1050
Hello 1051
Hello 1052
Hello 1053
Hello 1054
Hello 1055
Hello 1056
Hello 1057
Hello 1058
Hello 1059
Hello 1060
Hello 1061
Hello 1062
Hello 1063
Hello 1064
Hello 1065

  9%|▉         | 1122/12000 [00:02<00:26, 413.57it/s]

Hello 1066
Hello 1067
Hello 1068
Hello 1069
Hello 1070
Hello 1071
Hello 1072
Hello 1073
Hello 1074
Hello 1075
Hello 1076
Hello 1077
Hello 1078
Hello 1079
Hello 1080
Hello 1081
Hello 1082
Hello 1083
Hello 1084
Hello 1085
Hello 1086
Hello 1087
Hello 1088
Hello 1089
Hello 1090
Hello 1091
Hello 1092
Hello 1093
Hello 1094
Hello 1095
Hello 1096
Hello 1097
Hello 1098
Hello 1099
Hello 1100
Hello 1101
Hello 1102
Hello 1103
Hello 1104
Hello 1105
Hello 1106
Hello 1107
Hello 1108
Hello 1109
Hello 1110
Hello 1111
Hello 1112
Hello 1113
Hello 1114
Hello 1115
Hello 1116
Hello 1117
Hello 1118
Hello 1119
Hello 1120
Hello 1121
Hello 1122
Hello 1123
Hello 1124
Hello 1125
Hello 1126
Hello 1127
Hello 1128
Hello 1129
Hello 1130
Hello 1131
Hello 1132
Hello 1133
Hello 1134
Hello 1135
Hello 1136
Hello 1137
Hello 1138
Hello 1139
Hello 1140
Hello 1141
Hello 1142
Hello 1143
Hello 1144
Hello 1145
Hello 1146
Hello 1147
Hello 1148
Hello 1149
Hello 1150
Hello 1151
Hello 1152
Hello 1153
Hello 1154
Hello 1155
Hello 1156
Hello 1157
Hello 1158
Hello 1159
Hello 1160
Hello 1161
Hello 1162
Hello 1163
Hello 1164
Hello 1165
Hello 1166
Hello 1167
Hello 1168
Hello 1169
Hello 1170
Hello 1171
Hello 1172
Hello 1173
Hello 1174
Hello 1175
Hello 1176
Hello 1177

 10%|█         | 1225/12000 [00:02<00:24, 433.07it/s]

Hello 1178
Hello 1179
Hello 1180
Hello 1181
Hello 1182
Hello 1183
Hello 1184
Hello 1185
Hello 1186
Hello 1187
Hello 1188
Hello 1189
Hello 1190
Hello 1191
Hello 1192
Hello 1193
Hello 1194
Hello 1195
Hello 1196
Hello 1197
Hello 1198
Hello 1199
Hello 1200
Hello 1201
Hello 1202
Hello 1203
Hello 1204
Hello 1205
Hello 1206
Hello 1207
Hello 1208
Hello 1209
Hello 1210
Hello 1211
Hello 1212
Hello 1213
Hello 1214
Hello 1215
Hello 1216
Hello 1217
Hello 1218
Hello 1219
Hello 1220
Hello 1221
Hello 1222
Hello 1223
Hello 1224
Hello 1225
Hello 1226
Hello 1227
Hello 1228
Hello 1229
Hello 1230
Hello 1231
Hello 1232
Hello 1233
Hello 1234
Hello 1235
Hello 1236
Hello 1237
Hello 1238
Hello 1239
Hello 1240
Hello 1241
Hello 1242
Hello 1243
Hello 1244
Hello 1245
Hello 1246
Hello 1247
Hello 1248
Hello 1249
Hello 1250
Hello 1251
Hello 1252
Hello 1253
Hello 1254
Hello 1255
Hello 1256
Hello 1257
Hello 1258
Hello 1259
Hello 1260
Hello 1261
Hello 1262
Hello 1263
Hello 1264
Hello 1265
Hello 1266
Hello 1267
Hello 1268
Hello 1269
Hello 1270
Hello 1271
Hello 1272

 11%|█         | 1334/12000 [00:03<00:22, 468.93it/s]

Hello 1273
Hello 1274
Hello 1275
Hello 1276
Hello 1277
Hello 1278
Hello 1279
Hello 1280
Hello 1281
Hello 1282
Hello 1283
Hello 1284
Hello 1285
Hello 1286
Hello 1287
Hello 1288
Hello 1289
Hello 1290
Hello 1291
Hello 1292
Hello 1293
Hello 1294
Hello 1295
Hello 1296
Hello 1297
Hello 1298
Hello 1299
Hello 1300
Hello 1301
Hello 1302
Hello 1303
Hello 1304
Hello 1305
Hello 1306
Hello 1307
Hello 1308
Hello 1309
Hello 1310
Hello 1311
Hello 1312
Hello 1313
Hello 1314
Hello 1315
Hello 1316
Hello 1317
Hello 1318
Hello 1319
Hello 1320
Hello 1321
Hello 1322
Hello 1323
Hello 1324
Hello 1325
Hello 1326
Hello 1327
Hello 1328
Hello 1329
Hello 1330
Hello 1331
Hello 1332
Hello 1333
Hello 1334
Hello 1335
Hello 1336
Hello 1337
Hello 1338
Hello 1339
Hello 1340
Hello 1341
Hello 1342
Hello 1343
Hello 1344
Hello 1345
Hello 1346
Hello 1347
Hello 1348
Hello 1349
Hello 1350
Hello 1351
Hello 1352
Hello 1353
Hello 1354
Hello 1355
Hello 1356
Hello 1357
Hello 1358
Hello 1359
Hello 1360
Hello 1361
Hello 1362
Hello 1363
Hello 1364
Hello 1365
Hello 1366
Hello 1367
Hello 1368
Hello 1369
Hello 1370
Hello 1371
Hello 1372
Hello 1373
Hello 1374
Hello 1375
Hello 1376
Hello 1377
Hello 1378
Hello 1379
Hello 1380
Hello 1381
Hello 1382

 12%|█▏        | 1460/12000 [00:03<00:19, 535.08it/s]

Hello 1383
Hello 1384
Hello 1385
Hello 1386
Hello 1387
Hello 1388
Hello 1389
Hello 1390
Hello 1391
Hello 1392
Hello 1393
Hello 1394
Hello 1395
Hello 1396
Hello 1397
Hello 1398
Hello 1399
Hello 1400
Hello 1401
Hello 1402
Hello 1403
Hello 1404
Hello 1405
Hello 1406
Hello 1407
Hello 1408
Hello 1409
Hello 1410
Hello 1411
Hello 1412
Hello 1413
Hello 1414
Hello 1415
Hello 1416
Hello 1417
Hello 1418
Hello 1419
Hello 1420
Hello 1421
Hello 1422
Hello 1423
Hello 1424
Hello 1425
Hello 1426
Hello 1427
Hello 1428
Hello 1429
Hello 1430
Hello 1431
Hello 1432
Hello 1433
Hello 1434
Hello 1435
Hello 1436
Hello 1437
Hello 1438
Hello 1439
Hello 1440
Hello 1441
Hello 1442
Hello 1443
Hello 1444
Hello 1445
Hello 1446
Hello 1447
Hello 1448
Hello 1449
Hello 1450
Hello 1451
Hello 1452
Hello 1453
Hello 1454
Hello 1455
Hello 1456
Hello 1457
Hello 1458
Hello 1459
Hello 1460
Hello 1461
Hello 1462
Hello 1463
Hello 1464
Hello 1465
Hello 1466
Hello 1467
Hello 1468
Hello 1469
Hello 1470
Hello 1471
Hello 1472
Hello 1473
Hello 1474
Hello 1475
Hello 1476
Hello 1477
Hello 1478
Hello 1479
Hello 1480
Hello 1481
Hello 1482
Hello 1483
Hello 1484
Hello 1485
Hello 1486
Hello 1487
Hello 1488
Hello 1489
Hello 1490
Hello 1491
Hello 1492
Hello 1493
Hello 1494
Hello 1495
Hello 1496
Hello 1497
Hello 1498
Hello 1499
Hello 1500
Hello 1501
Hello 1502
Hello 1503
Hello 1504
Hello 1505
Hello 1506
Hello 1507
Hello 1508
Hello 1509
Hello 1510
Hello 1511
Hello 1512

 13%|█▎        | 1572/12000 [00:03<00:20, 499.67it/s]

Hello 1513
Hello 1514
Hello 1515
Hello 1516
Hello 1517
Hello 1518
Hello 1519
Hello 1520
Hello 1521
Hello 1522
Hello 1523
Hello 1524
Hello 1525
Hello 1526
Hello 1527
Hello 1528
Hello 1529
Hello 1530
Hello 1531
Hello 1532
Hello 1533
Hello 1534
Hello 1535
Hello 1536
Hello 1537
Hello 1538
Hello 1539
Hello 1540
Hello 1541
Hello 1542
Hello 1543
Hello 1544
Hello 1545
Hello 1546
Hello 1547
Hello 1548
Hello 1549
Hello 1550
Hello 1551
Hello 1552
Hello 1553
Hello 1554
Hello 1555
Hello 1556
Hello 1557
Hello 1558
Hello 1559
Hello 1560
Hello 1561
Hello 1562
Hello 1563
Hello 1564
Hello 1565
Hello 1566
Hello 1567
Hello 1568
Hello 1569
Hello 1570
Hello 1571
Hello 1572
Hello 1573
Hello 1574
Hello 1575
Hello 1576
Hello 1577
Hello 1578
Hello 1579
Hello 1580
Hello 1581
Hello 1582
Hello 1583
Hello 1584
Hello 1585
Hello 1586
Hello 1587
Hello 1588
Hello 1589
Hello 1590
Hello 1591
Hello 1592
Hello 1593
Hello 1594
Hello 1595
Hello 1596
Hello 1597
Hello 1598
Hello 1599
Hello 1600
Hello 1601
Hello 1602
Hello 1603
Hello 1604
Hello 1605
Hello 1606
Hello 1607
Hello 1608
Hello 1609
Hello 1610
Hello 1611
Hello 1612
Hello 1613
Hello 1614
Hello 1615
Hello 1616
Hello 1617
Hello 1618
Hello 1619
Hello 1620
Hello 1621
Hello 1622
Hello 1623
Hello 1624

 14%|█▍        | 1686/12000 [00:03<00:23, 439.86it/s]

Hello 1625
Hello 1626
Hello 1627
Hello 1628
Hello 1629
Hello 1630
Hello 1631
Hello 1632
Hello 1633
Hello 1634
Hello 1635
Hello 1636
Hello 1637
Hello 1638
Hello 1639
Hello 1640
Hello 1641
Hello 1642
Hello 1643
Hello 1644
Hello 1645
Hello 1646
Hello 1647
Hello 1648
Hello 1649
Hello 1650
Hello 1651
Hello 1652
Hello 1653
Hello 1654
Hello 1655
Hello 1656
Hello 1657
Hello 1658
Hello 1659
Hello 1660
Hello 1661
Hello 1662
Hello 1663
Hello 1664
Hello 1665
Hello 1666
Hello 1667
Hello 1668
Hello 1669
Hello 1670
Hello 1671
Hello 1672
Hello 1673
Hello 1674
Hello 1675
Hello 1676
Hello 1677
Hello 1678
Hello 1679
Hello 1680
Hello 1681
Hello 1682
Hello 1683
Hello 1684
Hello 1685

 14%|█▍        | 1733/12000 [00:03<00:23, 441.45it/s]

Hello 1686
Hello 1687
Hello 1688
Hello 1689
Hello 1690
Hello 1691
Hello 1692
Hello 1693
Hello 1694
Hello 1695
Hello 1696
Hello 1697
Hello 1698
Hello 1699
Hello 1700
Hello 1701
Hello 1702
Hello 1703
Hello 1704
Hello 1705
Hello 1706
Hello 1707
Hello 1708
Hello 1709
Hello 1710
Hello 1711
Hello 1712
Hello 1713
Hello 1714
Hello 1715
Hello 1716
Hello 1717
Hello 1718
Hello 1719
Hello 1720
Hello 1721
Hello 1722
Hello 1723
Hello 1724
Hello 1725
Hello 1726
Hello 1727
Hello 1728
Hello 1729
Hello 1730
Hello 1731
Hello 1732
Hello 1733
Hello 1734
Hello 1735
Hello 1736
Hello 1737
Hello 1738
Hello 1739
Hello 1740
Hello 1741
Hello 1742
Hello 1743
Hello 1744
Hello 1745
Hello 1746
Hello 1747
Hello 1748
Hello 1749
Hello 1750
Hello 1751
Hello 1752
Hello 1753
Hello 1754
Hello 1755
Hello 1756
Hello 1757
Hello 1758
Hello 1759
Hello 1760
Hello 1761

 15%|█▌        | 1822/12000 [00:04<00:26, 390.11it/s]

Hello 1762
Hello 1763
Hello 1764
Hello 1765
Hello 1766
Hello 1767
Hello 1768
Hello 1769
Hello 1770
Hello 1771
Hello 1772
Hello 1773
Hello 1774
Hello 1775
Hello 1776
Hello 1777
Hello 1778
Hello 1779
Hello 1780
Hello 1781
Hello 1782
Hello 1783
Hello 1784
Hello 1785
Hello 1786
Hello 1787
Hello 1788
Hello 1789
Hello 1790
Hello 1791
Hello 1792
Hello 1793
Hello 1794
Hello 1795
Hello 1796
Hello 1797
Hello 1798
Hello 1799
Hello 1800
Hello 1801
Hello 1802
Hello 1803
Hello 1804
Hello 1805
Hello 1806
Hello 1807
Hello 1808
Hello 1809
Hello 1810
Hello 1811
Hello 1812
Hello 1813
Hello 1814
Hello 1815
Hello 1816
Hello 1817
Hello 1818
Hello 1819
Hello 1820
Hello 1821
Hello 1822
Hello 1823
Hello 1824
Hello 1825
Hello 1826
Hello 1827
Hello 1828
Hello 1829
Hello 1830
Hello 1831

 16%|█▌        | 1917/12000 [00:04<00:25, 394.78it/s]

Hello 1832
Hello 1833
Hello 1834
Hello 1835
Hello 1836
Hello 1837
Hello 1838
Hello 1839
Hello 1840
Hello 1841
Hello 1842
Hello 1843
Hello 1844
Hello 1845
Hello 1846
Hello 1847
Hello 1848
Hello 1849
Hello 1850
Hello 1851
Hello 1852
Hello 1853
Hello 1854
Hello 1855
Hello 1856
Hello 1857
Hello 1858
Hello 1859
Hello 1860
Hello 1861
Hello 1862
Hello 1863
Hello 1864
Hello 1865
Hello 1866
Hello 1867
Hello 1868
Hello 1869
Hello 1870
Hello 1871
Hello 1872
Hello 1873
Hello 1874
Hello 1875
Hello 1876
Hello 1877
Hello 1878
Hello 1879
Hello 1880
Hello 1881
Hello 1882
Hello 1883
Hello 1884
Hello 1885
Hello 1886
Hello 1887
Hello 1888
Hello 1889
Hello 1890
Hello 1891
Hello 1892
Hello 1893
Hello 1894
Hello 1895
Hello 1896
Hello 1897
Hello 1898
Hello 1899
Hello 1900
Hello 1901
Hello 1902
Hello 1903
Hello 1904
Hello 1905
Hello 1906
Hello 1907
Hello 1908
Hello 1909
Hello 1910
Hello 1911
Hello 1912
Hello 1913
Hello 1914
Hello 1915
Hello 1916
Hello 1917
Hello 1918
Hello 1919
Hello 1920
Hello 1921
Hello 1922
Hello 1923
Hello 1924
Hello 1925
Hello 1926
Hello 1927
Hello 1928
Hello 1929
Hello 1930
Hello 1931
Hello 1932
Hello 1933
Hello 1934
Hello 1935
Hello 1936
Hello 1937
Hello 1938
Hello 1939
Hello 1940
Hello 1941
Hello 1942
Hello 1943
Hello 1944
Hello 1945
Hello 1946
Hello 1947
Hello 1948
Hello 1949
Hello 1950
Hello 1951
Hello 1952
Hello 1953
Hello 1954
Hello 1955
Hello 1956

 17%|█▋        | 2002/12000 [00:04<00:30, 331.01it/s]

Hello 1957
Hello 1958
Hello 1959
Hello 1960
Hello 1961
Hello 1962
Hello 1963
Hello 1964
Hello 1965
Hello 1966
Hello 1967
Hello 1968
Hello 1969
Hello 1970
Hello 1971
Hello 1972
Hello 1973
Hello 1974
Hello 1975
Hello 1976
Hello 1977
Hello 1978
Hello 1979
Hello 1980
Hello 1981
Hello 1982
Hello 1983
Hello 1984
Hello 1985
Hello 1986
Hello 1987
Hello 1988
Hello 1989
Hello 1990
Hello 1991
Hello 1992
Hello 1993
Hello 1994
Hello 1995
Hello 1996
Hello 1997
Hello 1998
Hello 1999
Hello 2000
Hello 2001
Hello 2002
Hello 2003
Hello 2004
Hello 2005
Hello 2006
Hello 2007
Hello 2008
Hello 2009
Hello 2010
Hello 2011
Hello 2012
Hello 2013
Hello 2014
Hello 2015
Hello 2016
Hello 2017
Hello 2018
Hello 2019
Hello 2020
Hello 2021
Hello 2022
Hello 2023
Hello 2024
Hello 2025
Hello 2026
Hello 2027
Hello 2028
Hello 2029
Hello 2030
Hello 2031
Hello 2032
Hello 2033
Hello 2034
Hello 2035
Hello 2036
Hello 2037
Hello 2038
Hello 2039
Hello 2040

 18%|█▊        | 2140/12000 [00:05<00:23, 417.60it/s]

Hello 2041
Hello 2042
Hello 2043
Hello 2044
Hello 2045
Hello 2046
Hello 2047
Hello 2048
Hello 2049
Hello 2050
Hello 2051
Hello 2052
Hello 2053
Hello 2054
Hello 2055
Hello 2056
Hello 2057
Hello 2058
Hello 2059
Hello 2060
Hello 2061
Hello 2062
Hello 2063
Hello 2064
Hello 2065
Hello 2066
Hello 2067
Hello 2068
Hello 2069
Hello 2070
Hello 2071
Hello 2072
Hello 2073
Hello 2074
Hello 2075
Hello 2076
Hello 2077
Hello 2078
Hello 2079
Hello 2080
Hello 2081
Hello 2082
Hello 2083
Hello 2084
Hello 2085
Hello 2086
Hello 2087
Hello 2088
Hello 2089
Hello 2090
Hello 2091
Hello 2092
Hello 2093
Hello 2094
Hello 2095
Hello 2096
Hello 2097
Hello 2098
Hello 2099
Hello 2100
Hello 2101
Hello 2102
Hello 2103
Hello 2104
Hello 2105
Hello 2106
Hello 2107
Hello 2108
Hello 2109
Hello 2110
Hello 2111
Hello 2112
Hello 2113
Hello 2114
Hello 2115
Hello 2116
Hello 2117
Hello 2118
Hello 2119
Hello 2120
Hello 2121
Hello 2122
Hello 2123
Hello 2124
Hello 2125
Hello 2126
Hello 2127
Hello 2128
Hello 2129
Hello 2130
Hello 2131
Hello 2132
Hello 2133
Hello 2134
Hello 2135
Hello 2136
Hello 2137
Hello 2138
Hello 2139

 19%|█▉        | 2256/12000 [00:05<00:20, 478.03it/s]

Hello 2140
Hello 2141
Hello 2142
Hello 2143
Hello 2144
Hello 2145
Hello 2146
Hello 2147
Hello 2148
Hello 2149
Hello 2150
Hello 2151
Hello 2152
Hello 2153
Hello 2154
Hello 2155
Hello 2156
Hello 2157
Hello 2158
Hello 2159
Hello 2160
Hello 2161
Hello 2162
Hello 2163
Hello 2164
Hello 2165
Hello 2166
Hello 2167
Hello 2168
Hello 2169
Hello 2170
Hello 2171
Hello 2172
Hello 2173
Hello 2174
Hello 2175
Hello 2176
Hello 2177
Hello 2178
Hello 2179
Hello 2180
Hello 2181
Hello 2182
Hello 2183
Hello 2184
Hello 2185
Hello 2186
Hello 2187
Hello 2188
Hello 2189
Hello 2190
Hello 2191
Hello 2192
Hello 2193
Hello 2194
Hello 2195
Hello 2196
Hello 2197
Hello 2198
Hello 2199
Hello 2200
Hello 2201
Hello 2202
Hello 2203
Hello 2204
Hello 2205
Hello 2206
Hello 2207
Hello 2208
Hello 2209
Hello 2210
Hello 2211
Hello 2212
Hello 2213
Hello 2214
Hello 2215
Hello 2216
Hello 2217
Hello 2218
Hello 2219
Hello 2220
Hello 2221
Hello 2222
Hello 2223
Hello 2224
Hello 2225
Hello 2226
Hello 2227
Hello 2228
Hello 2229
Hello 2230
Hello 2231
Hello 2232
Hello 2233
Hello 2234
Hello 2235
Hello 2236
Hello 2237
Hello 2238
Hello 2239
Hello 2240
Hello 2241
Hello 2242
Hello 2243
Hello 2244
Hello 2245
Hello 2246
Hello 2247
Hello 2248
Hello 2249
Hello 2250
Hello 2251
Hello 2252
Hello 2253
Hello 2254
Hello 2255

 19%|█▉        | 2306/12000 [00:05<00:20, 474.19it/s]

Hello 2256
Hello 2257
Hello 2258
Hello 2259
Hello 2260
Hello 2261
Hello 2262
Hello 2263
Hello 2264
Hello 2265
Hello 2266
Hello 2267
Hello 2268
Hello 2269
Hello 2270
Hello 2271
Hello 2272
Hello 2273
Hello 2274
Hello 2275
Hello 2276
Hello 2277
Hello 2278
Hello 2279
Hello 2280
Hello 2281
Hello 2282
Hello 2283
Hello 2284
Hello 2285
Hello 2286
Hello 2287
Hello 2288
Hello 2289
Hello 2290
Hello 2291
Hello 2292
Hello 2293
Hello 2294
Hello 2295
Hello 2296
Hello 2297
Hello 2298
Hello 2299
Hello 2300
Hello 2301
Hello 2302
Hello 2303
Hello 2304
Hello 2305
Hello 2306
Hello 2307
Hello 2308
Hello 2309
Hello 2310
Hello 2311
Hello 2312
Hello 2313
Hello 2314
Hello 2315
Hello 2316
Hello 2317
Hello 2318
Hello 2319
Hello 2320
Hello 2321
Hello 2322
Hello 2323
Hello 2324
Hello 2325
Hello 2326
Hello 2327
Hello 2328
Hello 2329
Hello 2330
Hello 2331
Hello 2332
Hello 2333
Hello 2334
Hello 2335
Hello 2336
Hello 2337
Hello 2338
Hello 2339
Hello 2340
Hello 2341
Hello 2342
Hello 2343
Hello 2344
Hello 2345
Hello 2346
Hello 2347

 20%|██        | 2404/12000 [00:05<00:20, 464.84it/s]

Hello 2348
Hello 2349
Hello 2350
Hello 2351
Hello 2352
Hello 2353
Hello 2354
Hello 2355
Hello 2356
Hello 2357
Hello 2358
Hello 2359
Hello 2360
Hello 2361
Hello 2362
Hello 2363
Hello 2364
Hello 2365
Hello 2366
Hello 2367
Hello 2368
Hello 2369
Hello 2370
Hello 2371
Hello 2372
Hello 2373
Hello 2374
Hello 2375
Hello 2376
Hello 2377
Hello 2378
Hello 2379
Hello 2380
Hello 2381
Hello 2382
Hello 2383
Hello 2384
Hello 2385
Hello 2386
Hello 2387
Hello 2388
Hello 2389
Hello 2390
Hello 2391
Hello 2392
Hello 2393
Hello 2394
Hello 2395
Hello 2396
Hello 2397
Hello 2398
Hello 2399
Hello 2400
Hello 2401
Hello 2402
Hello 2403
Hello 2404
Hello 2405
Hello 2406
Hello 2407
Hello 2408
Hello 2409
Hello 2410
Hello 2411
Hello 2412
Hello 2413
Hello 2414
Hello 2415
Hello 2416
Hello 2417
Hello 2418
Hello 2419
Hello 2420
Hello 2421
Hello 2422
Hello 2423
Hello 2424
Hello 2425
Hello 2426
Hello 2427
Hello 2428
Hello 2429
Hello 2430
Hello 2431
Hello 2432
Hello 2433
Hello 2434
Hello 2435

 21%|██        | 2499/12000 [00:05<00:20, 459.67it/s]

Hello 2436
Hello 2437
Hello 2438
Hello 2439
Hello 2440
Hello 2441
Hello 2442
Hello 2443
Hello 2444
Hello 2445
Hello 2446
Hello 2447
Hello 2448
Hello 2449
Hello 2450
Hello 2451
Hello 2452
Hello 2453
Hello 2454
Hello 2455
Hello 2456
Hello 2457
Hello 2458
Hello 2459
Hello 2460
Hello 2461
Hello 2462
Hello 2463
Hello 2464
Hello 2465
Hello 2466
Hello 2467
Hello 2468
Hello 2469
Hello 2470
Hello 2471
Hello 2472
Hello 2473
Hello 2474
Hello 2475
Hello 2476
Hello 2477
Hello 2478
Hello 2479
Hello 2480
Hello 2481
Hello 2482
Hello 2483
Hello 2484
Hello 2485
Hello 2486
Hello 2487
Hello 2488
Hello 2489
Hello 2490
Hello 2491
Hello 2492
Hello 2493
Hello 2494
Hello 2495
Hello 2496
Hello 2497
Hello 2498
Hello 2499
Hello 2500
Hello 2501
Hello 2502
Hello 2503
Hello 2504
Hello 2505
Hello 2506
Hello 2507
Hello 2508
Hello 2509
Hello 2510
Hello 2511
Hello 2512
Hello 2513
Hello 2514
Hello 2515
Hello 2516
Hello 2517
Hello 2518
Hello 2519
Hello 2520
Hello 2521
Hello 2522
Hello 2523
Hello 2524
Hello 2525
Hello 2526
Hello 2527
Hello 2528
Hello 2529
Hello 2530
Hello 2531
Hello 2532
Hello 2533
Hello 2534
Hello 2535
Hello 2536
Hello 2537
Hello 2538
Hello 2539
Hello 2540
Hello 2541
Hello 2542
Hello 2543

 22%|██▏       | 2608/12000 [00:05<00:18, 500.63it/s]

Hello 2544
Hello 2545
Hello 2546
Hello 2547
Hello 2548
Hello 2549
Hello 2550
Hello 2551
Hello 2552
Hello 2553
Hello 2554
Hello 2555
Hello 2556
Hello 2557
Hello 2558
Hello 2559
Hello 2560
Hello 2561
Hello 2562
Hello 2563
Hello 2564
Hello 2565
Hello 2566
Hello 2567
Hello 2568
Hello 2569
Hello 2570
Hello 2571
Hello 2572
Hello 2573
Hello 2574
Hello 2575
Hello 2576
Hello 2577
Hello 2578
Hello 2579
Hello 2580
Hello 2581
Hello 2582
Hello 2583
Hello 2584
Hello 2585
Hello 2586
Hello 2587
Hello 2588
Hello 2589
Hello 2590
Hello 2591
Hello 2592
Hello 2593
Hello 2594
Hello 2595
Hello 2596
Hello 2597
Hello 2598
Hello 2599
Hello 2600
Hello 2601
Hello 2602
Hello 2603
Hello 2604
Hello 2605
Hello 2606
Hello 2607
Hello 2608
Hello 2609
Hello 2610
Hello 2611
Hello 2612
Hello 2613
Hello 2614
Hello 2615
Hello 2616
Hello 2617
Hello 2618
Hello 2619
Hello 2620
Hello 2621
Hello 2622
Hello 2623
Hello 2624
Hello 2625
Hello 2626
Hello 2627
Hello 2628
Hello 2629
Hello 2630
Hello 2631
Hello 2632
Hello 2633
Hello 2634
Hello 2635
Hello 2636
Hello 2637
Hello 2638
Hello 2639
Hello 2640
Hello 2641

 23%|██▎       | 2706/12000 [00:06<00:20, 449.39it/s]

Hello 2642
Hello 2643
Hello 2644
Hello 2645
Hello 2646
Hello 2647
Hello 2648
Hello 2649
Hello 2650
Hello 2651
Hello 2652
Hello 2653
Hello 2654
Hello 2655
Hello 2656
Hello 2657
Hello 2658
Hello 2659
Hello 2660
Hello 2661
Hello 2662
Hello 2663
Hello 2664
Hello 2665
Hello 2666
Hello 2667
Hello 2668
Hello 2669
Hello 2670
Hello 2671
Hello 2672
Hello 2673
Hello 2674
Hello 2675
Hello 2676
Hello 2677
Hello 2678
Hello 2679
Hello 2680
Hello 2681
Hello 2682
Hello 2683
Hello 2684
Hello 2685
Hello 2686
Hello 2687
Hello 2688
Hello 2689
Hello 2690
Hello 2691
Hello 2692
Hello 2693
Hello 2694
Hello 2695
Hello 2696
Hello 2697
Hello 2698
Hello 2699
Hello 2700
Hello 2701
Hello 2702
Hello 2703
Hello 2704
Hello 2705
Hello 2706
Hello 2707
Hello 2708
Hello 2709
Hello 2710
Hello 2711
Hello 2712
Hello 2713
Hello 2714
Hello 2715
Hello 2716
Hello 2717
Hello 2718
Hello 2719
Hello 2720
Hello 2721
Hello 2722
Hello 2723
Hello 2724
Hello 2725
Hello 2726
Hello 2727
Hello 2728
Hello 2729
Hello 2730
Hello 2731
Hello 2732
Hello 2733
Hello 2734
Hello 2735
Hello 2736
Hello 2737
Hello 2738
Hello 2739
Hello 2740
Hello 2741
Hello 2742
Hello 2743
Hello 2744
Hello 2745
Hello 2746
Hello 2747

 23%|██▎       | 2797/12000 [00:06<00:21, 434.16it/s]

Hello 2748
Hello 2749
Hello 2750
Hello 2751
Hello 2752
Hello 2753
Hello 2754
Hello 2755
Hello 2756
Hello 2757
Hello 2758
Hello 2759
Hello 2760
Hello 2761
Hello 2762
Hello 2763
Hello 2764
Hello 2765
Hello 2766
Hello 2767
Hello 2768
Hello 2769
Hello 2770
Hello 2771
Hello 2772
Hello 2773
Hello 2774
Hello 2775
Hello 2776
Hello 2777
Hello 2778
Hello 2779
Hello 2780
Hello 2781
Hello 2782
Hello 2783
Hello 2784
Hello 2785
Hello 2786
Hello 2787
Hello 2788
Hello 2789
Hello 2790
Hello 2791
Hello 2792
Hello 2793
Hello 2794
Hello 2795
Hello 2796
Hello 2797
Hello 2798
Hello 2799
Hello 2800
Hello 2801
Hello 2802
Hello 2803
Hello 2804
Hello 2805
Hello 2806
Hello 2807
Hello 2808
Hello 2809
Hello 2810
Hello 2811
Hello 2812
Hello 2813
Hello 2814
Hello 2815
Hello 2816
Hello 2817
Hello 2818
Hello 2819
Hello 2820
Hello 2821
Hello 2822

 24%|██▍       | 2888/12000 [00:06<00:22, 400.62it/s]

Hello 2823
Hello 2824
Hello 2825
Hello 2826
Hello 2827
Hello 2828
Hello 2829
Hello 2830
Hello 2831
Hello 2832
Hello 2833
Hello 2834
Hello 2835
Hello 2836
Hello 2837
Hello 2838
Hello 2839
Hello 2840
Hello 2841
Hello 2842
Hello 2843
Hello 2844
Hello 2845
Hello 2846
Hello 2847
Hello 2848
Hello 2849
Hello 2850
Hello 2851
Hello 2852
Hello 2853
Hello 2854
Hello 2855
Hello 2856
Hello 2857
Hello 2858
Hello 2859
Hello 2860
Hello 2861
Hello 2862
Hello 2863
Hello 2864
Hello 2865
Hello 2866
Hello 2867
Hello 2868
Hello 2869
Hello 2870
Hello 2871
Hello 2872
Hello 2873
Hello 2874
Hello 2875
Hello 2876
Hello 2877
Hello 2878
Hello 2879
Hello 2880
Hello 2881
Hello 2882
Hello 2883
Hello 2884
Hello 2885
Hello 2886
Hello 2887
Hello 2888
Hello 2889
Hello 2890
Hello 2891
Hello 2892
Hello 2893
Hello 2894
Hello 2895
Hello 2896
Hello 2897
Hello 2898
Hello 2899
Hello 2900
Hello 2901
Hello 2902
Hello 2903
Hello 2904
Hello 2905
Hello 2906
Hello 2907
Hello 2908
Hello 2909
Hello 2910
Hello 2911
Hello 2912
Hello 2913
Hello 2914
Hello 2915
Hello 2916
Hello 2917
Hello 2918
Hello 2919
Hello 2920
Hello 2921
Hello 2922
Hello 2923
Hello 2924
Hello 2925
Hello 2926
Hello 2927

 25%|██▌       | 3007/12000 [00:06<00:18, 483.56it/s]

Hello 2928
Hello 2929
Hello 2930
Hello 2931
Hello 2932
Hello 2933
Hello 2934
Hello 2935
Hello 2936
Hello 2937
Hello 2938
Hello 2939
Hello 2940
Hello 2941
Hello 2942
Hello 2943
Hello 2944
Hello 2945
Hello 2946
Hello 2947
Hello 2948
Hello 2949
Hello 2950
Hello 2951
Hello 2952
Hello 2953
Hello 2954
Hello 2955
Hello 2956
Hello 2957
Hello 2958
Hello 2959
Hello 2960
Hello 2961
Hello 2962
Hello 2963
Hello 2964
Hello 2965
Hello 2966
Hello 2967
Hello 2968
Hello 2969
Hello 2970
Hello 2971
Hello 2972
Hello 2973
Hello 2974
Hello 2975
Hello 2976
Hello 2977
Hello 2978
Hello 2979
Hello 2980
Hello 2981
Hello 2982
Hello 2983
Hello 2984
Hello 2985
Hello 2986
Hello 2987
Hello 2988
Hello 2989
Hello 2990
Hello 2991
Hello 2992
Hello 2993
Hello 2994
Hello 2995
Hello 2996
Hello 2997
Hello 2998
Hello 2999
Hello 3000
Hello 3001
Hello 3002
Hello 3003
Hello 3004
Hello 3005
Hello 3006
Hello 3007
Hello 3008
Hello 3009
Hello 3010
Hello 3011
Hello 3012
Hello 3013
Hello 3014
Hello 3015
Hello 3016
Hello 3017
Hello 3018
Hello 3019
Hello 3020
Hello 3021
Hello 3022
Hello 3023
Hello 3024
Hello 3025
Hello 3026
Hello 3027
Hello 3028
Hello 3029
Hello 3030
Hello 3031
Hello 3032
Hello 3033
Hello 3034
Hello 3035
Hello 3036
Hello 3037
Hello 3038
Hello 3039
Hello 3040
Hello 3041
Hello 3042
Hello 3043
Hello 3044
Hello 3045
Hello 3046
Hello 3047
Hello 3048
Hello 3049
Hello 3050
Hello 3051
Hello 3052
Hello 3053
Hello 3054
Hello 3055
Hello 3056
Hello 3057
Hello 3058

 26%|██▌       | 3122/12000 [00:07<00:18, 481.87it/s]

Hello 3059
Hello 3060
Hello 3061
Hello 3062
Hello 3063
Hello 3064
Hello 3065
Hello 3066
Hello 3067
Hello 3068
Hello 3069
Hello 3070
Hello 3071
Hello 3072
Hello 3073
Hello 3074
Hello 3075
Hello 3076
Hello 3077
Hello 3078
Hello 3079
Hello 3080
Hello 3081
Hello 3082
Hello 3083
Hello 3084
Hello 3085
Hello 3086
Hello 3087
Hello 3088
Hello 3089
Hello 3090
Hello 3091
Hello 3092
Hello 3093
Hello 3094
Hello 3095
Hello 3096
Hello 3097
Hello 3098
Hello 3099
Hello 3100
Hello 3101
Hello 3102
Hello 3103
Hello 3104
Hello 3105
Hello 3106
Hello 3107
Hello 3108
Hello 3109
Hello 3110
Hello 3111
Hello 3112
Hello 3113
Hello 3114
Hello 3115
Hello 3116
Hello 3117
Hello 3118
Hello 3119
Hello 3120
Hello 3121
Hello 3122
Hello 3123
Hello 3124
Hello 3125
Hello 3126
Hello 3127
Hello 3128
Hello 3129
Hello 3130
Hello 3131
Hello 3132
Hello 3133
Hello 3134
Hello 3135
Hello 3136
Hello 3137
Hello 3138
Hello 3139
Hello 3140
Hello 3141
Hello 3142
Hello 3143

 27%|██▋       | 3216/12000 [00:07<00:21, 417.47it/s]

Hello 3144
Hello 3145
Hello 3146
Hello 3147
Hello 3148
Hello 3149
Hello 3150
Hello 3151
Hello 3152
Hello 3153
Hello 3154
Hello 3155
Hello 3156
Hello 3157
Hello 3158
Hello 3159
Hello 3160
Hello 3161
Hello 3162
Hello 3163
Hello 3164
Hello 3165
Hello 3166
Hello 3167
Hello 3168
Hello 3169
Hello 3170
Hello 3171
Hello 3172
Hello 3173
Hello 3174
Hello 3175
Hello 3176
Hello 3177
Hello 3178
Hello 3179
Hello 3180
Hello 3181
Hello 3182
Hello 3183
Hello 3184
Hello 3185
Hello 3186
Hello 3187
Hello 3188
Hello 3189
Hello 3190
Hello 3191
Hello 3192
Hello 3193
Hello 3194
Hello 3195
Hello 3196
Hello 3197
Hello 3198
Hello 3199
Hello 3200
Hello 3201
Hello 3202
Hello 3203
Hello 3204
Hello 3205
Hello 3206
Hello 3207
Hello 3208
Hello 3209
Hello 3210
Hello 3211
Hello 3212
Hello 3213
Hello 3214
Hello 3215
Hello 3216
Hello 3217
Hello 3218
Hello 3219
Hello 3220
Hello 3221
Hello 3222
Hello 3223
Hello 3224
Hello 3225
Hello 3226
Hello 3227
Hello 3228

 28%|██▊       | 3303/12000 [00:07<00:21, 407.53it/s]

Hello 3229
Hello 3230
Hello 3231
Hello 3232
Hello 3233
Hello 3234
Hello 3235
Hello 3236
Hello 3237
Hello 3238
Hello 3239
Hello 3240
Hello 3241
Hello 3242
Hello 3243
Hello 3244
Hello 3245
Hello 3246
Hello 3247
Hello 3248
Hello 3249
Hello 3250
Hello 3251
Hello 3252
Hello 3253
Hello 3254
Hello 3255
Hello 3256
Hello 3257
Hello 3258
Hello 3259
Hello 3260
Hello 3261
Hello 3262
Hello 3263
Hello 3264
Hello 3265
Hello 3266
Hello 3267
Hello 3268
Hello 3269
Hello 3270
Hello 3271
Hello 3272
Hello 3273
Hello 3274
Hello 3275
Hello 3276
Hello 3277
Hello 3278
Hello 3279
Hello 3280
Hello 3281
Hello 3282
Hello 3283
Hello 3284
Hello 3285
Hello 3286
Hello 3287
Hello 3288
Hello 3289
Hello 3290
Hello 3291
Hello 3292
Hello 3293
Hello 3294
Hello 3295
Hello 3296
Hello 3297
Hello 3298
Hello 3299
Hello 3300
Hello 3301
Hello 3302
Hello 3303
Hello 3304
Hello 3305
Hello 3306
Hello 3307
Hello 3308
Hello 3309
Hello 3310
Hello 3311
Hello 3312
Hello 3313
Hello 3314
Hello 3315
Hello 3316
Hello 3317
Hello 3318
Hello 3319
Hello 3320
Hello 3321
Hello 3322
Hello 3323
Hello 3324
Hello 3325
Hello 3326
Hello 3327
Hello 3328
Hello 3329
Hello 3330
Hello 3331
Hello 3332

 28%|██▊       | 3355/12000 [00:07<00:20, 426.91it/s]

Hello 3333
Hello 3334
Hello 3335
Hello 3336
Hello 3337
Hello 3338
Hello 3339
Hello 3340
Hello 3341
Hello 3342
Hello 3343
Hello 3344
Hello 3345
Hello 3346
Hello 3347
Hello 3348
Hello 3349
Hello 3350
Hello 3351
Hello 3352
Hello 3353
Hello 3354
Hello 3355
Hello 3356
Hello 3357
Hello 3358
Hello 3359
Hello 3360
Hello 3361
Hello 3362
Hello 3363
Hello 3364
Hello 3365
Hello 3366
Hello 3367
Hello 3368
Hello 3369
Hello 3370
Hello 3371
Hello 3372
Hello 3373
Hello 3374
Hello 3375
Hello 3376
Hello 3377
Hello 3378
Hello 3379
Hello 3380
Hello 3381
Hello 3382
Hello 3383
Hello 3384
Hello 3385
Hello 3386
Hello 3387
Hello 3388
Hello 3389
Hello 3390
Hello 3391
Hello 3392
Hello 3393
Hello 3394
Hello 3395
Hello 3396
Hello 3397
Hello 3398

 29%|██▊       | 3441/12000 [00:07<00:22, 384.20it/s]

Hello 3399
Hello 3400
Hello 3401
Hello 3402
Hello 3403
Hello 3404
Hello 3405
Hello 3406
Hello 3407
Hello 3408
Hello 3409
Hello 3410
Hello 3411
Hello 3412
Hello 3413
Hello 3414
Hello 3415
Hello 3416
Hello 3417
Hello 3418
Hello 3419
Hello 3420
Hello 3421
Hello 3422
Hello 3423
Hello 3424
Hello 3425
Hello 3426
Hello 3427
Hello 3428
Hello 3429
Hello 3430
Hello 3431
Hello 3432
Hello 3433
Hello 3434
Hello 3435
Hello 3436
Hello 3437
Hello 3438
Hello 3439
Hello 3440
Hello 3441
Hello 3442
Hello 3443
Hello 3444
Hello 3445
Hello 3446
Hello 3447
Hello 3448
Hello 3449
Hello 3450
Hello 3451
Hello 3452
Hello 3453
Hello 3454
Hello 3455
Hello 3456
Hello 3457
Hello 3458
Hello 3459
Hello 3460
Hello 3461
Hello 3462
Hello 3463
Hello 3464
Hello 3465
Hello 3466
Hello 3467
Hello 3468
Hello 3469
Hello 3470
Hello 3471
Hello 3472
Hello 3473
Hello 3474
Hello 3475
Hello 3476
Hello 3477
Hello 3478
Hello 3479
Hello 3480
Hello 3481
Hello 3482
Hello 3483
Hello 3484
Hello 3485
Hello 3486
Hello 3487
Hello 3488
Hello 3489
Hello 3490
Hello 3491
Hello 3492

 30%|██▉       | 3547/12000 [00:08<00:18, 445.18it/s]

Hello 3493
Hello 3494
Hello 3495
Hello 3496
Hello 3497
Hello 3498
Hello 3499
Hello 3500
Hello 3501
Hello 3502
Hello 3503
Hello 3504
Hello 3505
Hello 3506
Hello 3507
Hello 3508
Hello 3509
Hello 3510
Hello 3511
Hello 3512
Hello 3513
Hello 3514
Hello 3515
Hello 3516
Hello 3517
Hello 3518
Hello 3519
Hello 3520
Hello 3521
Hello 3522
Hello 3523
Hello 3524
Hello 3525
Hello 3526
Hello 3527
Hello 3528
Hello 3529
Hello 3530
Hello 3531
Hello 3532
Hello 3533
Hello 3534
Hello 3535
Hello 3536
Hello 3537
Hello 3538
Hello 3539
Hello 3540
Hello 3541
Hello 3542
Hello 3543
Hello 3544
Hello 3545
Hello 3546
Hello 3547
Hello 3548
Hello 3549
Hello 3550
Hello 3551
Hello 3552
Hello 3553
Hello 3554
Hello 3555
Hello 3556
Hello 3557
Hello 3558
Hello 3559
Hello 3560
Hello 3561
Hello 3562
Hello 3563
Hello 3564
Hello 3565
Hello 3566
Hello 3567
Hello 3568
Hello 3569
Hello 3570
Hello 3571
Hello 3572
Hello 3573
Hello 3574
Hello 3575
Hello 3576
Hello 3577
Hello 3578
Hello 3579
Hello 3580
Hello 3581
Hello 3582
Hello 3583
Hello 3584
Hello 3585
Hello 3586
Hello 3587
Hello 3588
Hello 3589
Hello 3590
Hello 3591
Hello 3592
Hello 3593
Hello 3594
Hello 3595
Hello 3596
Hello 3597
Hello 3598
Hello 3599
Hello 3600
Hello 3601
Hello 3602
Hello 3603
Hello 3604

 30%|███       | 3654/12000 [00:08<00:18, 442.11it/s]

Hello 3605
Hello 3606
Hello 3607
Hello 3608
Hello 3609
Hello 3610
Hello 3611
Hello 3612
Hello 3613
Hello 3614
Hello 3615
Hello 3616
Hello 3617
Hello 3618
Hello 3619
Hello 3620
Hello 3621
Hello 3622
Hello 3623
Hello 3624
Hello 3625
Hello 3626
Hello 3627
Hello 3628
Hello 3629
Hello 3630
Hello 3631
Hello 3632
Hello 3633
Hello 3634
Hello 3635
Hello 3636
Hello 3637
Hello 3638
Hello 3639
Hello 3640
Hello 3641
Hello 3642
Hello 3643
Hello 3644
Hello 3645
Hello 3646
Hello 3647
Hello 3648
Hello 3649
Hello 3650
Hello 3651
Hello 3652
Hello 3653
Hello 3654
Hello 3655
Hello 3656
Hello 3657
Hello 3658
Hello 3659
Hello 3660
Hello 3661
Hello 3662
Hello 3663
Hello 3664
Hello 3665
Hello 3666
Hello 3667
Hello 3668
Hello 3669
Hello 3670
Hello 3671
Hello 3672
Hello 3673
Hello 3674
Hello 3675
Hello 3676
Hello 3677
Hello 3678
Hello 3679
Hello 3680
Hello 3681
Hello 3682
Hello 3683
Hello 3684
Hello 3685
Hello 3686
Hello 3687
Hello 3688
Hello 3689
Hello 3690
Hello 3691

 31%|███▏      | 3755/12000 [00:08<00:18, 451.06it/s]

Hello 3692
Hello 3693
Hello 3694
Hello 3695
Hello 3696
Hello 3697
Hello 3698
Hello 3699
Hello 3700
Hello 3701
Hello 3702
Hello 3703
Hello 3704
Hello 3705
Hello 3706
Hello 3707
Hello 3708
Hello 3709
Hello 3710
Hello 3711
Hello 3712
Hello 3713
Hello 3714
Hello 3715
Hello 3716
Hello 3717
Hello 3718
Hello 3719
Hello 3720
Hello 3721
Hello 3722
Hello 3723
Hello 3724
Hello 3725
Hello 3726
Hello 3727
Hello 3728
Hello 3729
Hello 3730
Hello 3731
Hello 3732
Hello 3733
Hello 3734
Hello 3735
Hello 3736
Hello 3737
Hello 3738
Hello 3739
Hello 3740
Hello 3741
Hello 3742
Hello 3743
Hello 3744
Hello 3745
Hello 3746
Hello 3747
Hello 3748
Hello 3749
Hello 3750
Hello 3751
Hello 3752
Hello 3753
Hello 3754
Hello 3755
Hello 3756
Hello 3757
Hello 3758
Hello 3759
Hello 3760
Hello 3761
Hello 3762
Hello 3763
Hello 3764
Hello 3765
Hello 3766
Hello 3767
Hello 3768
Hello 3769
Hello 3770
Hello 3771
Hello 3772
Hello 3773
Hello 3774
Hello 3775
Hello 3776
Hello 3777
Hello 3778
Hello 3779
Hello 3780
Hello 3781
Hello 3782
Hello 3783
Hello 3784
Hello 3785
Hello 3786
Hello 3787
Hello 3788
Hello 3789
Hello 3790
Hello 3791
Hello 3792
Hello 3793
Hello 3794
Hello 3795
Hello 3796
Hello 3797
Hello 3798
Hello 3799
Hello 3800
Hello 3801
Hello 3802
Hello 3803
Hello 3804

 32%|███▏      | 3866/12000 [00:08<00:18, 435.76it/s]

Hello 3805
Hello 3806
Hello 3807
Hello 3808
Hello 3809
Hello 3810
Hello 3811
Hello 3812
Hello 3813
Hello 3814
Hello 3815
Hello 3816
Hello 3817
Hello 3818
Hello 3819
Hello 3820
Hello 3821
Hello 3822
Hello 3823
Hello 3824
Hello 3825
Hello 3826
Hello 3827
Hello 3828
Hello 3829
Hello 3830
Hello 3831
Hello 3832
Hello 3833
Hello 3834
Hello 3835
Hello 3836
Hello 3837
Hello 3838
Hello 3839
Hello 3840
Hello 3841
Hello 3842
Hello 3843
Hello 3844
Hello 3845
Hello 3846
Hello 3847
Hello 3848
Hello 3849
Hello 3850
Hello 3851
Hello 3852
Hello 3853
Hello 3854
Hello 3855
Hello 3856
Hello 3857
Hello 3858
Hello 3859
Hello 3860
Hello 3861
Hello 3862
Hello 3863
Hello 3864
Hello 3865

 33%|███▎      | 3911/12000 [00:08<00:18, 429.52it/s]

Hello 3866
Hello 3867
Hello 3868
Hello 3869
Hello 3870
Hello 3871
Hello 3872
Hello 3873
Hello 3874
Hello 3875
Hello 3876
Hello 3877
Hello 3878
Hello 3879
Hello 3880
Hello 3881
Hello 3882
Hello 3883
Hello 3884
Hello 3885
Hello 3886
Hello 3887
Hello 3888
Hello 3889
Hello 3890
Hello 3891
Hello 3892
Hello 3893
Hello 3894
Hello 3895
Hello 3896
Hello 3897
Hello 3898
Hello 3899
Hello 3900
Hello 3901
Hello 3902
Hello 3903
Hello 3904
Hello 3905
Hello 3906
Hello 3907
Hello 3908
Hello 3909
Hello 3910
Hello 3911
Hello 3912
Hello 3913
Hello 3914
Hello 3915
Hello 3916
Hello 3917
Hello 3918
Hello 3919
Hello 3920
Hello 3921
Hello 3922
Hello 3923
Hello 3924
Hello 3925
Hello 3926
Hello 3927
Hello 3928
Hello 3929
Hello 3930
Hello 3931
Hello 3932
Hello 3933
Hello 3934
Hello 3935
Hello 3936
Hello 3937
Hello 3938
Hello 3939
Hello 3940
Hello 3941
Hello 3942
Hello 3943
Hello 3944
Hello 3945
Hello 3946
Hello 3947
Hello 3948
Hello 3949
Hello 3950
Hello 3951
Hello 3952
Hello 3953
Hello 3954
Hello 3955
Hello 3956
Hello 3957
Hello 3958
Hello 3959
Hello 3960
Hello 3961

 34%|███▎      | 4023/12000 [00:09<00:16, 490.69it/s]

Hello 3962
Hello 3963
Hello 3964
Hello 3965
Hello 3966
Hello 3967
Hello 3968
Hello 3969
Hello 3970
Hello 3971
Hello 3972
Hello 3973
Hello 3974
Hello 3975
Hello 3976
Hello 3977
Hello 3978
Hello 3979
Hello 3980
Hello 3981
Hello 3982
Hello 3983
Hello 3984
Hello 3985
Hello 3986
Hello 3987
Hello 3988
Hello 3989
Hello 3990
Hello 3991
Hello 3992
Hello 3993
Hello 3994
Hello 3995
Hello 3996
Hello 3997
Hello 3998
Hello 3999
Hello 4000
Hello 4001
Hello 4002
Hello 4003
Hello 4004
Hello 4005
Hello 4006
Hello 4007
Hello 4008
Hello 4009
Hello 4010
Hello 4011
Hello 4012
Hello 4013
Hello 4014
Hello 4015
Hello 4016
Hello 4017
Hello 4018
Hello 4019
Hello 4020
Hello 4021
Hello 4022
Hello 4023
Hello 4024
Hello 4025
Hello 4026
Hello 4027
Hello 4028
Hello 4029
Hello 4030
Hello 4031
Hello 4032
Hello 4033
Hello 4034
Hello 4035
Hello 4036
Hello 4037
Hello 4038
Hello 4039
Hello 4040
Hello 4041
Hello 4042
Hello 4043
Hello 4044
Hello 4045
Hello 4046
Hello 4047
Hello 4048
Hello 4049
Hello 4050
Hello 4051
Hello 4052
Hello 4053
Hello 4054
Hello 4055
Hello 4056
Hello 4057
Hello 4058
Hello 4059
Hello 4060
Hello 4061
Hello 4062
Hello 4063
Hello 4064
Hello 4065
Hello 4066
Hello 4067
Hello 4068
Hello 4069
Hello 4070
Hello 4071
Hello 4072
Hello 4073
Hello 4074
Hello 4075
Hello 4076
Hello 4077
Hello 4078
Hello 4079
Hello 4080

 34%|███▍      | 4135/12000 [00:09<00:15, 497.37it/s]

Hello 4081
Hello 4082
Hello 4083
Hello 4084
Hello 4085
Hello 4086
Hello 4087
Hello 4088
Hello 4089
Hello 4090
Hello 4091
Hello 4092
Hello 4093
Hello 4094
Hello 4095
Hello 4096
Hello 4097
Hello 4098
Hello 4099
Hello 4100
Hello 4101
Hello 4102
Hello 4103
Hello 4104
Hello 4105
Hello 4106
Hello 4107
Hello 4108
Hello 4109
Hello 4110
Hello 4111
Hello 4112
Hello 4113
Hello 4114
Hello 4115
Hello 4116
Hello 4117
Hello 4118
Hello 4119
Hello 4120
Hello 4121
Hello 4122
Hello 4123
Hello 4124
Hello 4125
Hello 4126
Hello 4127
Hello 4128
Hello 4129
Hello 4130
Hello 4131
Hello 4132
Hello 4133
Hello 4134
Hello 4135
Hello 4136
Hello 4137
Hello 4138
Hello 4139
Hello 4140
Hello 4141
Hello 4142
Hello 4143
Hello 4144
Hello 4145
Hello 4146
Hello 4147
Hello 4148
Hello 4149
Hello 4150
Hello 4151
Hello 4152
Hello 4153
Hello 4154
Hello 4155
Hello 4156
Hello 4157
Hello 4158
Hello 4159
Hello 4160
Hello 4161
Hello 4162
Hello 4163
Hello 4164
Hello 4165
Hello 4166
Hello 4167
Hello 4168
Hello 4169
Hello 4170
Hello 4171
Hello 4172
Hello 4173
Hello 4174
Hello 4175
Hello 4176
Hello 4177
Hello 4178
Hello 4179
Hello 4180
Hello 4181
Hello 4182
Hello 4183
Hello 4184
Hello 4185

 35%|███▍      | 4193/12000 [00:09<00:15, 520.15it/s]

Hello 4186
Hello 4187
Hello 4188
Hello 4189
Hello 4190
Hello 4191
Hello 4192
Hello 4193
Hello 4194
Hello 4195
Hello 4196
Hello 4197
Hello 4198
Hello 4199
Hello 4200
Hello 4201
Hello 4202
Hello 4203
Hello 4204
Hello 4205
Hello 4206
Hello 4207
Hello 4208
Hello 4209
Hello 4210
Hello 4211
Hello 4212
Hello 4213
Hello 4214
Hello 4215
Hello 4216
Hello 4217
Hello 4218
Hello 4219
Hello 4220
Hello 4221
Hello 4222
Hello 4223
Hello 4224
Hello 4225
Hello 4226
Hello 4227
Hello 4228
Hello 4229
Hello 4230
Hello 4231
Hello 4232
Hello 4233
Hello 4234
Hello 4235
Hello 4236
Hello 4237
Hello 4238
Hello 4239
Hello 4240
Hello 4241
Hello 4242
Hello 4243
Hello 4244
Hello 4245

 36%|███▌      | 4304/12000 [00:09<00:16, 453.83it/s]

Hello 4246
Hello 4247
Hello 4248
Hello 4249
Hello 4250
Hello 4251
Hello 4252
Hello 4253
Hello 4254
Hello 4255
Hello 4256
Hello 4257
Hello 4258
Hello 4259
Hello 4260
Hello 4261
Hello 4262
Hello 4263
Hello 4264
Hello 4265
Hello 4266
Hello 4267
Hello 4268
Hello 4269
Hello 4270
Hello 4271
Hello 4272
Hello 4273
Hello 4274
Hello 4275
Hello 4276
Hello 4277
Hello 4278
Hello 4279
Hello 4280
Hello 4281
Hello 4282
Hello 4283
Hello 4284
Hello 4285
Hello 4286
Hello 4287
Hello 4288
Hello 4289
Hello 4290
Hello 4291
Hello 4292
Hello 4293
Hello 4294
Hello 4295
Hello 4296
Hello 4297
Hello 4298
Hello 4299
Hello 4300
Hello 4301
Hello 4302
Hello 4303
Hello 4304
Hello 4305
Hello 4306
Hello 4307
Hello 4308
Hello 4309
Hello 4310
Hello 4311
Hello 4312
Hello 4313
Hello 4314
Hello 4315
Hello 4316
Hello 4317
Hello 4318
Hello 4319
Hello 4320
Hello 4321
Hello 4322
Hello 4323
Hello 4324
Hello 4325
Hello 4326
Hello 4327
Hello 4328
Hello 4329
Hello 4330
Hello 4331
Hello 4332
Hello 4333
Hello 4334
Hello 4335
Hello 4336
Hello 4337
Hello 4338
Hello 4339
Hello 4340
Hello 4341
Hello 4342
Hello 4343
Hello 4344
Hello 4345
Hello 4346
Hello 4347
Hello 4348
Hello 4349
Hello 4350
Hello 4351
Hello 4352
Hello 4353
Hello 4354
Hello 4355
Hello 4356
Hello 4357
Hello 4358
Hello 4359
Hello 4360
Hello 4361
Hello 4362
Hello 4363
Hello 4364
Hello 4365

 37%|███▋      | 4431/12000 [00:10<00:14, 515.78it/s]

Hello 4366
Hello 4367
Hello 4368
Hello 4369
Hello 4370
Hello 4371
Hello 4372
Hello 4373
Hello 4374
Hello 4375
Hello 4376
Hello 4377
Hello 4378
Hello 4379
Hello 4380
Hello 4381
Hello 4382
Hello 4383
Hello 4384
Hello 4385
Hello 4386
Hello 4387
Hello 4388
Hello 4389
Hello 4390
Hello 4391
Hello 4392
Hello 4393
Hello 4394
Hello 4395
Hello 4396
Hello 4397
Hello 4398
Hello 4399
Hello 4400
Hello 4401
Hello 4402
Hello 4403
Hello 4404
Hello 4405
Hello 4406
Hello 4407
Hello 4408
Hello 4409
Hello 4410
Hello 4411
Hello 4412
Hello 4413
Hello 4414
Hello 4415
Hello 4416
Hello 4417
Hello 4418
Hello 4419
Hello 4420
Hello 4421
Hello 4422
Hello 4423
Hello 4424
Hello 4425
Hello 4426
Hello 4427
Hello 4428
Hello 4429
Hello 4430
Hello 4431
Hello 4432
Hello 4433
Hello 4434
Hello 4435
Hello 4436
Hello 4437
Hello 4438
Hello 4439
Hello 4440
Hello 4441
Hello 4442
Hello 4443
Hello 4444
Hello 4445
Hello 4446
Hello 4447
Hello 4448
Hello 4449
Hello 4450
Hello 4451
Hello 4452
Hello 4453
Hello 4454
Hello 4455
Hello 4456
Hello 4457
Hello 4458
Hello 4459
Hello 4460
Hello 4461
Hello 4462
Hello 4463
Hello 4464
Hello 4465
Hello 4466
Hello 4467
Hello 4468
Hello 4469
Hello 4470
Hello 4471
Hello 4472
Hello 4473
Hello 4474
Hello 4475
Hello 4476
Hello 4477

 38%|███▊      | 4616/12000 [00:10<00:12, 572.38it/s]

Hello 4478
Hello 4479
Hello 4480
Hello 4481
Hello 4482
Hello 4483
Hello 4484
Hello 4485
Hello 4486
Hello 4487
Hello 4488
Hello 4489
Hello 4490
Hello 4491
Hello 4492
Hello 4493
Hello 4494
Hello 4495
Hello 4496
Hello 4497
Hello 4498
Hello 4499
Hello 4500
Hello 4501
Hello 4502
Hello 4503
Hello 4504
Hello 4505
Hello 4506
Hello 4507
Hello 4508
Hello 4509
Hello 4510
Hello 4511
Hello 4512
Hello 4513
Hello 4514
Hello 4515
Hello 4516
Hello 4517
Hello 4518
Hello 4519
Hello 4520
Hello 4521
Hello 4522
Hello 4523
Hello 4524
Hello 4525
Hello 4526
Hello 4527
Hello 4528
Hello 4529
Hello 4530
Hello 4531
Hello 4532
Hello 4533
Hello 4534
Hello 4535
Hello 4536
Hello 4537
Hello 4538
Hello 4539
Hello 4540
Hello 4541
Hello 4542
Hello 4543
Hello 4544
Hello 4545
Hello 4546
Hello 4547
Hello 4548
Hello 4549
Hello 4550
Hello 4551
Hello 4552
Hello 4553
Hello 4554
Hello 4555
Hello 4556
Hello 4557
Hello 4558
Hello 4559
Hello 4560
Hello 4561
Hello 4562
Hello 4563
Hello 4564
Hello 4565
Hello 4566
Hello 4567
Hello 4568
Hello 4569
Hello 4570
Hello 4571
Hello 4572
Hello 4573
Hello 4574
Hello 4575
Hello 4576
Hello 4577
Hello 4578
Hello 4579
Hello 4580
Hello 4581
Hello 4582
Hello 4583
Hello 4584
Hello 4585
Hello 4586
Hello 4587
Hello 4588
Hello 4589
Hello 4590
Hello 4591
Hello 4592
Hello 4593
Hello 4594
Hello 4595
Hello 4596
Hello 4597
Hello 4598
Hello 4599
Hello 4600
Hello 4601
Hello 4602
Hello 4603
Hello 4604
Hello 4605
Hello 4606
Hello 4607
Hello 4608
Hello 4609
Hello 4610
Hello 4611
Hello 4612
Hello 4613
Hello 4614
Hello 4615

 39%|███▉      | 4680/12000 [00:10<00:12, 587.60it/s]

Hello 4616
Hello 4617
Hello 4618
Hello 4619
Hello 4620
Hello 4621
Hello 4622
Hello 4623
Hello 4624
Hello 4625
Hello 4626
Hello 4627
Hello 4628
Hello 4629
Hello 4630
Hello 4631
Hello 4632
Hello 4633
Hello 4634
Hello 4635
Hello 4636
Hello 4637
Hello 4638
Hello 4639
Hello 4640
Hello 4641
Hello 4642
Hello 4643
Hello 4644
Hello 4645
Hello 4646
Hello 4647
Hello 4648
Hello 4649
Hello 4650
Hello 4651
Hello 4652
Hello 4653
Hello 4654
Hello 4655
Hello 4656
Hello 4657
Hello 4658
Hello 4659
Hello 4660
Hello 4661
Hello 4662
Hello 4663
Hello 4664
Hello 4665
Hello 4666
Hello 4667
Hello 4668
Hello 4669
Hello 4670
Hello 4671
Hello 4672
Hello 4673
Hello 4674
Hello 4675
Hello 4676
Hello 4677
Hello 4678
Hello 4679
Hello 4680
Hello 4681
Hello 4682
Hello 4683
Hello 4684
Hello 4685
Hello 4686
Hello 4687
Hello 4688
Hello 4689
Hello 4690
Hello 4691
Hello 4692
Hello 4693
Hello 4694
Hello 4695
Hello 4696
Hello 4697
Hello 4698
Hello 4699
Hello 4700
Hello 4701
Hello 4702
Hello 4703
Hello 4704
Hello 4705
Hello 4706
Hello 4707
Hello 4708
Hello 4709
Hello 4710
Hello 4711
Hello 4712
Hello 4713
Hello 4714
Hello 4715
Hello 4716
Hello 4717
Hello 4718
Hello 4719
Hello 4720
Hello 4721
Hello 4722
Hello 4723
Hello 4724
Hello 4725
Hello 4726
Hello 4727
Hello 4728
Hello 4729
Hello 4730
Hello 4731
Hello 4732
Hello 4733
Hello 4734
Hello 4735
Hello 4736
Hello 4737
Hello 4738
Hello 4739
Hello 4740
Hello 4741
Hello 4742

 40%|████      | 4803/12000 [00:10<00:13, 551.68it/s]

Hello 4743
Hello 4744
Hello 4745
Hello 4746
Hello 4747
Hello 4748
Hello 4749
Hello 4750
Hello 4751
Hello 4752
Hello 4753
Hello 4754
Hello 4755
Hello 4756
Hello 4757
Hello 4758
Hello 4759
Hello 4760
Hello 4761
Hello 4762
Hello 4763
Hello 4764
Hello 4765
Hello 4766
Hello 4767
Hello 4768
Hello 4769
Hello 4770
Hello 4771
Hello 4772
Hello 4773
Hello 4774
Hello 4775
Hello 4776
Hello 4777
Hello 4778
Hello 4779
Hello 4780
Hello 4781
Hello 4782
Hello 4783
Hello 4784
Hello 4785
Hello 4786
Hello 4787
Hello 4788
Hello 4789
Hello 4790
Hello 4791
Hello 4792
Hello 4793
Hello 4794
Hello 4795
Hello 4796
Hello 4797
Hello 4798
Hello 4799
Hello 4800
Hello 4801
Hello 4802
Hello 4803
Hello 4804
Hello 4805
Hello 4806
Hello 4807
Hello 4808
Hello 4809
Hello 4810
Hello 4811
Hello 4812
Hello 4813
Hello 4814
Hello 4815
Hello 4816
Hello 4817
Hello 4818
Hello 4819
Hello 4820
Hello 4821
Hello 4822
Hello 4823
Hello 4824
Hello 4825
Hello 4826
Hello 4827
Hello 4828
Hello 4829
Hello 4830
Hello 4831
Hello 4832
Hello 4833
Hello 4834
Hello 4835
Hello 4836
Hello 4837
Hello 4838
Hello 4839
Hello 4840
Hello 4841
Hello 4842
Hello 4843
Hello 4844
Hello 4845
Hello 4846
Hello 4847
Hello 4848
Hello 4849

 41%|████      | 4913/12000 [00:10<00:14, 486.62it/s]

Hello 4850
Hello 4851
Hello 4852
Hello 4853
Hello 4854
Hello 4855
Hello 4856
Hello 4857
Hello 4858
Hello 4859
Hello 4860
Hello 4861
Hello 4862
Hello 4863
Hello 4864
Hello 4865
Hello 4866
Hello 4867
Hello 4868
Hello 4869
Hello 4870
Hello 4871
Hello 4872
Hello 4873
Hello 4874
Hello 4875
Hello 4876
Hello 4877
Hello 4878
Hello 4879
Hello 4880
Hello 4881
Hello 4882
Hello 4883
Hello 4884
Hello 4885
Hello 4886
Hello 4887
Hello 4888
Hello 4889
Hello 4890
Hello 4891
Hello 4892
Hello 4893
Hello 4894
Hello 4895
Hello 4896
Hello 4897
Hello 4898
Hello 4899
Hello 4900
Hello 4901
Hello 4902
Hello 4903
Hello 4904
Hello 4905
Hello 4906
Hello 4907
Hello 4908
Hello 4909
Hello 4910
Hello 4911
Hello 4912
Hello 4913
Hello 4914
Hello 4915
Hello 4916
Hello 4917
Hello 4918
Hello 4919
Hello 4920
Hello 4921
Hello 4922
Hello 4923
Hello 4924
Hello 4925
Hello 4926
Hello 4927
Hello 4928
Hello 4929
Hello 4930
Hello 4931
Hello 4932

 41%|████▏     | 4963/12000 [00:11<00:16, 420.52it/s]

Hello 4933
Hello 4934
Hello 4935
Hello 4936
Hello 4937
Hello 4938
Hello 4939
Hello 4940
Hello 4941
Hello 4942
Hello 4943
Hello 4944
Hello 4945
Hello 4946
Hello 4947
Hello 4948
Hello 4949
Hello 4950
Hello 4951
Hello 4952
Hello 4953
Hello 4954
Hello 4955
Hello 4956
Hello 4957
Hello 4958
Hello 4959
Hello 4960
Hello 4961
Hello 4962
Hello 4963
Hello 4964
Hello 4965
Hello 4966
Hello 4967
Hello 4968
Hello 4969
Hello 4970
Hello 4971
Hello 4972
Hello 4973
Hello 4974
Hello 4975
Hello 4976
Hello 4977
Hello 4978
Hello 4979
Hello 4980
Hello 4981
Hello 4982
Hello 4983
Hello 4984
Hello 4985
Hello 4986
Hello 4987
Hello 4988
Hello 4989
Hello 4990
Hello 4991
Hello 4992
Hello 4993
Hello 4994
Hello 4995
Hello 4996
Hello 4997
Hello 4998
Hello 4999
Hello 5000
Hello 5001
Hello 5002
Hello 5003
Hello 5004

 42%|████▏     | 5050/12000 [00:11<00:18, 369.24it/s]

Hello 5005
Hello 5006
Hello 5007
Hello 5008
Hello 5009
Hello 5010
Hello 5011
Hello 5012
Hello 5013
Hello 5014
Hello 5015
Hello 5016
Hello 5017
Hello 5018
Hello 5019
Hello 5020
Hello 5021
Hello 5022
Hello 5023
Hello 5024
Hello 5025
Hello 5026
Hello 5027
Hello 5028
Hello 5029
Hello 5030
Hello 5031
Hello 5032
Hello 5033
Hello 5034
Hello 5035
Hello 5036
Hello 5037
Hello 5038
Hello 5039
Hello 5040
Hello 5041
Hello 5042
Hello 5043
Hello 5044
Hello 5045
Hello 5046
Hello 5047
Hello 5048
Hello 5049
Hello 5050
Hello 5051
Hello 5052
Hello 5053
Hello 5054
Hello 5055
Hello 5056
Hello 5057
Hello 5058
Hello 5059
Hello 5060
Hello 5061
Hello 5062
Hello 5063
Hello 5064
Hello 5065
Hello 5066
Hello 5067
Hello 5068
Hello 5069
Hello 5070
Hello 5071
Hello 5072
Hello 5073
Hello 5074
Hello 5075
Hello 5076
Hello 5077
Hello 5078
Hello 5079

 43%|████▎     | 5138/12000 [00:11<00:17, 388.75it/s]

Hello 5080
Hello 5081
Hello 5082
Hello 5083
Hello 5084
Hello 5085
Hello 5086
Hello 5087
Hello 5088
Hello 5089
Hello 5090
Hello 5091
Hello 5092
Hello 5093
Hello 5094
Hello 5095
Hello 5096
Hello 5097
Hello 5098
Hello 5099
Hello 5100
Hello 5101
Hello 5102
Hello 5103
Hello 5104
Hello 5105
Hello 5106
Hello 5107
Hello 5108
Hello 5109
Hello 5110
Hello 5111
Hello 5112
Hello 5113
Hello 5114
Hello 5115
Hello 5116
Hello 5117
Hello 5118
Hello 5119
Hello 5120
Hello 5121
Hello 5122
Hello 5123
Hello 5124
Hello 5125
Hello 5126
Hello 5127
Hello 5128
Hello 5129
Hello 5130
Hello 5131
Hello 5132
Hello 5133
Hello 5134
Hello 5135
Hello 5136
Hello 5137
Hello 5138
Hello 5139
Hello 5140
Hello 5141
Hello 5142
Hello 5143
Hello 5144
Hello 5145
Hello 5146
Hello 5147
Hello 5148
Hello 5149
Hello 5150
Hello 5151
Hello 5152
Hello 5153
Hello 5154
Hello 5155
Hello 5156
Hello 5157
Hello 5158
Hello 5159
Hello 5160
Hello 5161
Hello 5162
Hello 5163
Hello 5164
Hello 5165
Hello 5166
Hello 5167
Hello 5168
Hello 5169
Hello 5170
Hello 5171
Hello 5172
Hello 5173
Hello 5174
Hello 5175
Hello 5176
Hello 5177
Hello 5178

 43%|████▎     | 5205/12000 [00:11<00:14, 457.01it/s]

Hello 5179
Hello 5180
Hello 5181
Hello 5182
Hello 5183
Hello 5184
Hello 5185
Hello 5186
Hello 5187
Hello 5188
Hello 5189
Hello 5190
Hello 5191
Hello 5192
Hello 5193
Hello 5194
Hello 5195
Hello 5196
Hello 5197
Hello 5198
Hello 5199
Hello 5200
Hello 5201
Hello 5202
Hello 5203
Hello 5204
Hello 5205
Hello 5206
Hello 5207
Hello 5208
Hello 5209
Hello 5210
Hello 5211
Hello 5212
Hello 5213
Hello 5214
Hello 5215
Hello 5216
Hello 5217
Hello 5218
Hello 5219
Hello 5220
Hello 5221
Hello 5222
Hello 5223
Hello 5224
Hello 5225
Hello 5226
Hello 5227
Hello 5228
Hello 5229
Hello 5230
Hello 5231
Hello 5232
Hello 5233
Hello 5234
Hello 5235
Hello 5236
Hello 5237
Hello 5238
Hello 5239
Hello 5240
Hello 5241
Hello 5242
Hello 5243
Hello 5244
Hello 5245
Hello 5246
Hello 5247
Hello 5248
Hello 5249
Hello 5250
Hello 5251
Hello 5252

 44%|████▍     | 5296/12000 [00:11<00:16, 398.90it/s]

Hello 5253
Hello 5254
Hello 5255
Hello 5256
Hello 5257
Hello 5258
Hello 5259
Hello 5260
Hello 5261
Hello 5262
Hello 5263
Hello 5264
Hello 5265
Hello 5266
Hello 5267
Hello 5268
Hello 5269
Hello 5270
Hello 5271
Hello 5272
Hello 5273
Hello 5274
Hello 5275
Hello 5276
Hello 5277
Hello 5278
Hello 5279
Hello 5280
Hello 5281
Hello 5282
Hello 5283
Hello 5284
Hello 5285
Hello 5286
Hello 5287
Hello 5288
Hello 5289
Hello 5290
Hello 5291
Hello 5292
Hello 5293
Hello 5294
Hello 5295
Hello 5296
Hello 5297
Hello 5298
Hello 5299
Hello 5300
Hello 5301
Hello 5302
Hello 5303
Hello 5304
Hello 5305
Hello 5306
Hello 5307
Hello 5308
Hello 5309
Hello 5310
Hello 5311
Hello 5312
Hello 5313
Hello 5314
Hello 5315
Hello 5316
Hello 5317
Hello 5318
Hello 5319
Hello 5320
Hello 5321
Hello 5322
Hello 5323
Hello 5324
Hello 5325
Hello 5326
Hello 5327
Hello 5328
Hello 5329
Hello 5330
Hello 5331
Hello 5332
Hello 5333
Hello 5334
Hello 5335
Hello 5336
Hello 5337
Hello 5338
Hello 5339
Hello 5340
Hello 5341
Hello 5342
Hello 5343
Hello 5344

 45%|████▌     | 5446/12000 [00:12<00:14, 459.43it/s]

Hello 5345
Hello 5346
Hello 5347
Hello 5348
Hello 5349
Hello 5350
Hello 5351
Hello 5352
Hello 5353
Hello 5354
Hello 5355
Hello 5356
Hello 5357
Hello 5358
Hello 5359
Hello 5360
Hello 5361
Hello 5362
Hello 5363
Hello 5364
Hello 5365
Hello 5366
Hello 5367
Hello 5368
Hello 5369
Hello 5370
Hello 5371
Hello 5372
Hello 5373
Hello 5374
Hello 5375
Hello 5376
Hello 5377
Hello 5378
Hello 5379
Hello 5380
Hello 5381
Hello 5382
Hello 5383
Hello 5384
Hello 5385
Hello 5386
Hello 5387
Hello 5388
Hello 5389
Hello 5390
Hello 5391
Hello 5392
Hello 5393
Hello 5394
Hello 5395
Hello 5396
Hello 5397
Hello 5398
Hello 5399
Hello 5400
Hello 5401
Hello 5402
Hello 5403
Hello 5404
Hello 5405
Hello 5406
Hello 5407
Hello 5408
Hello 5409
Hello 5410
Hello 5411
Hello 5412
Hello 5413
Hello 5414
Hello 5415
Hello 5416
Hello 5417
Hello 5418
Hello 5419
Hello 5420
Hello 5421
Hello 5422
Hello 5423
Hello 5424
Hello 5425
Hello 5426
Hello 5427
Hello 5428
Hello 5429
Hello 5430
Hello 5431
Hello 5432
Hello 5433
Hello 5434
Hello 5435
Hello 5436
Hello 5437
Hello 5438
Hello 5439
Hello 5440
Hello 5441
Hello 5442
Hello 5443
Hello 5444
Hello 5445

 46%|████▌     | 5502/12000 [00:12<00:13, 471.40it/s]

Hello 5446
Hello 5447
Hello 5448
Hello 5449
Hello 5450
Hello 5451
Hello 5452
Hello 5453
Hello 5454
Hello 5455
Hello 5456
Hello 5457
Hello 5458
Hello 5459
Hello 5460
Hello 5461
Hello 5462
Hello 5463
Hello 5464
Hello 5465
Hello 5466
Hello 5467
Hello 5468
Hello 5469
Hello 5470
Hello 5471
Hello 5472
Hello 5473
Hello 5474
Hello 5475
Hello 5476
Hello 5477
Hello 5478
Hello 5479
Hello 5480
Hello 5481
Hello 5482
Hello 5483
Hello 5484
Hello 5485
Hello 5486
Hello 5487
Hello 5488
Hello 5489
Hello 5490
Hello 5491
Hello 5492
Hello 5493
Hello 5494
Hello 5495
Hello 5496
Hello 5497
Hello 5498
Hello 5499
Hello 5500
Hello 5501
Hello 5502
Hello 5503
Hello 5504
Hello 5505
Hello 5506
Hello 5507
Hello 5508
Hello 5509
Hello 5510
Hello 5511
Hello 5512
Hello 5513
Hello 5514
Hello 5515
Hello 5516
Hello 5517
Hello 5518
Hello 5519
Hello 5520
Hello 5521
Hello 5522
Hello 5523
Hello 5524
Hello 5525
Hello 5526
Hello 5527
Hello 5528
Hello 5529
Hello 5530
Hello 5531
Hello 5532
Hello 5533
Hello 5534
Hello 5535
Hello 5536
Hello 5537
Hello 5538
Hello 5539
Hello 5540
Hello 5541
Hello 5542
Hello 5543
Hello 5544
Hello 5545
Hello 5546
Hello 5547

 47%|████▋     | 5597/12000 [00:12<00:14, 453.75it/s]

Hello 5548
Hello 5549
Hello 5550
Hello 5551
Hello 5552
Hello 5553
Hello 5554
Hello 5555
Hello 5556
Hello 5557
Hello 5558
Hello 5559
Hello 5560
Hello 5561
Hello 5562
Hello 5563
Hello 5564
Hello 5565
Hello 5566
Hello 5567
Hello 5568
Hello 5569
Hello 5570
Hello 5571
Hello 5572
Hello 5573
Hello 5574
Hello 5575
Hello 5576
Hello 5577
Hello 5578
Hello 5579
Hello 5580
Hello 5581
Hello 5582
Hello 5583
Hello 5584
Hello 5585
Hello 5586
Hello 5587
Hello 5588
Hello 5589
Hello 5590
Hello 5591
Hello 5592
Hello 5593
Hello 5594
Hello 5595
Hello 5596
Hello 5597
Hello 5598
Hello 5599
Hello 5600
Hello 5601
Hello 5602
Hello 5603
Hello 5604
Hello 5605
Hello 5606
Hello 5607
Hello 5608
Hello 5609
Hello 5610
Hello 5611
Hello 5612
Hello 5613
Hello 5614
Hello 5615
Hello 5616
Hello 5617
Hello 5618
Hello 5619
Hello 5620
Hello 5621
Hello 5622
Hello 5623
Hello 5624
Hello 5625
Hello 5626
Hello 5627
Hello 5628
Hello 5629
Hello 5630
Hello 5631
Hello 5632
Hello 5633
Hello 5634
Hello 5635
Hello 5636
Hello 5637
Hello 5638
Hello 5639
Hello 5640
Hello 5641
Hello 5642
Hello 5643
Hello 5644
Hello 5645
Hello 5646
Hello 5647
Hello 5648
Hello 5649
Hello 5650
Hello 5651
Hello 5652
Hello 5653
Hello 5654
Hello 5655
Hello 5656
Hello 5657
Hello 5658
Hello 5659
Hello 5660
Hello 5661
Hello 5662
Hello 5663
Hello 5664

 48%|████▊     | 5716/12000 [00:12<00:14, 440.52it/s]

Hello 5665
Hello 5666
Hello 5667
Hello 5668
Hello 5669
Hello 5670
Hello 5671
Hello 5672
Hello 5673
Hello 5674
Hello 5675
Hello 5676
Hello 5677
Hello 5678
Hello 5679
Hello 5680
Hello 5681
Hello 5682
Hello 5683
Hello 5684
Hello 5685
Hello 5686
Hello 5687
Hello 5688
Hello 5689
Hello 5690
Hello 5691
Hello 5692
Hello 5693
Hello 5694
Hello 5695
Hello 5696
Hello 5697
Hello 5698
Hello 5699
Hello 5700
Hello 5701
Hello 5702
Hello 5703
Hello 5704
Hello 5705
Hello 5706
Hello 5707
Hello 5708
Hello 5709
Hello 5710
Hello 5711
Hello 5712
Hello 5713
Hello 5714
Hello 5715
Hello 5716
Hello 5717
Hello 5718
Hello 5719
Hello 5720
Hello 5721
Hello 5722
Hello 5723
Hello 5724
Hello 5725

 48%|████▊     | 5806/12000 [00:13<00:14, 416.77it/s]

Hello 5726
Hello 5727
Hello 5728
Hello 5729
Hello 5730
Hello 5731
Hello 5732
Hello 5733
Hello 5734
Hello 5735
Hello 5736
Hello 5737
Hello 5738
Hello 5739
Hello 5740
Hello 5741
Hello 5742
Hello 5743
Hello 5744
Hello 5745
Hello 5746
Hello 5747
Hello 5748
Hello 5749
Hello 5750
Hello 5751
Hello 5752
Hello 5753
Hello 5754
Hello 5755
Hello 5756
Hello 5757
Hello 5758
Hello 5759
Hello 5760
Hello 5761
Hello 5762
Hello 5763
Hello 5764
Hello 5765
Hello 5766
Hello 5767
Hello 5768
Hello 5769
Hello 5770
Hello 5771
Hello 5772
Hello 5773
Hello 5774
Hello 5775
Hello 5776
Hello 5777
Hello 5778
Hello 5779
Hello 5780
Hello 5781
Hello 5782
Hello 5783
Hello 5784
Hello 5785
Hello 5786
Hello 5787
Hello 5788
Hello 5789
Hello 5790
Hello 5791
Hello 5792
Hello 5793
Hello 5794
Hello 5795
Hello 5796
Hello 5797
Hello 5798
Hello 5799
Hello 5800
Hello 5801
Hello 5802
Hello 5803
Hello 5804
Hello 5805
Hello 5806
Hello 5807
Hello 5808
Hello 5809
Hello 5810
Hello 5811
Hello 5812
Hello 5813
Hello 5814
Hello 5815
Hello 5816
Hello 5817
Hello 5818
Hello 5819
Hello 5820
Hello 5821
Hello 5822
Hello 5823
Hello 5824
Hello 5825
Hello 5826
Hello 5827
Hello 5828

 49%|████▉     | 5925/12000 [00:13<00:12, 477.60it/s]

Hello 5829
Hello 5830
Hello 5831
Hello 5832
Hello 5833
Hello 5834
Hello 5835
Hello 5836
Hello 5837
Hello 5838
Hello 5839
Hello 5840
Hello 5841
Hello 5842
Hello 5843
Hello 5844
Hello 5845
Hello 5846
Hello 5847
Hello 5848
Hello 5849
Hello 5850
Hello 5851
Hello 5852
Hello 5853
Hello 5854
Hello 5855
Hello 5856
Hello 5857
Hello 5858
Hello 5859
Hello 5860
Hello 5861
Hello 5862
Hello 5863
Hello 5864
Hello 5865
Hello 5866
Hello 5867
Hello 5868
Hello 5869
Hello 5870
Hello 5871
Hello 5872
Hello 5873
Hello 5874
Hello 5875
Hello 5876
Hello 5877
Hello 5878
Hello 5879
Hello 5880
Hello 5881
Hello 5882
Hello 5883
Hello 5884
Hello 5885
Hello 5886
Hello 5887
Hello 5888
Hello 5889
Hello 5890
Hello 5891
Hello 5892
Hello 5893
Hello 5894
Hello 5895
Hello 5896
Hello 5897
Hello 5898
Hello 5899
Hello 5900
Hello 5901
Hello 5902
Hello 5903
Hello 5904
Hello 5905
Hello 5906
Hello 5907
Hello 5908
Hello 5909
Hello 5910
Hello 5911
Hello 5912
Hello 5913
Hello 5914
Hello 5915
Hello 5916
Hello 5917
Hello 5918
Hello 5919
Hello 5920
Hello 5921
Hello 5922
Hello 5923
Hello 5924

 50%|████▉     | 5975/12000 [00:13<00:12, 473.43it/s]

Hello 5925
Hello 5926
Hello 5927
Hello 5928
Hello 5929
Hello 5930
Hello 5931
Hello 5932
Hello 5933
Hello 5934
Hello 5935
Hello 5936
Hello 5937
Hello 5938
Hello 5939
Hello 5940
Hello 5941
Hello 5942
Hello 5943
Hello 5944
Hello 5945
Hello 5946
Hello 5947
Hello 5948
Hello 5949
Hello 5950
Hello 5951
Hello 5952
Hello 5953
Hello 5954
Hello 5955
Hello 5956
Hello 5957
Hello 5958
Hello 5959
Hello 5960
Hello 5961
Hello 5962
Hello 5963
Hello 5964
Hello 5965
Hello 5966
Hello 5967
Hello 5968
Hello 5969
Hello 5970
Hello 5971
Hello 5972
Hello 5973
Hello 5974
Hello 5975
Hello 5976
Hello 5977
Hello 5978
Hello 5979
Hello 5980
Hello 5981
Hello 5982
Hello 5983
Hello 5984
Hello 5985
Hello 5986
Hello 5987
Hello 5988
Hello 5989
Hello 5990
Hello 5991
Hello 5992
Hello 5993
Hello 5994
Hello 5995
Hello 5996
Hello 5997
Hello 5998
Hello 5999
Hello 6000
Hello 6001
Hello 6002
Hello 6003
Hello 6004
Hello 6005
Hello 6006
Hello 6007
Hello 6008
Hello 6009
Hello 6010
Hello 6011
Hello 6012
Hello 6013
Hello 6014
Hello 6015
Hello 6016
Hello 6017
Hello 6018
Hello 6019
Hello 6020
Hello 6021
Hello 6022
Hello 6023
Hello 6024
Hello 6025
Hello 6026
Hello 6027
Hello 6028
Hello 6029
Hello 6030
Hello 6031
Hello 6032
Hello 6033
Hello 6034
Hello 6035
Hello 6036
Hello 6037

 51%|█████     | 6093/12000 [00:13<00:13, 440.39it/s]

Hello 6038
Hello 6039
Hello 6040
Hello 6041
Hello 6042
Hello 6043
Hello 6044
Hello 6045
Hello 6046
Hello 6047
Hello 6048
Hello 6049
Hello 6050
Hello 6051
Hello 6052
Hello 6053
Hello 6054
Hello 6055
Hello 6056
Hello 6057
Hello 6058
Hello 6059
Hello 6060
Hello 6061
Hello 6062
Hello 6063
Hello 6064
Hello 6065
Hello 6066
Hello 6067
Hello 6068
Hello 6069
Hello 6070
Hello 6071
Hello 6072
Hello 6073
Hello 6074
Hello 6075
Hello 6076
Hello 6077
Hello 6078
Hello 6079
Hello 6080
Hello 6081
Hello 6082
Hello 6083
Hello 6084
Hello 6085
Hello 6086
Hello 6087
Hello 6088
Hello 6089
Hello 6090
Hello 6091
Hello 6092
Hello 6093
Hello 6094
Hello 6095
Hello 6096
Hello 6097

 51%|█████     | 6140/12000 [00:13<00:15, 381.95it/s]

Hello 6098
Hello 6099
Hello 6100
Hello 6101
Hello 6102
Hello 6103
Hello 6104
Hello 6105
Hello 6106
Hello 6107
Hello 6108
Hello 6109
Hello 6110
Hello 6111
Hello 6112
Hello 6113
Hello 6114
Hello 6115
Hello 6116
Hello 6117
Hello 6118
Hello 6119
Hello 6120
Hello 6121
Hello 6122
Hello 6123
Hello 6124
Hello 6125
Hello 6126
Hello 6127
Hello 6128
Hello 6129
Hello 6130
Hello 6131
Hello 6132
Hello 6133
Hello 6134
Hello 6135
Hello 6136
Hello 6137
Hello 6138
Hello 6139
Hello 6140
Hello 6141
Hello 6142
Hello 6143
Hello 6144
Hello 6145
Hello 6146
Hello 6147
Hello 6148
Hello 6149
Hello 6150
Hello 6151
Hello 6152
Hello 6153
Hello 6154
Hello 6155
Hello 6156
Hello 6157
Hello 6158
Hello 6159
Hello 6160
Hello 6161
Hello 6162
Hello 6163
Hello 6164
Hello 6165
Hello 6166
Hello 6167
Hello 6168
Hello 6169
Hello 6170
Hello 6171
Hello 6172
Hello 6173
Hello 6174
Hello 6175
Hello 6176
Hello 6177
Hello 6178
Hello 6179
Hello 6180
Hello 6181
Hello 6182
Hello 6183
Hello 6184
Hello 6185

 52%|█████▏    | 6258/12000 [00:14<00:12, 455.50it/s]

Hello 6186
Hello 6187
Hello 6188
Hello 6189
Hello 6190
Hello 6191
Hello 6192
Hello 6193
Hello 6194
Hello 6195
Hello 6196
Hello 6197
Hello 6198
Hello 6199
Hello 6200
Hello 6201
Hello 6202
Hello 6203
Hello 6204
Hello 6205
Hello 6206
Hello 6207
Hello 6208
Hello 6209
Hello 6210
Hello 6211
Hello 6212
Hello 6213
Hello 6214
Hello 6215
Hello 6216
Hello 6217
Hello 6218
Hello 6219
Hello 6220
Hello 6221
Hello 6222
Hello 6223
Hello 6224
Hello 6225
Hello 6226
Hello 6227
Hello 6228
Hello 6229
Hello 6230
Hello 6231
Hello 6232
Hello 6233
Hello 6234
Hello 6235
Hello 6236
Hello 6237
Hello 6238
Hello 6239
Hello 6240
Hello 6241
Hello 6242
Hello 6243
Hello 6244
Hello 6245
Hello 6246
Hello 6247
Hello 6248
Hello 6249
Hello 6250
Hello 6251
Hello 6252
Hello 6253
Hello 6254
Hello 6255
Hello 6256
Hello 6257
Hello 6258
Hello 6259
Hello 6260
Hello 6261
Hello 6262
Hello 6263
Hello 6264
Hello 6265
Hello 6266
Hello 6267
Hello 6268
Hello 6269
Hello 6270
Hello 6271
Hello 6272
Hello 6273
Hello 6274
Hello 6275
Hello 6276
Hello 6277
Hello 6278
Hello 6279
Hello 6280
Hello 6281
Hello 6282
Hello 6283
Hello 6284
Hello 6285
Hello 6286
Hello 6287
Hello 6288
Hello 6289
Hello 6290
Hello 6291
Hello 6292
Hello 6293
Hello 6294
Hello 6295
Hello 6296
Hello 6297
Hello 6298
Hello 6299
Hello 6300
Hello 6301
Hello 6302
Hello 6303
Hello 6304
Hello 6305
Hello 6306
Hello 6307
Hello 6308
Hello 6309
Hello 6310
Hello 6311
Hello 6312
Hello 6313
Hello 6314
Hello 6315
Hello 6316
Hello 6317
Hello 6318
Hello 6319
Hello 6320
Hello 6321
Hello 6322
Hello 6323
Hello 6324
Hello 6325
Hello 6326
Hello 6327
Hello 6328
Hello 6329
Hello 6330
Hello 6331
Hello 6332

 53%|█████▎    | 6400/12000 [00:14<00:10, 541.54it/s]

Hello 6333
Hello 6334
Hello 6335
Hello 6336
Hello 6337
Hello 6338
Hello 6339
Hello 6340
Hello 6341
Hello 6342
Hello 6343
Hello 6344
Hello 6345
Hello 6346
Hello 6347
Hello 6348
Hello 6349
Hello 6350
Hello 6351
Hello 6352
Hello 6353
Hello 6354
Hello 6355
Hello 6356
Hello 6357
Hello 6358
Hello 6359
Hello 6360
Hello 6361
Hello 6362
Hello 6363
Hello 6364
Hello 6365
Hello 6366
Hello 6367
Hello 6368
Hello 6369
Hello 6370
Hello 6371
Hello 6372
Hello 6373
Hello 6374
Hello 6375
Hello 6376
Hello 6377
Hello 6378
Hello 6379
Hello 6380
Hello 6381
Hello 6382
Hello 6383
Hello 6384
Hello 6385
Hello 6386
Hello 6387
Hello 6388
Hello 6389
Hello 6390
Hello 6391
Hello 6392
Hello 6393
Hello 6394
Hello 6395
Hello 6396
Hello 6397
Hello 6398
Hello 6399
Hello 6400
Hello 6401
Hello 6402
Hello 6403
Hello 6404
Hello 6405
Hello 6406
Hello 6407
Hello 6408
Hello 6409
Hello 6410
Hello 6411
Hello 6412
Hello 6413
Hello 6414
Hello 6415
Hello 6416
Hello 6417
Hello 6418
Hello 6419
Hello 6420
Hello 6421
Hello 6422
Hello 6423
Hello 6424
Hello 6425
Hello 6426
Hello 6427
Hello 6428
Hello 6429
Hello 6430
Hello 6431
Hello 6432
Hello 6433
Hello 6434
Hello 6435
Hello 6436
Hello 6437
Hello 6438
Hello 6439
Hello 6440
Hello 6441
Hello 6442
Hello 6443
Hello 6444
Hello 6445
Hello 6446
Hello 6447
Hello 6448
Hello 6449
Hello 6450
Hello 6451
Hello 6452
Hello 6453
Hello 6454
Hello 6455
Hello 6456
Hello 6457
Hello 6458
Hello 6459

 54%|█████▍    | 6517/12000 [00:14<00:10, 523.19it/s]

Hello 6460
Hello 6461
Hello 6462
Hello 6463
Hello 6464
Hello 6465
Hello 6466
Hello 6467
Hello 6468
Hello 6469
Hello 6470
Hello 6471
Hello 6472
Hello 6473
Hello 6474
Hello 6475
Hello 6476
Hello 6477
Hello 6478
Hello 6479
Hello 6480
Hello 6481
Hello 6482
Hello 6483
Hello 6484
Hello 6485
Hello 6486
Hello 6487
Hello 6488
Hello 6489
Hello 6490
Hello 6491
Hello 6492
Hello 6493
Hello 6494
Hello 6495
Hello 6496
Hello 6497
Hello 6498
Hello 6499
Hello 6500
Hello 6501
Hello 6502
Hello 6503
Hello 6504
Hello 6505
Hello 6506
Hello 6507
Hello 6508
Hello 6509
Hello 6510
Hello 6511
Hello 6512
Hello 6513
Hello 6514
Hello 6515
Hello 6516
Hello 6517
Hello 6518
Hello 6519
Hello 6520
Hello 6521
Hello 6522
Hello 6523
Hello 6524
Hello 6525
Hello 6526
Hello 6527
Hello 6528
Hello 6529
Hello 6530
Hello 6531
Hello 6532
Hello 6533
Hello 6534
Hello 6535
Hello 6536
Hello 6537
Hello 6538
Hello 6539
Hello 6540
Hello 6541
Hello 6542
Hello 6543
Hello 6544
Hello 6545
Hello 6546
Hello 6547

 55%|█████▌    | 6627/12000 [00:14<00:10, 500.34it/s]

Hello 6548
Hello 6549
Hello 6550
Hello 6551
Hello 6552
Hello 6553
Hello 6554
Hello 6555
Hello 6556
Hello 6557
Hello 6558
Hello 6559
Hello 6560
Hello 6561
Hello 6562
Hello 6563
Hello 6564
Hello 6565
Hello 6566
Hello 6567
Hello 6568
Hello 6569
Hello 6570
Hello 6571
Hello 6572
Hello 6573
Hello 6574
Hello 6575
Hello 6576
Hello 6577
Hello 6578
Hello 6579
Hello 6580
Hello 6581
Hello 6582
Hello 6583
Hello 6584
Hello 6585
Hello 6586
Hello 6587
Hello 6588
Hello 6589
Hello 6590
Hello 6591
Hello 6592
Hello 6593
Hello 6594
Hello 6595
Hello 6596
Hello 6597
Hello 6598
Hello 6599
Hello 6600
Hello 6601
Hello 6602
Hello 6603
Hello 6604
Hello 6605
Hello 6606
Hello 6607
Hello 6608
Hello 6609
Hello 6610
Hello 6611
Hello 6612
Hello 6613
Hello 6614
Hello 6615
Hello 6616
Hello 6617
Hello 6618
Hello 6619
Hello 6620
Hello 6621
Hello 6622
Hello 6623
Hello 6624
Hello 6625
Hello 6626
Hello 6627
Hello 6628
Hello 6629
Hello 6630
Hello 6631
Hello 6632
Hello 6633
Hello 6634
Hello 6635
Hello 6636
Hello 6637
Hello 6638
Hello 6639
Hello 6640
Hello 6641
Hello 6642
Hello 6643
Hello 6644
Hello 6645
Hello 6646
Hello 6647
Hello 6648
Hello 6649
Hello 6650
Hello 6651
Hello 6652
Hello 6653
Hello 6654
Hello 6655
Hello 6656
Hello 6657
Hello 6658
Hello 6659
Hello 6660
Hello 6661
Hello 6662
Hello 6663
Hello 6664

 56%|█████▌    | 6737/12000 [00:14<00:10, 497.45it/s]

Hello 6665
Hello 6666
Hello 6667
Hello 6668
Hello 6669
Hello 6670
Hello 6671
Hello 6672
Hello 6673
Hello 6674
Hello 6675
Hello 6676
Hello 6677
Hello 6678
Hello 6679
Hello 6680
Hello 6681
Hello 6682
Hello 6683
Hello 6684
Hello 6685
Hello 6686
Hello 6687
Hello 6688
Hello 6689
Hello 6690
Hello 6691
Hello 6692
Hello 6693
Hello 6694
Hello 6695
Hello 6696
Hello 6697
Hello 6698
Hello 6699
Hello 6700
Hello 6701
Hello 6702
Hello 6703
Hello 6704
Hello 6705
Hello 6706
Hello 6707
Hello 6708
Hello 6709
Hello 6710
Hello 6711
Hello 6712
Hello 6713
Hello 6714
Hello 6715
Hello 6716
Hello 6717
Hello 6718
Hello 6719
Hello 6720
Hello 6721
Hello 6722
Hello 6723
Hello 6724
Hello 6725
Hello 6726
Hello 6727
Hello 6728
Hello 6729
Hello 6730
Hello 6731
Hello 6732
Hello 6733
Hello 6734
Hello 6735
Hello 6736
Hello 6737
Hello 6738
Hello 6739
Hello 6740
Hello 6741
Hello 6742
Hello 6743
Hello 6744
Hello 6745
Hello 6746
Hello 6747
Hello 6748
Hello 6749
Hello 6750
Hello 6751
Hello 6752
Hello 6753
Hello 6754
Hello 6755
Hello 6756
Hello 6757
Hello 6758
Hello 6759
Hello 6760
Hello 6761
Hello 6762
Hello 6763
Hello 6764
Hello 6765

 57%|█████▋    | 6843/12000 [00:15<00:10, 503.63it/s]

Hello 6766
Hello 6767
Hello 6768
Hello 6769
Hello 6770
Hello 6771
Hello 6772
Hello 6773
Hello 6774
Hello 6775
Hello 6776
Hello 6777
Hello 6778
Hello 6779
Hello 6780
Hello 6781
Hello 6782
Hello 6783
Hello 6784
Hello 6785
Hello 6786
Hello 6787
Hello 6788
Hello 6789
Hello 6790
Hello 6791
Hello 6792
Hello 6793
Hello 6794
Hello 6795
Hello 6796
Hello 6797
Hello 6798
Hello 6799
Hello 6800
Hello 6801
Hello 6802
Hello 6803
Hello 6804
Hello 6805
Hello 6806
Hello 6807
Hello 6808
Hello 6809
Hello 6810
Hello 6811
Hello 6812
Hello 6813
Hello 6814
Hello 6815
Hello 6816
Hello 6817
Hello 6818
Hello 6819
Hello 6820
Hello 6821
Hello 6822
Hello 6823
Hello 6824
Hello 6825
Hello 6826
Hello 6827
Hello 6828
Hello 6829
Hello 6830
Hello 6831
Hello 6832
Hello 6833
Hello 6834
Hello 6835
Hello 6836
Hello 6837
Hello 6838
Hello 6839
Hello 6840
Hello 6841
Hello 6842
Hello 6843
Hello 6844
Hello 6845
Hello 6846
Hello 6847
Hello 6848
Hello 6849
Hello 6850
Hello 6851
Hello 6852
Hello 6853
Hello 6854
Hello 6855
Hello 6856
Hello 6857
Hello 6858
Hello 6859
Hello 6860
Hello 6861
Hello 6862
Hello 6863
Hello 6864
Hello 6865
Hello 6866
Hello 6867
Hello 6868
Hello 6869
Hello 6870
Hello 6871
Hello 6872
Hello 6873
Hello 6874
Hello 6875
Hello 6876
Hello 6877
Hello 6878
Hello 6879
Hello 6880
Hello 6881
Hello 6882
Hello 6883
Hello 6884
Hello 6885
Hello 6886
Hello 6887
Hello 6888
Hello 6889
Hello 6890
Hello 6891
Hello 6892
Hello 6893
Hello 6894
Hello 6895
Hello 6896
Hello 6897
Hello 6898
Hello 6899
Hello 6900
Hello 6901
Hello 6902
Hello 6903
Hello 6904
Hello 6905
Hello 6906

 58%|█████▊    | 6968/12000 [00:15<00:10, 494.61it/s]

Hello 6907
Hello 6908
Hello 6909
Hello 6910
Hello 6911
Hello 6912
Hello 6913
Hello 6914
Hello 6915
Hello 6916
Hello 6917
Hello 6918
Hello 6919
Hello 6920
Hello 6921
Hello 6922
Hello 6923
Hello 6924
Hello 6925
Hello 6926
Hello 6927
Hello 6928
Hello 6929
Hello 6930
Hello 6931
Hello 6932
Hello 6933
Hello 6934
Hello 6935
Hello 6936
Hello 6937
Hello 6938
Hello 6939
Hello 6940
Hello 6941
Hello 6942
Hello 6943
Hello 6944
Hello 6945
Hello 6946
Hello 6947
Hello 6948
Hello 6949
Hello 6950
Hello 6951
Hello 6952
Hello 6953
Hello 6954
Hello 6955
Hello 6956
Hello 6957
Hello 6958
Hello 6959
Hello 6960
Hello 6961
Hello 6962
Hello 6963
Hello 6964
Hello 6965
Hello 6966
Hello 6967
Hello 6968
Hello 6969
Hello 6970
Hello 6971
Hello 6972
Hello 6973
Hello 6974
Hello 6975
Hello 6976
Hello 6977
Hello 6978
Hello 6979
Hello 6980
Hello 6981
Hello 6982
Hello 6983
Hello 6984
Hello 6985
Hello 6986
Hello 6987
Hello 6988
Hello 6989
Hello 6990
Hello 6991
Hello 6992

 59%|█████▊    | 7023/12000 [00:15<00:09, 503.43it/s]

Hello 6993
Hello 6994
Hello 6995
Hello 6996
Hello 6997
Hello 6998
Hello 6999
Hello 7000
Hello 7001
Hello 7002
Hello 7003
Hello 7004
Hello 7005
Hello 7006
Hello 7007
Hello 7008
Hello 7009
Hello 7010
Hello 7011
Hello 7012
Hello 7013
Hello 7014
Hello 7015
Hello 7016
Hello 7017
Hello 7018
Hello 7019
Hello 7020
Hello 7021
Hello 7022
Hello 7023
Hello 7024
Hello 7025
Hello 7026
Hello 7027
Hello 7028
Hello 7029
Hello 7030
Hello 7031
Hello 7032
Hello 7033
Hello 7034
Hello 7035
Hello 7036
Hello 7037
Hello 7038
Hello 7039
Hello 7040
Hello 7041
Hello 7042
Hello 7043
Hello 7044
Hello 7045
Hello 7046
Hello 7047
Hello 7048
Hello 7049
Hello 7050
Hello 7051
Hello 7052
Hello 7053
Hello 7054
Hello 7055
Hello 7056
Hello 7057
Hello 7058
Hello 7059
Hello 7060
Hello 7061
Hello 7062
Hello 7063
Hello 7064
Hello 7065

 59%|█████▉    | 7121/12000 [00:15<00:11, 430.14it/s]

Hello 7066
Hello 7067
Hello 7068
Hello 7069
Hello 7070
Hello 7071
Hello 7072
Hello 7073
Hello 7074
Hello 7075
Hello 7076
Hello 7077
Hello 7078
Hello 7079
Hello 7080
Hello 7081
Hello 7082
Hello 7083
Hello 7084
Hello 7085
Hello 7086
Hello 7087
Hello 7088
Hello 7089
Hello 7090
Hello 7091
Hello 7092
Hello 7093
Hello 7094
Hello 7095
Hello 7096
Hello 7097
Hello 7098
Hello 7099
Hello 7100
Hello 7101
Hello 7102
Hello 7103
Hello 7104
Hello 7105
Hello 7106
Hello 7107
Hello 7108
Hello 7109
Hello 7110
Hello 7111
Hello 7112
Hello 7113
Hello 7114
Hello 7115
Hello 7116
Hello 7117
Hello 7118
Hello 7119
Hello 7120
Hello 7121
Hello 7122
Hello 7123
Hello 7124
Hello 7125
Hello 7126
Hello 7127
Hello 7128
Hello 7129
Hello 7130
Hello 7131
Hello 7132
Hello 7133
Hello 7134
Hello 7135
Hello 7136
Hello 7137
Hello 7138
Hello 7139
Hello 7140
Hello 7141
Hello 7142
Hello 7143
Hello 7144
Hello 7145
Hello 7146
Hello 7147
Hello 7148
Hello 7149
Hello 7150
Hello 7151
Hello 7152
Hello 7153
Hello 7154
Hello 7155
Hello 7156
Hello 7157
Hello 7158
Hello 7159
Hello 7160
Hello 7161
Hello 7162
Hello 7163
Hello 7164
Hello 7165
Hello 7166
Hello 7167
Hello 7168
Hello 7169

 60%|██████    | 7232/12000 [00:16<00:11, 424.97it/s]

Hello 7170
Hello 7171
Hello 7172
Hello 7173
Hello 7174
Hello 7175
Hello 7176
Hello 7177
Hello 7178
Hello 7179
Hello 7180
Hello 7181
Hello 7182
Hello 7183
Hello 7184
Hello 7185
Hello 7186
Hello 7187
Hello 7188
Hello 7189
Hello 7190
Hello 7191
Hello 7192
Hello 7193
Hello 7194
Hello 7195
Hello 7196
Hello 7197
Hello 7198
Hello 7199
Hello 7200
Hello 7201
Hello 7202
Hello 7203
Hello 7204
Hello 7205
Hello 7206
Hello 7207
Hello 7208
Hello 7209
Hello 7210
Hello 7211
Hello 7212
Hello 7213
Hello 7214
Hello 7215
Hello 7216
Hello 7217
Hello 7218
Hello 7219
Hello 7220
Hello 7221
Hello 7222
Hello 7223
Hello 7224
Hello 7225
Hello 7226
Hello 7227
Hello 7228
Hello 7229
Hello 7230
Hello 7231
Hello 7232
Hello 7233
Hello 7234
Hello 7235
Hello 7236
Hello 7237
Hello 7238
Hello 7239
Hello 7240
Hello 7241
Hello 7242
Hello 7243

 61%|██████    | 7277/12000 [00:16<00:12, 385.66it/s]

Hello 7244
Hello 7245
Hello 7246
Hello 7247
Hello 7248
Hello 7249
Hello 7250
Hello 7251
Hello 7252
Hello 7253
Hello 7254
Hello 7255
Hello 7256
Hello 7257
Hello 7258
Hello 7259
Hello 7260
Hello 7261
Hello 7262
Hello 7263
Hello 7264
Hello 7265
Hello 7266
Hello 7267
Hello 7268
Hello 7269
Hello 7270
Hello 7271
Hello 7272
Hello 7273
Hello 7274
Hello 7275
Hello 7276
Hello 7277
Hello 7278
Hello 7279
Hello 7280
Hello 7281
Hello 7282
Hello 7283
Hello 7284
Hello 7285
Hello 7286
Hello 7287
Hello 7288
Hello 7289
Hello 7290
Hello 7291
Hello 7292
Hello 7293
Hello 7294
Hello 7295
Hello 7296
Hello 7297
Hello 7298
Hello 7299
Hello 7300
Hello 7301
Hello 7302
Hello 7303
Hello 7304
Hello 7305
Hello 7306
Hello 7307
Hello 7308
Hello 7309
Hello 7310
Hello 7311
Hello 7312
Hello 7313
Hello 7314
Hello 7315
Hello 7316
Hello 7317

 61%|██████▏   | 7371/12000 [00:16<00:11, 416.14it/s]

Hello 7318
Hello 7319
Hello 7320
Hello 7321
Hello 7322
Hello 7323
Hello 7324
Hello 7325
Hello 7326
Hello 7327
Hello 7328
Hello 7329
Hello 7330
Hello 7331
Hello 7332
Hello 7333
Hello 7334
Hello 7335
Hello 7336
Hello 7337
Hello 7338
Hello 7339
Hello 7340
Hello 7341
Hello 7342
Hello 7343
Hello 7344
Hello 7345
Hello 7346
Hello 7347
Hello 7348
Hello 7349
Hello 7350
Hello 7351
Hello 7352
Hello 7353
Hello 7354
Hello 7355
Hello 7356
Hello 7357
Hello 7358
Hello 7359
Hello 7360
Hello 7361
Hello 7362
Hello 7363
Hello 7364
Hello 7365
Hello 7366
Hello 7367
Hello 7368
Hello 7369
Hello 7370
Hello 7371
Hello 7372
Hello 7373
Hello 7374
Hello 7375
Hello 7376
Hello 7377
Hello 7378
Hello 7379
Hello 7380
Hello 7381
Hello 7382
Hello 7383
Hello 7384
Hello 7385
Hello 7386
Hello 7387
Hello 7388
Hello 7389
Hello 7390
Hello 7391
Hello 7392
Hello 7393
Hello 7394
Hello 7395
Hello 7396
Hello 7397
Hello 7398
Hello 7399
Hello 7400
Hello 7401
Hello 7402
Hello 7403
Hello 7404
Hello 7405
Hello 7406

 62%|██████▏   | 7457/12000 [00:16<00:12, 355.62it/s]

Hello 7407
Hello 7408
Hello 7409
Hello 7410
Hello 7411
Hello 7412
Hello 7413
Hello 7414
Hello 7415
Hello 7416
Hello 7417
Hello 7418
Hello 7419
Hello 7420
Hello 7421
Hello 7422
Hello 7423
Hello 7424
Hello 7425
Hello 7426
Hello 7427
Hello 7428
Hello 7429
Hello 7430
Hello 7431
Hello 7432
Hello 7433
Hello 7434
Hello 7435
Hello 7436
Hello 7437
Hello 7438
Hello 7439
Hello 7440
Hello 7441
Hello 7442
Hello 7443
Hello 7444
Hello 7445
Hello 7446
Hello 7447
Hello 7448
Hello 7449
Hello 7450
Hello 7451
Hello 7452
Hello 7453
Hello 7454
Hello 7455
Hello 7456
Hello 7457
Hello 7458
Hello 7459
Hello 7460
Hello 7461
Hello 7462
Hello 7463
Hello 7464
Hello 7465
Hello 7466
Hello 7467
Hello 7468
Hello 7469
Hello 7470
Hello 7471
Hello 7472
Hello 7473
Hello 7474
Hello 7475
Hello 7476
Hello 7477
Hello 7478
Hello 7479
Hello 7480
Hello 7481
Hello 7482
Hello 7483

 63%|██████▎   | 7585/12000 [00:16<00:09, 464.25it/s]

Hello 7484
Hello 7485
Hello 7486
Hello 7487
Hello 7488
Hello 7489
Hello 7490
Hello 7491
Hello 7492
Hello 7493
Hello 7494
Hello 7495
Hello 7496
Hello 7497
Hello 7498
Hello 7499
Hello 7500
Hello 7501
Hello 7502
Hello 7503
Hello 7504
Hello 7505
Hello 7506
Hello 7507
Hello 7508
Hello 7509
Hello 7510
Hello 7511
Hello 7512
Hello 7513
Hello 7514
Hello 7515
Hello 7516
Hello 7517
Hello 7518
Hello 7519
Hello 7520
Hello 7521
Hello 7522
Hello 7523
Hello 7524
Hello 7525
Hello 7526
Hello 7527
Hello 7528
Hello 7529
Hello 7530
Hello 7531
Hello 7532
Hello 7533
Hello 7534
Hello 7535
Hello 7536
Hello 7537
Hello 7538
Hello 7539
Hello 7540
Hello 7541
Hello 7542
Hello 7543
Hello 7544
Hello 7545
Hello 7546
Hello 7547
Hello 7548
Hello 7549
Hello 7550
Hello 7551
Hello 7552
Hello 7553
Hello 7554
Hello 7555
Hello 7556
Hello 7557
Hello 7558
Hello 7559
Hello 7560
Hello 7561
Hello 7562
Hello 7563
Hello 7564
Hello 7565
Hello 7566
Hello 7567
Hello 7568
Hello 7569
Hello 7570
Hello 7571
Hello 7572
Hello 7573
Hello 7574
Hello 7575
Hello 7576
Hello 7577
Hello 7578
Hello 7579
Hello 7580
Hello 7581
Hello 7582
Hello 7583
Hello 7584
Hello 7585
Hello 7586
Hello 7587
Hello 7588
Hello 7589
Hello 7590
Hello 7591
Hello 7592
Hello 7593
Hello 7594
Hello 7595
Hello 7596
Hello 7597
Hello 7598
Hello 7599
Hello 7600
Hello 7601
Hello 7602
Hello 7603
Hello 7604
Hello 7605
Hello 7606
Hello 7607
Hello 7608
Hello 7609
Hello 7610
Hello 7611
Hello 7612
Hello 7613
Hello 7614
Hello 7615

 64%|██████▍   | 7686/12000 [00:17<00:09, 471.53it/s]

Hello 7616
Hello 7617
Hello 7618
Hello 7619
Hello 7620
Hello 7621
Hello 7622
Hello 7623
Hello 7624
Hello 7625
Hello 7626
Hello 7627
Hello 7628
Hello 7629
Hello 7630
Hello 7631
Hello 7632
Hello 7633
Hello 7634
Hello 7635
Hello 7636
Hello 7637
Hello 7638
Hello 7639
Hello 7640
Hello 7641
Hello 7642
Hello 7643
Hello 7644
Hello 7645
Hello 7646
Hello 7647
Hello 7648
Hello 7649
Hello 7650
Hello 7651
Hello 7652
Hello 7653
Hello 7654
Hello 7655
Hello 7656
Hello 7657
Hello 7658
Hello 7659
Hello 7660
Hello 7661
Hello 7662
Hello 7663
Hello 7664
Hello 7665
Hello 7666
Hello 7667
Hello 7668
Hello 7669
Hello 7670
Hello 7671
Hello 7672
Hello 7673
Hello 7674
Hello 7675
Hello 7676
Hello 7677
Hello 7678
Hello 7679
Hello 7680
Hello 7681
Hello 7682
Hello 7683
Hello 7684
Hello 7685
Hello 7686
Hello 7687
Hello 7688
Hello 7689
Hello 7690
Hello 7691
Hello 7692

 65%|██████▍   | 7784/12000 [00:17<00:09, 452.14it/s]

Hello 7693
Hello 7694
Hello 7695
Hello 7696
Hello 7697
Hello 7698
Hello 7699
Hello 7700
Hello 7701
Hello 7702
Hello 7703
Hello 7704
Hello 7705
Hello 7706
Hello 7707
Hello 7708
Hello 7709
Hello 7710
Hello 7711
Hello 7712
Hello 7713
Hello 7714
Hello 7715
Hello 7716
Hello 7717
Hello 7718
Hello 7719
Hello 7720
Hello 7721
Hello 7722
Hello 7723
Hello 7724
Hello 7725
Hello 7726
Hello 7727
Hello 7728
Hello 7729
Hello 7730
Hello 7731
Hello 7732
Hello 7733
Hello 7734
Hello 7735
Hello 7736
Hello 7737
Hello 7738
Hello 7739
Hello 7740
Hello 7741
Hello 7742
Hello 7743
Hello 7744
Hello 7745
Hello 7746
Hello 7747
Hello 7748
Hello 7749
Hello 7750
Hello 7751
Hello 7752
Hello 7753
Hello 7754
Hello 7755
Hello 7756
Hello 7757
Hello 7758
Hello 7759
Hello 7760
Hello 7761
Hello 7762
Hello 7763
Hello 7764
Hello 7765
Hello 7766
Hello 7767
Hello 7768
Hello 7769
Hello 7770
Hello 7771
Hello 7772
Hello 7773
Hello 7774
Hello 7775
Hello 7776
Hello 7777
Hello 7778
Hello 7779
Hello 7780
Hello 7781
Hello 7782
Hello 7783
Hello 7784

 65%|██████▌   | 7846/12000 [00:17<00:08, 496.39it/s]

Hello 7785
Hello 7786
Hello 7787
Hello 7788
Hello 7789
Hello 7790
Hello 7791
Hello 7792
Hello 7793
Hello 7794
Hello 7795
Hello 7796
Hello 7797
Hello 7798
Hello 7799
Hello 7800
Hello 7801
Hello 7802
Hello 7803
Hello 7804
Hello 7805
Hello 7806
Hello 7807
Hello 7808
Hello 7809
Hello 7810
Hello 7811
Hello 7812
Hello 7813
Hello 7814
Hello 7815
Hello 7816
Hello 7817
Hello 7818
Hello 7819
Hello 7820
Hello 7821
Hello 7822
Hello 7823
Hello 7824
Hello 7825
Hello 7826
Hello 7827
Hello 7828
Hello 7829
Hello 7830
Hello 7831
Hello 7832
Hello 7833
Hello 7834
Hello 7835
Hello 7836
Hello 7837
Hello 7838
Hello 7839
Hello 7840
Hello 7841
Hello 7842
Hello 7843
Hello 7844
Hello 7845
Hello 7846
Hello 7847
Hello 7848
Hello 7849
Hello 7850
Hello 7851
Hello 7852
Hello 7853
Hello 7854
Hello 7855
Hello 7856
Hello 7857
Hello 7858
Hello 7859
Hello 7860
Hello 7861
Hello 7862
Hello 7863
Hello 7864
Hello 7865
Hello 7866
Hello 7867
Hello 7868
Hello 7869
Hello 7870
Hello 7871
Hello 7872
Hello 7873
Hello 7874
Hello 7875
Hello 7876
Hello 7877
Hello 7878
Hello 7879
Hello 7880
Hello 7881
Hello 7882
Hello 7883
Hello 7884
Hello 7885
Hello 7886
Hello 7887
Hello 7888
Hello 7889

 66%|██████▌   | 7947/12000 [00:17<00:08, 486.54it/s]

Hello 7890
Hello 7891
Hello 7892
Hello 7893
Hello 7894
Hello 7895
Hello 7896
Hello 7897
Hello 7898
Hello 7899
Hello 7900
Hello 7901
Hello 7902
Hello 7903
Hello 7904
Hello 7905
Hello 7906
Hello 7907
Hello 7908
Hello 7909
Hello 7910
Hello 7911
Hello 7912
Hello 7913
Hello 7914
Hello 7915
Hello 7916
Hello 7917
Hello 7918
Hello 7919
Hello 7920
Hello 7921
Hello 7922
Hello 7923
Hello 7924
Hello 7925
Hello 7926
Hello 7927
Hello 7928
Hello 7929
Hello 7930
Hello 7931
Hello 7932
Hello 7933
Hello 7934
Hello 7935
Hello 7936
Hello 7937
Hello 7938
Hello 7939
Hello 7940
Hello 7941
Hello 7942
Hello 7943
Hello 7944
Hello 7945
Hello 7946
Hello 7947
Hello 7948
Hello 7949
Hello 7950
Hello 7951
Hello 7952
Hello 7953
Hello 7954
Hello 7955
Hello 7956
Hello 7957
Hello 7958
Hello 7959
Hello 7960
Hello 7961
Hello 7962
Hello 7963
Hello 7964
Hello 7965
Hello 7966
Hello 7967
Hello 7968
Hello 7969
Hello 7970
Hello 7971
Hello 7972
Hello 7973
Hello 7974
Hello 7975
Hello 7976
Hello 7977
Hello 7978
Hello 7979
Hello 7980

 67%|██████▋   | 8051/12000 [00:17<00:09, 437.35it/s]

Hello 7981
Hello 7982
Hello 7983
Hello 7984
Hello 7985
Hello 7986
Hello 7987
Hello 7988
Hello 7989
Hello 7990
Hello 7991
Hello 7992
Hello 7993
Hello 7994
Hello 7995
Hello 7996
Hello 7997
Hello 7998
Hello 7999
Hello 8000
Hello 8001
Hello 8002
Hello 8003
Hello 8004
Hello 8005
Hello 8006
Hello 8007
Hello 8008
Hello 8009
Hello 8010
Hello 8011
Hello 8012
Hello 8013
Hello 8014
Hello 8015
Hello 8016
Hello 8017
Hello 8018
Hello 8019
Hello 8020
Hello 8021
Hello 8022
Hello 8023
Hello 8024
Hello 8025
Hello 8026
Hello 8027
Hello 8028
Hello 8029
Hello 8030
Hello 8031
Hello 8032
Hello 8033
Hello 8034
Hello 8035
Hello 8036
Hello 8037
Hello 8038
Hello 8039
Hello 8040
Hello 8041
Hello 8042
Hello 8043
Hello 8044
Hello 8045
Hello 8046
Hello 8047
Hello 8048
Hello 8049
Hello 8050
Hello 8051
Hello 8052
Hello 8053
Hello 8054
Hello 8055
Hello 8056
Hello 8057
Hello 8058
Hello 8059
Hello 8060
Hello 8061
Hello 8062
Hello 8063
Hello 8064
Hello 8065
Hello 8066
Hello 8067

 67%|██████▋   | 8097/12000 [00:18<00:09, 395.72it/s]

Hello 8068
Hello 8069
Hello 8070
Hello 8071
Hello 8072
Hello 8073
Hello 8074
Hello 8075
Hello 8076
Hello 8077
Hello 8078
Hello 8079
Hello 8080
Hello 8081
Hello 8082
Hello 8083
Hello 8084
Hello 8085
Hello 8086
Hello 8087
Hello 8088
Hello 8089
Hello 8090
Hello 8091
Hello 8092
Hello 8093
Hello 8094
Hello 8095
Hello 8096
Hello 8097
Hello 8098
Hello 8099
Hello 8100
Hello 8101
Hello 8102
Hello 8103
Hello 8104
Hello 8105
Hello 8106
Hello 8107
Hello 8108
Hello 8109
Hello 8110
Hello 8111
Hello 8112
Hello 8113
Hello 8114
Hello 8115
Hello 8116
Hello 8117
Hello 8118
Hello 8119
Hello 8120
Hello 8121
Hello 8122
Hello 8123
Hello 8124
Hello 8125
Hello 8126
Hello 8127
Hello 8128
Hello 8129
Hello 8130
Hello 8131
Hello 8132
Hello 8133
Hello 8134
Hello 8135
Hello 8136
Hello 8137
Hello 8138

 69%|██████▊   | 8246/12000 [00:18<00:08, 444.26it/s]

Hello 8139
Hello 8140
Hello 8141
Hello 8142
Hello 8143
Hello 8144
Hello 8145
Hello 8146
Hello 8147
Hello 8148
Hello 8149
Hello 8150
Hello 8151
Hello 8152
Hello 8153
Hello 8154
Hello 8155
Hello 8156
Hello 8157
Hello 8158
Hello 8159
Hello 8160
Hello 8161
Hello 8162
Hello 8163
Hello 8164
Hello 8165
Hello 8166
Hello 8167
Hello 8168
Hello 8169
Hello 8170
Hello 8171
Hello 8172
Hello 8173
Hello 8174
Hello 8175
Hello 8176
Hello 8177
Hello 8178
Hello 8179
Hello 8180
Hello 8181
Hello 8182
Hello 8183
Hello 8184
Hello 8185
Hello 8186
Hello 8187
Hello 8188
Hello 8189
Hello 8190
Hello 8191
Hello 8192
Hello 8193
Hello 8194
Hello 8195
Hello 8196
Hello 8197
Hello 8198
Hello 8199
Hello 8200
Hello 8201
Hello 8202
Hello 8203
Hello 8204
Hello 8205
Hello 8206
Hello 8207
Hello 8208
Hello 8209
Hello 8210
Hello 8211
Hello 8212
Hello 8213
Hello 8214
Hello 8215
Hello 8216
Hello 8217
Hello 8218
Hello 8219
Hello 8220
Hello 8221
Hello 8222
Hello 8223
Hello 8224
Hello 8225
Hello 8226
Hello 8227
Hello 8228
Hello 8229
Hello 8230
Hello 8231
Hello 8232
Hello 8233
Hello 8234
Hello 8235
Hello 8236
Hello 8237
Hello 8238
Hello 8239
Hello 8240
Hello 8241
Hello 8242
Hello 8243
Hello 8244
Hello 8245

 69%|██████▉   | 8293/12000 [00:18<00:08, 417.61it/s]

Hello 8246
Hello 8247
Hello 8248
Hello 8249
Hello 8250
Hello 8251
Hello 8252
Hello 8253
Hello 8254
Hello 8255
Hello 8256
Hello 8257
Hello 8258
Hello 8259
Hello 8260
Hello 8261
Hello 8262
Hello 8263
Hello 8264
Hello 8265
Hello 8266
Hello 8267
Hello 8268
Hello 8269
Hello 8270
Hello 8271
Hello 8272
Hello 8273
Hello 8274
Hello 8275
Hello 8276
Hello 8277
Hello 8278
Hello 8279
Hello 8280
Hello 8281
Hello 8282
Hello 8283
Hello 8284
Hello 8285
Hello 8286
Hello 8287
Hello 8288
Hello 8289
Hello 8290
Hello 8291
Hello 8292
Hello 8293
Hello 8294
Hello 8295
Hello 8296
Hello 8297
Hello 8298
Hello 8299
Hello 8300
Hello 8301
Hello 8302
Hello 8303
Hello 8304
Hello 8305
Hello 8306
Hello 8307
Hello 8308
Hello 8309
Hello 8310
Hello 8311
Hello 8312
Hello 8313
Hello 8314
Hello 8315
Hello 8316
Hello 8317
Hello 8318
Hello 8319
Hello 8320
Hello 8321
Hello 8322
Hello 8323
Hello 8324
Hello 8325
Hello 8326
Hello 8327
Hello 8328
Hello 8329

 70%|██████▉   | 8393/12000 [00:18<00:08, 413.67it/s]

Hello 8330
Hello 8331
Hello 8332
Hello 8333
Hello 8334
Hello 8335
Hello 8336
Hello 8337
Hello 8338
Hello 8339
Hello 8340
Hello 8341
Hello 8342
Hello 8343
Hello 8344
Hello 8345
Hello 8346
Hello 8347
Hello 8348
Hello 8349
Hello 8350
Hello 8351
Hello 8352
Hello 8353
Hello 8354
Hello 8355
Hello 8356
Hello 8357
Hello 8358
Hello 8359
Hello 8360
Hello 8361
Hello 8362
Hello 8363
Hello 8364
Hello 8365
Hello 8366
Hello 8367
Hello 8368
Hello 8369
Hello 8370
Hello 8371
Hello 8372
Hello 8373
Hello 8374
Hello 8375
Hello 8376
Hello 8377
Hello 8378
Hello 8379
Hello 8380
Hello 8381
Hello 8382
Hello 8383
Hello 8384
Hello 8385
Hello 8386
Hello 8387
Hello 8388
Hello 8389
Hello 8390
Hello 8391
Hello 8392
Hello 8393
Hello 8394
Hello 8395
Hello 8396
Hello 8397
Hello 8398
Hello 8399
Hello 8400
Hello 8401
Hello 8402
Hello 8403
Hello 8404
Hello 8405
Hello 8406
Hello 8407
Hello 8408
Hello 8409
Hello 8410
Hello 8411
Hello 8412
Hello 8413
Hello 8414
Hello 8415
Hello 8416

 71%|███████   | 8493/12000 [00:18<00:07, 452.31it/s]

Hello 8417
Hello 8418
Hello 8419
Hello 8420
Hello 8421
Hello 8422
Hello 8423
Hello 8424
Hello 8425
Hello 8426
Hello 8427
Hello 8428
Hello 8429
Hello 8430
Hello 8431
Hello 8432
Hello 8433
Hello 8434
Hello 8435
Hello 8436
Hello 8437
Hello 8438
Hello 8439
Hello 8440
Hello 8441
Hello 8442
Hello 8443
Hello 8444
Hello 8445
Hello 8446
Hello 8447
Hello 8448
Hello 8449
Hello 8450
Hello 8451
Hello 8452
Hello 8453
Hello 8454
Hello 8455
Hello 8456
Hello 8457
Hello 8458
Hello 8459
Hello 8460
Hello 8461
Hello 8462
Hello 8463
Hello 8464
Hello 8465
Hello 8466
Hello 8467
Hello 8468
Hello 8469
Hello 8470
Hello 8471
Hello 8472
Hello 8473
Hello 8474
Hello 8475
Hello 8476
Hello 8477
Hello 8478
Hello 8479
Hello 8480
Hello 8481
Hello 8482
Hello 8483
Hello 8484
Hello 8485
Hello 8486
Hello 8487
Hello 8488
Hello 8489
Hello 8490
Hello 8491
Hello 8492
Hello 8493
Hello 8494
Hello 8495
Hello 8496
Hello 8497
Hello 8498
Hello 8499
Hello 8500
Hello 8501
Hello 8502
Hello 8503
Hello 8504
Hello 8505
Hello 8506
Hello 8507
Hello 8508
Hello 8509
Hello 8510
Hello 8511
Hello 8512
Hello 8513
Hello 8514
Hello 8515
Hello 8516

 72%|███████▏  | 8587/12000 [00:19<00:08, 411.77it/s]

Hello 8517
Hello 8518
Hello 8519
Hello 8520
Hello 8521
Hello 8522
Hello 8523
Hello 8524
Hello 8525
Hello 8526
Hello 8527
Hello 8528
Hello 8529
Hello 8530
Hello 8531
Hello 8532
Hello 8533
Hello 8534
Hello 8535
Hello 8536
Hello 8537
Hello 8538
Hello 8539
Hello 8540
Hello 8541
Hello 8542
Hello 8543
Hello 8544
Hello 8545
Hello 8546
Hello 8547
Hello 8548
Hello 8549
Hello 8550
Hello 8551
Hello 8552
Hello 8553
Hello 8554
Hello 8555
Hello 8556
Hello 8557
Hello 8558
Hello 8559
Hello 8560
Hello 8561
Hello 8562
Hello 8563
Hello 8564
Hello 8565
Hello 8566
Hello 8567
Hello 8568
Hello 8569
Hello 8570
Hello 8571
Hello 8572
Hello 8573
Hello 8574
Hello 8575
Hello 8576
Hello 8577
Hello 8578
Hello 8579
Hello 8580
Hello 8581
Hello 8582
Hello 8583
Hello 8584
Hello 8585
Hello 8586
Hello 8587
Hello 8588
Hello 8589
Hello 8590
Hello 8591
Hello 8592
Hello 8593
Hello 8594
Hello 8595
Hello 8596
Hello 8597
Hello 8598
Hello 8599
Hello 8600

 72%|███████▏  | 8672/12000 [00:19<00:08, 407.29it/s]

Hello 8601
Hello 8602
Hello 8603
Hello 8604
Hello 8605
Hello 8606
Hello 8607
Hello 8608
Hello 8609
Hello 8610
Hello 8611
Hello 8612
Hello 8613
Hello 8614
Hello 8615
Hello 8616
Hello 8617
Hello 8618
Hello 8619
Hello 8620
Hello 8621
Hello 8622
Hello 8623
Hello 8624
Hello 8625
Hello 8626
Hello 8627
Hello 8628
Hello 8629
Hello 8630
Hello 8631
Hello 8632
Hello 8633
Hello 8634
Hello 8635
Hello 8636
Hello 8637
Hello 8638
Hello 8639
Hello 8640
Hello 8641
Hello 8642
Hello 8643
Hello 8644
Hello 8645
Hello 8646
Hello 8647
Hello 8648
Hello 8649
Hello 8650
Hello 8651
Hello 8652
Hello 8653
Hello 8654
Hello 8655
Hello 8656
Hello 8657
Hello 8658
Hello 8659
Hello 8660
Hello 8661
Hello 8662
Hello 8663
Hello 8664
Hello 8665
Hello 8666
Hello 8667
Hello 8668
Hello 8669
Hello 8670
Hello 8671
Hello 8672
Hello 8673
Hello 8674
Hello 8675
Hello 8676
Hello 8677
Hello 8678
Hello 8679
Hello 8680
Hello 8681
Hello 8682
Hello 8683
Hello 8684
Hello 8685
Hello 8686
Hello 8687
Hello 8688
Hello 8689
Hello 8690
Hello 8691
Hello 8692
Hello 8693
Hello 8694
Hello 8695

 73%|███████▎  | 8784/12000 [00:19<00:06, 489.35it/s]

Hello 8696
Hello 8697
Hello 8698
Hello 8699
Hello 8700
Hello 8701
Hello 8702
Hello 8703
Hello 8704
Hello 8705
Hello 8706
Hello 8707
Hello 8708
Hello 8709
Hello 8710
Hello 8711
Hello 8712
Hello 8713
Hello 8714
Hello 8715
Hello 8716
Hello 8717
Hello 8718
Hello 8719
Hello 8720
Hello 8721
Hello 8722
Hello 8723
Hello 8724
Hello 8725
Hello 8726
Hello 8727
Hello 8728
Hello 8729
Hello 8730
Hello 8731
Hello 8732
Hello 8733
Hello 8734
Hello 8735
Hello 8736
Hello 8737
Hello 8738
Hello 8739
Hello 8740
Hello 8741
Hello 8742
Hello 8743
Hello 8744
Hello 8745
Hello 8746
Hello 8747
Hello 8748
Hello 8749
Hello 8750
Hello 8751
Hello 8752
Hello 8753
Hello 8754
Hello 8755
Hello 8756
Hello 8757
Hello 8758
Hello 8759
Hello 8760
Hello 8761
Hello 8762
Hello 8763
Hello 8764
Hello 8765
Hello 8766
Hello 8767
Hello 8768
Hello 8769
Hello 8770
Hello 8771
Hello 8772
Hello 8773
Hello 8774
Hello 8775
Hello 8776
Hello 8777
Hello 8778
Hello 8779
Hello 8780
Hello 8781
Hello 8782
Hello 8783
Hello 8784
Hello 8785
Hello 8786
Hello 8787
Hello 8788
Hello 8789
Hello 8790
Hello 8791
Hello 8792
Hello 8793
Hello 8794
Hello 8795
Hello 8796
Hello 8797
Hello 8798
Hello 8799
Hello 8800
Hello 8801
Hello 8802
Hello 8803
Hello 8804
Hello 8805
Hello 8806
Hello 8807
Hello 8808
Hello 8809

 74%|███████▍  | 8883/12000 [00:19<00:06, 461.99it/s]

Hello 8810
Hello 8811
Hello 8812
Hello 8813
Hello 8814
Hello 8815
Hello 8816
Hello 8817
Hello 8818
Hello 8819
Hello 8820
Hello 8821
Hello 8822
Hello 8823
Hello 8824
Hello 8825
Hello 8826
Hello 8827
Hello 8828
Hello 8829
Hello 8830
Hello 8831
Hello 8832
Hello 8833
Hello 8834
Hello 8835
Hello 8836
Hello 8837
Hello 8838
Hello 8839
Hello 8840
Hello 8841
Hello 8842
Hello 8843
Hello 8844
Hello 8845
Hello 8846
Hello 8847
Hello 8848
Hello 8849
Hello 8850
Hello 8851
Hello 8852
Hello 8853
Hello 8854
Hello 8855
Hello 8856
Hello 8857
Hello 8858
Hello 8859
Hello 8860
Hello 8861
Hello 8862
Hello 8863
Hello 8864
Hello 8865
Hello 8866
Hello 8867
Hello 8868
Hello 8869
Hello 8870
Hello 8871
Hello 8872
Hello 8873
Hello 8874
Hello 8875
Hello 8876
Hello 8877
Hello 8878
Hello 8879
Hello 8880
Hello 8881
Hello 8882
Hello 8883
Hello 8884
Hello 8885
Hello 8886
Hello 8887
Hello 8888
Hello 8889
Hello 8890
Hello 8891
Hello 8892
Hello 8893
Hello 8894
Hello 8895
Hello 8896
Hello 8897
Hello 8898

 75%|███████▍  | 8977/12000 [00:20<00:06, 442.32it/s]

Hello 8899
Hello 8900
Hello 8901
Hello 8902
Hello 8903
Hello 8904
Hello 8905
Hello 8906
Hello 8907
Hello 8908
Hello 8909
Hello 8910
Hello 8911
Hello 8912
Hello 8913
Hello 8914
Hello 8915
Hello 8916
Hello 8917
Hello 8918
Hello 8919
Hello 8920
Hello 8921
Hello 8922
Hello 8923
Hello 8924
Hello 8925
Hello 8926
Hello 8927
Hello 8928
Hello 8929
Hello 8930
Hello 8931
Hello 8932
Hello 8933
Hello 8934
Hello 8935
Hello 8936
Hello 8937
Hello 8938
Hello 8939
Hello 8940
Hello 8941
Hello 8942
Hello 8943
Hello 8944
Hello 8945
Hello 8946
Hello 8947
Hello 8948
Hello 8949
Hello 8950
Hello 8951
Hello 8952
Hello 8953
Hello 8954
Hello 8955
Hello 8956
Hello 8957
Hello 8958
Hello 8959
Hello 8960
Hello 8961
Hello 8962
Hello 8963
Hello 8964
Hello 8965
Hello 8966
Hello 8967
Hello 8968
Hello 8969
Hello 8970
Hello 8971
Hello 8972
Hello 8973
Hello 8974
Hello 8975
Hello 8976

 75%|███████▌  | 9022/12000 [00:20<00:07, 409.60it/s]

Hello 8977
Hello 8978
Hello 8979
Hello 8980
Hello 8981
Hello 8982
Hello 8983
Hello 8984
Hello 8985
Hello 8986
Hello 8987
Hello 8988
Hello 8989
Hello 8990
Hello 8991
Hello 8992
Hello 8993
Hello 8994
Hello 8995
Hello 8996
Hello 8997
Hello 8998
Hello 8999
Hello 9000
Hello 9001
Hello 9002
Hello 9003
Hello 9004
Hello 9005
Hello 9006
Hello 9007
Hello 9008
Hello 9009
Hello 9010
Hello 9011
Hello 9012
Hello 9013
Hello 9014
Hello 9015
Hello 9016
Hello 9017
Hello 9018
Hello 9019
Hello 9020
Hello 9021
Hello 9022
Hello 9023
Hello 9024
Hello 9025
Hello 9026
Hello 9027
Hello 9028
Hello 9029
Hello 9030
Hello 9031
Hello 9032
Hello 9033
Hello 9034
Hello 9035
Hello 9036
Hello 9037
Hello 9038
Hello 9039
Hello 9040
Hello 9041
Hello 9042
Hello 9043
Hello 9044
Hello 9045
Hello 9046
Hello 9047
Hello 9048
Hello 9049
Hello 9050
Hello 9051
Hello 9052
Hello 9053
Hello 9054
Hello 9055
Hello 9056
Hello 9057
Hello 9058
Hello 9059
Hello 9060
Hello 9061
Hello 9062
Hello 9063

 76%|███████▌  | 9116/12000 [00:20<00:06, 417.77it/s]

Hello 9064
Hello 9065
Hello 9066
Hello 9067
Hello 9068
Hello 9069
Hello 9070
Hello 9071
Hello 9072
Hello 9073
Hello 9074
Hello 9075
Hello 9076
Hello 9077
Hello 9078
Hello 9079
Hello 9080
Hello 9081
Hello 9082
Hello 9083
Hello 9084
Hello 9085
Hello 9086
Hello 9087
Hello 9088
Hello 9089
Hello 9090
Hello 9091
Hello 9092
Hello 9093
Hello 9094
Hello 9095
Hello 9096
Hello 9097
Hello 9098
Hello 9099
Hello 9100
Hello 9101
Hello 9102
Hello 9103
Hello 9104
Hello 9105
Hello 9106
Hello 9107
Hello 9108
Hello 9109
Hello 9110
Hello 9111
Hello 9112
Hello 9113
Hello 9114
Hello 9115
Hello 9116
Hello 9117
Hello 9118
Hello 9119
Hello 9120
Hello 9121
Hello 9122
Hello 9123
Hello 9124
Hello 9125
Hello 9126
Hello 9127
Hello 9128
Hello 9129
Hello 9130
Hello 9131
Hello 9132
Hello 9133
Hello 9134
Hello 9135
Hello 9136
Hello 9137
Hello 9138
Hello 9139
Hello 9140
Hello 9141
Hello 9142
Hello 9143
Hello 9144
Hello 9145
Hello 9146
Hello 9147
Hello 9148
Hello 9149
Hello 9150
Hello 9151
Hello 9152
Hello 9153
Hello 9154
Hello 9155
Hello 9156
Hello 9157
Hello 9158
Hello 9159
Hello 9160
Hello 9161
Hello 9162
Hello 9163
Hello 9164
Hello 9165
Hello 9166
Hello 9167
Hello 9168
Hello 9169
Hello 9170
Hello 9171
Hello 9172
Hello 9173
Hello 9174
Hello 9175
Hello 9176
Hello 9177
Hello 9178
Hello 9179
Hello 9180
Hello 9181
Hello 9182

 77%|███████▋  | 9197/12000 [00:20<00:05, 520.67it/s]

Hello 9183
Hello 9184
Hello 9185
Hello 9186
Hello 9187
Hello 9188
Hello 9189
Hello 9190
Hello 9191
Hello 9192
Hello 9193
Hello 9194
Hello 9195
Hello 9196
Hello 9197
Hello 9198
Hello 9199
Hello 9200
Hello 9201
Hello 9202
Hello 9203
Hello 9204
Hello 9205
Hello 9206
Hello 9207
Hello 9208
Hello 9209
Hello 9210
Hello 9211
Hello 9212
Hello 9213
Hello 9214
Hello 9215
Hello 9216
Hello 9217
Hello 9218
Hello 9219
Hello 9220
Hello 9221
Hello 9222
Hello 9223
Hello 9224
Hello 9225
Hello 9226
Hello 9227
Hello 9228
Hello 9229
Hello 9230
Hello 9231
Hello 9232
Hello 9233
Hello 9234
Hello 9235
Hello 9236
Hello 9237
Hello 9238
Hello 9239
Hello 9240
Hello 9241
Hello 9242
Hello 9243
Hello 9244
Hello 9245
Hello 9246
Hello 9247

 77%|███████▋  | 9296/12000 [00:20<00:06, 402.75it/s]

Hello 9248
Hello 9249
Hello 9250
Hello 9251
Hello 9252
Hello 9253
Hello 9254
Hello 9255
Hello 9256
Hello 9257
Hello 9258
Hello 9259
Hello 9260
Hello 9261
Hello 9262
Hello 9263
Hello 9264
Hello 9265
Hello 9266
Hello 9267
Hello 9268
Hello 9269
Hello 9270
Hello 9271
Hello 9272
Hello 9273
Hello 9274
Hello 9275
Hello 9276
Hello 9277
Hello 9278
Hello 9279
Hello 9280
Hello 9281
Hello 9282
Hello 9283
Hello 9284
Hello 9285
Hello 9286
Hello 9287
Hello 9288
Hello 9289
Hello 9290
Hello 9291
Hello 9292
Hello 9293
Hello 9294
Hello 9295
Hello 9296
Hello 9297
Hello 9298
Hello 9299
Hello 9300
Hello 9301
Hello 9302
Hello 9303
Hello 9304
Hello 9305
Hello 9306
Hello 9307
Hello 9308
Hello 9309
Hello 9310
Hello 9311
Hello 9312
Hello 9313
Hello 9314
Hello 9315
Hello 9316
Hello 9317
Hello 9318
Hello 9319
Hello 9320
Hello 9321
Hello 9322
Hello 9323
Hello 9324
Hello 9325
Hello 9326
Hello 9327
Hello 9328
Hello 9329
Hello 9330
Hello 9331
Hello 9332
Hello 9333
Hello 9334
Hello 9335
Hello 9336
Hello 9337
Hello 9338
Hello 9339

 78%|███████▊  | 9418/12000 [00:21<00:05, 479.77it/s]

Hello 9340
Hello 9341
Hello 9342
Hello 9343
Hello 9344
Hello 9345
Hello 9346
Hello 9347
Hello 9348
Hello 9349
Hello 9350
Hello 9351
Hello 9352
Hello 9353
Hello 9354
Hello 9355
Hello 9356
Hello 9357
Hello 9358
Hello 9359
Hello 9360
Hello 9361
Hello 9362
Hello 9363
Hello 9364
Hello 9365
Hello 9366
Hello 9367
Hello 9368
Hello 9369
Hello 9370
Hello 9371
Hello 9372
Hello 9373
Hello 9374
Hello 9375
Hello 9376
Hello 9377
Hello 9378
Hello 9379
Hello 9380
Hello 9381
Hello 9382
Hello 9383
Hello 9384
Hello 9385
Hello 9386
Hello 9387
Hello 9388
Hello 9389
Hello 9390
Hello 9391
Hello 9392
Hello 9393
Hello 9394
Hello 9395
Hello 9396
Hello 9397
Hello 9398
Hello 9399
Hello 9400
Hello 9401
Hello 9402
Hello 9403
Hello 9404
Hello 9405
Hello 9406
Hello 9407
Hello 9408
Hello 9409
Hello 9410
Hello 9411
Hello 9412
Hello 9413
Hello 9414
Hello 9415
Hello 9416
Hello 9417
Hello 9418
Hello 9419
Hello 9420
Hello 9421
Hello 9422
Hello 9423
Hello 9424
Hello 9425
Hello 9426
Hello 9427
Hello 9428
Hello 9429
Hello 9430
Hello 9431
Hello 9432
Hello 9433
Hello 9434
Hello 9435
Hello 9436
Hello 9437
Hello 9438
Hello 9439
Hello 9440
Hello 9441
Hello 9442
Hello 9443
Hello 9444
Hello 9445
Hello 9446
Hello 9447
Hello 9448
Hello 9449
Hello 9450
Hello 9451
Hello 9452
Hello 9453
Hello 9454
Hello 9455
Hello 9456
Hello 9457
Hello 9458
Hello 9459
Hello 9460
Hello 9461
Hello 9462
Hello 9463
Hello 9464

 79%|███████▉  | 9490/12000 [00:21<00:04, 542.15it/s]

Hello 9465
Hello 9466
Hello 9467
Hello 9468
Hello 9469
Hello 9470
Hello 9471
Hello 9472
Hello 9473
Hello 9474
Hello 9475
Hello 9476
Hello 9477
Hello 9478
Hello 9479
Hello 9480
Hello 9481
Hello 9482
Hello 9483
Hello 9484
Hello 9485
Hello 9486
Hello 9487
Hello 9488
Hello 9489
Hello 9490
Hello 9491
Hello 9492
Hello 9493
Hello 9494
Hello 9495
Hello 9496
Hello 9497
Hello 9498
Hello 9499
Hello 9500
Hello 9501
Hello 9502
Hello 9503
Hello 9504
Hello 9505
Hello 9506
Hello 9507
Hello 9508
Hello 9509
Hello 9510
Hello 9511
Hello 9512
Hello 9513
Hello 9514
Hello 9515
Hello 9516
Hello 9517
Hello 9518
Hello 9519
Hello 9520
Hello 9521
Hello 9522
Hello 9523
Hello 9524
Hello 9525
Hello 9526
Hello 9527
Hello 9528
Hello 9529
Hello 9530
Hello 9531
Hello 9532
Hello 9533
Hello 9534
Hello 9535
Hello 9536
Hello 9537
Hello 9538
Hello 9539
Hello 9540
Hello 9541
Hello 9542
Hello 9543
Hello 9544
Hello 9545
Hello 9546

 80%|███████▉  | 9596/12000 [00:21<00:05, 419.95it/s]

Hello 9547
Hello 9548
Hello 9549
Hello 9550
Hello 9551
Hello 9552
Hello 9553
Hello 9554
Hello 9555
Hello 9556
Hello 9557
Hello 9558
Hello 9559
Hello 9560
Hello 9561
Hello 9562
Hello 9563
Hello 9564
Hello 9565
Hello 9566
Hello 9567
Hello 9568
Hello 9569
Hello 9570
Hello 9571
Hello 9572
Hello 9573
Hello 9574
Hello 9575
Hello 9576
Hello 9577
Hello 9578
Hello 9579
Hello 9580
Hello 9581
Hello 9582
Hello 9583
Hello 9584
Hello 9585
Hello 9586
Hello 9587
Hello 9588
Hello 9589
Hello 9590
Hello 9591
Hello 9592
Hello 9593
Hello 9594
Hello 9595
Hello 9596
Hello 9597
Hello 9598
Hello 9599
Hello 9600
Hello 9601
Hello 9602
Hello 9603
Hello 9604
Hello 9605
Hello 9606
Hello 9607
Hello 9608
Hello 9609
Hello 9610
Hello 9611
Hello 9612
Hello 9613
Hello 9614
Hello 9615
Hello 9616
Hello 9617
Hello 9618
Hello 9619
Hello 9620
Hello 9621
Hello 9622
Hello 9623
Hello 9624
Hello 9625
Hello 9626
Hello 9627
Hello 9628
Hello 9629
Hello 9630
Hello 9631
Hello 9632
Hello 9633
Hello 9634
Hello 9635
Hello 9636
Hello 9637
Hello 9638
Hello 9639
Hello 9640
Hello 9641
Hello 9642
Hello 9643
Hello 9644

 81%|████████  | 9705/12000 [00:21<00:05, 414.65it/s]

Hello 9645
Hello 9646
Hello 9647
Hello 9648
Hello 9649
Hello 9650
Hello 9651
Hello 9652
Hello 9653
Hello 9654
Hello 9655
Hello 9656
Hello 9657
Hello 9658
Hello 9659
Hello 9660
Hello 9661
Hello 9662
Hello 9663
Hello 9664
Hello 9665
Hello 9666
Hello 9667
Hello 9668
Hello 9669
Hello 9670
Hello 9671
Hello 9672
Hello 9673
Hello 9674
Hello 9675
Hello 9676
Hello 9677
Hello 9678
Hello 9679
Hello 9680
Hello 9681
Hello 9682
Hello 9683
Hello 9684
Hello 9685
Hello 9686
Hello 9687
Hello 9688
Hello 9689
Hello 9690
Hello 9691
Hello 9692
Hello 9693
Hello 9694
Hello 9695
Hello 9696
Hello 9697
Hello 9698
Hello 9699
Hello 9700
Hello 9701
Hello 9702
Hello 9703
Hello 9704
Hello 9705
Hello 9706
Hello 9707
Hello 9708
Hello 9709
Hello 9710
Hello 9711
Hello 9712
Hello 9713
Hello 9714
Hello 9715
Hello 9716
Hello 9717
Hello 9718
Hello 9719
Hello 9720
Hello 9721
Hello 9722
Hello 9723
Hello 9724
Hello 9725

 81%|████████▏ | 9750/12000 [00:21<00:05, 384.38it/s]

Hello 9726
Hello 9727
Hello 9728
Hello 9729
Hello 9730
Hello 9731
Hello 9732
Hello 9733
Hello 9734
Hello 9735
Hello 9736
Hello 9737
Hello 9738
Hello 9739
Hello 9740
Hello 9741
Hello 9742
Hello 9743
Hello 9744
Hello 9745
Hello 9746
Hello 9747
Hello 9748
Hello 9749
Hello 9750
Hello 9751
Hello 9752
Hello 9753
Hello 9754
Hello 9755
Hello 9756
Hello 9757
Hello 9758
Hello 9759
Hello 9760
Hello 9761
Hello 9762
Hello 9763
Hello 9764
Hello 9765
Hello 9766
Hello 9767
Hello 9768
Hello 9769
Hello 9770
Hello 9771
Hello 9772
Hello 9773
Hello 9774
Hello 9775
Hello 9776
Hello 9777
Hello 9778
Hello 9779
Hello 9780
Hello 9781
Hello 9782
Hello 9783
Hello 9784
Hello 9785
Hello 9786
Hello 9787
Hello 9788
Hello 9789
Hello 9790

 82%|████████▏ | 9832/12000 [00:22<00:06, 334.64it/s]

Hello 9791
Hello 9792
Hello 9793
Hello 9794
Hello 9795
Hello 9796
Hello 9797
Hello 9798
Hello 9799
Hello 9800
Hello 9801
Hello 9802
Hello 9803
Hello 9804
Hello 9805
Hello 9806
Hello 9807
Hello 9808
Hello 9809
Hello 9810
Hello 9811
Hello 9812
Hello 9813
Hello 9814
Hello 9815
Hello 9816
Hello 9817
Hello 9818
Hello 9819
Hello 9820
Hello 9821
Hello 9822
Hello 9823
Hello 9824
Hello 9825
Hello 9826
Hello 9827
Hello 9828
Hello 9829
Hello 9830
Hello 9831
Hello 9832
Hello 9833
Hello 9834
Hello 9835
Hello 9836

 82%|████████▏ | 9895/12000 [00:22<00:05, 402.84it/s]

Hello 9837
Hello 9838
Hello 9839
Hello 9840
Hello 9841
Hello 9842
Hello 9843
Hello 9844
Hello 9845
Hello 9846
Hello 9847
Hello 9848
Hello 9849
Hello 9850
Hello 9851
Hello 9852
Hello 9853
Hello 9854
Hello 9855
Hello 9856
Hello 9857
Hello 9858
Hello 9859
Hello 9860
Hello 9861
Hello 9862
Hello 9863
Hello 9864
Hello 9865
Hello 9866
Hello 9867
Hello 9868
Hello 9869
Hello 9870
Hello 9871
Hello 9872
Hello 9873
Hello 9874
Hello 9875
Hello 9876
Hello 9877
Hello 9878
Hello 9879
Hello 9880
Hello 9881
Hello 9882
Hello 9883
Hello 9884
Hello 9885
Hello 9886
Hello 9887
Hello 9888
Hello 9889
Hello 9890
Hello 9891
Hello 9892
Hello 9893
Hello 9894
Hello 9895
Hello 9896
Hello 9897
Hello 9898
Hello 9899
Hello 9900
Hello 9901
Hello 9902
Hello 9903
Hello 9904
Hello 9905
Hello 9906
Hello 9907
Hello 9908
Hello 9909
Hello 9910
Hello 9911
Hello 9912

 83%|████████▎ | 9997/12000 [00:22<00:05, 393.55it/s]

Hello 9913
Hello 9914
Hello 9915
Hello 9916
Hello 9917
Hello 9918
Hello 9919
Hello 9920
Hello 9921
Hello 9922
Hello 9923
Hello 9924
Hello 9925
Hello 9926
Hello 9927
Hello 9928
Hello 9929
Hello 9930
Hello 9931
Hello 9932
Hello 9933
Hello 9934
Hello 9935
Hello 9936
Hello 9937
Hello 9938
Hello 9939
Hello 9940
Hello 9941
Hello 9942
Hello 9943
Hello 9944
Hello 9945
Hello 9946
Hello 9947
Hello 9948
Hello 9949
Hello 9950
Hello 9951
Hello 9952
Hello 9953
Hello 9954
Hello 9955
Hello 9956
Hello 9957
Hello 9958
Hello 9959
Hello 9960
Hello 9961
Hello 9962
Hello 9963
Hello 9964
Hello 9965
Hello 9966
Hello 9967
Hello 9968
Hello 9969
Hello 9970
Hello 9971
Hello 9972
Hello 9973
Hello 9974
Hello 9975
Hello 9976
Hello 9977
Hello 9978
Hello 9979
Hello 9980
Hello 9981
Hello 9982
Hello 9983
Hello 9984
Hello 9985
Hello 9986
Hello 9987
Hello 9988
Hello 9989
Hello 9990
Hello 9991
Hello 9992
Hello 9993
Hello 9994
Hello 9995
Hello 9996

 84%|████████▎ | 10040/12000 [00:22<00:05, 383.61it/s]

Hello 9997
Hello 9998
Hello 9999
Hello 10000
Hello 10001
Hello 10002
Hello 10003
Hello 10004
Hello 10005
Hello 10006
Hello 10007
Hello 10008
Hello 10009
Hello 10010
Hello 10011
Hello 10012
Hello 10013
Hello 10014
Hello 10015
Hello 10016
Hello 10017
Hello 10018
Hello 10019
Hello 10020
Hello 10021
Hello 10022
Hello 10023
Hello 10024
Hello 10025
Hello 10026
Hello 10027
Hello 10028
Hello 10029
Hello 10030
Hello 10031
Hello 10032
Hello 10033
Hello 10034
Hello 10035
Hello 10036
Hello 10037
Hello 10038
Hello 10039
Hello 10040
Hello 10041
Hello 10042
Hello 10043
Hello 10044
Hello 10045
Hello 10046
Hello 10047
Hello 10048
Hello 10049
Hello 10050
Hello 10051
Hello 10052
Hello 10053
Hello 10054
Hello 10055
Hello 10056
Hello 10057
Hello 10058
Hello 10059
Hello 10060
Hello 10061
Hello 10062
Hello 10063
Hello 10064
Hello 10065

 84%|████████▍ | 10121/12000 [00:22<00:05, 350.21it/s]

Hello 10066
Hello 10067
Hello 10068
Hello 10069
Hello 10070
Hello 10071
Hello 10072
Hello 10073
Hello 10074
Hello 10075
Hello 10076
Hello 10077
Hello 10078
Hello 10079
Hello 10080
Hello 10081
Hello 10082
Hello 10083
Hello 10084
Hello 10085
Hello 10086
Hello 10087
Hello 10088
Hello 10089
Hello 10090
Hello 10091
Hello 10092
Hello 10093
Hello 10094
Hello 10095
Hello 10096
Hello 10097
Hello 10098
Hello 10099
Hello 10100
Hello 10101
Hello 10102
Hello 10103
Hello 10104
Hello 10105
Hello 10106
Hello 10107
Hello 10108
Hello 10109
Hello 10110
Hello 10111
Hello 10112
Hello 10113
Hello 10114
Hello 10115
Hello 10116
Hello 10117
Hello 10118
Hello 10119
Hello 10120
Hello 10121
Hello 10122
Hello 10123
Hello 10124
Hello 10125
Hello 10126
Hello 10127
Hello 10128
Hello 10129
Hello 10130
Hello 10131
Hello 10132
Hello 10133
Hello 10134
Hello 10135
Hello 10136
Hello 10137
Hello 10138
Hello 10139
Hello 10140
Hello 10141
Hello 10142

 85%|████████▍ | 10197/12000 [00:23<00:05, 332.92it/s]

Hello 10143
Hello 10144
Hello 10145
Hello 10146
Hello 10147
Hello 10148
Hello 10149
Hello 10150
Hello 10151
Hello 10152
Hello 10153
Hello 10154
Hello 10155
Hello 10156
Hello 10157
Hello 10158
Hello 10159
Hello 10160
Hello 10161
Hello 10162
Hello 10163
Hello 10164
Hello 10165
Hello 10166
Hello 10167
Hello 10168
Hello 10169
Hello 10170
Hello 10171
Hello 10172
Hello 10173
Hello 10174
Hello 10175
Hello 10176
Hello 10177
Hello 10178
Hello 10179
Hello 10180
Hello 10181
Hello 10182
Hello 10183
Hello 10184
Hello 10185
Hello 10186
Hello 10187
Hello 10188
Hello 10189
Hello 10190
Hello 10191
Hello 10192
Hello 10193
Hello 10194
Hello 10195
Hello 10196
Hello 10197
Hello 10198
Hello 10199
Hello 10200
Hello 10201
Hello 10202
Hello 10203
Hello 10204
Hello 10205
Hello 10206
Hello 10207
Hello 10208
Hello 10209

 86%|████████▌ | 10265/12000 [00:23<00:05, 299.41it/s]

Hello 10210
Hello 10211
Hello 10212
Hello 10213
Hello 10214
Hello 10215
Hello 10216
Hello 10217
Hello 10218
Hello 10219
Hello 10220
Hello 10221
Hello 10222
Hello 10223
Hello 10224
Hello 10225
Hello 10226
Hello 10227
Hello 10228
Hello 10229
Hello 10230
Hello 10231
Hello 10232
Hello 10233
Hello 10234
Hello 10235
Hello 10236
Hello 10237
Hello 10238
Hello 10239
Hello 10240
Hello 10241
Hello 10242
Hello 10243
Hello 10244
Hello 10245
Hello 10246
Hello 10247
Hello 10248
Hello 10249
Hello 10250
Hello 10251
Hello 10252
Hello 10253
Hello 10254
Hello 10255
Hello 10256
Hello 10257
Hello 10258
Hello 10259
Hello 10260
Hello 10261
Hello 10262
Hello 10263
Hello 10264
Hello 10265
Hello 10266

 86%|████████▌ | 10310/12000 [00:23<00:05, 337.25it/s]

Hello 10267
Hello 10268
Hello 10269
Hello 10270
Hello 10271
Hello 10272
Hello 10273
Hello 10274
Hello 10275
Hello 10276
Hello 10277
Hello 10278
Hello 10279
Hello 10280
Hello 10281
Hello 10282
Hello 10283
Hello 10284
Hello 10285
Hello 10286
Hello 10287
Hello 10288
Hello 10289
Hello 10290
Hello 10291
Hello 10292
Hello 10293
Hello 10294
Hello 10295
Hello 10296
Hello 10297
Hello 10298
Hello 10299
Hello 10300
Hello 10301
Hello 10302
Hello 10303
Hello 10304
Hello 10305
Hello 10306
Hello 10307
Hello 10308
Hello 10309
Hello 10310
Hello 10311
Hello 10312
Hello 10313
Hello 10314
Hello 10315
Hello 10316
Hello 10317
Hello 10318
Hello 10319
Hello 10320
Hello 10321
Hello 10322
Hello 10323
Hello 10324
Hello 10325
Hello 10326
Hello 10327
Hello 10328
Hello 10329
Hello 10330
Hello 10331
Hello 10332
Hello 10333
Hello 10334
Hello 10335
Hello 10336
Hello 10337
Hello 10338
Hello 10339
Hello 10340

 87%|████████▋ | 10389/12000 [00:23<00:04, 358.29it/s]

Hello 10341
Hello 10342
Hello 10343
Hello 10344
Hello 10345
Hello 10346
Hello 10347
Hello 10348
Hello 10349
Hello 10350
Hello 10351
Hello 10352
Hello 10353
Hello 10354
Hello 10355
Hello 10356
Hello 10357
Hello 10358
Hello 10359
Hello 10360
Hello 10361
Hello 10362
Hello 10363
Hello 10364
Hello 10365
Hello 10366
Hello 10367
Hello 10368
Hello 10369
Hello 10370
Hello 10371
Hello 10372
Hello 10373
Hello 10374
Hello 10375
Hello 10376
Hello 10377
Hello 10378
Hello 10379
Hello 10380
Hello 10381
Hello 10382
Hello 10383
Hello 10384
Hello 10385
Hello 10386
Hello 10387
Hello 10388
Hello 10389
Hello 10390
Hello 10391
Hello 10392
Hello 10393
Hello 10394
Hello 10395
Hello 10396
Hello 10397
Hello 10398
Hello 10399
Hello 10400
Hello 10401
Hello 10402
Hello 10403
Hello 10404
Hello 10405
Hello 10406
Hello 10407
Hello 10408
Hello 10409
Hello 10410
Hello 10411
Hello 10412
Hello 10413
Hello 10414
Hello 10415
Hello 10416
Hello 10417
Hello 10418
Hello 10419
Hello 10420
Hello 10421
Hello 10422
Hello 10423
Hello 10424
Hello 10425
Hello 10426
Hello 10427
Hello 10428
Hello 10429
Hello 10430
Hello 10431
Hello 10432
Hello 10433
Hello 10434
Hello 10435
Hello 10436
Hello 10437
Hello 10438
Hello 10439
Hello 10440
Hello 10441

 88%|████████▊ | 10528/12000 [00:23<00:03, 407.39it/s]

Hello 10442
Hello 10443
Hello 10444
Hello 10445
Hello 10446
Hello 10447
Hello 10448
Hello 10449
Hello 10450
Hello 10451
Hello 10452
Hello 10453
Hello 10454
Hello 10455
Hello 10456
Hello 10457
Hello 10458
Hello 10459
Hello 10460
Hello 10461
Hello 10462
Hello 10463
Hello 10464
Hello 10465
Hello 10466
Hello 10467
Hello 10468
Hello 10469
Hello 10470
Hello 10471
Hello 10472
Hello 10473
Hello 10474
Hello 10475
Hello 10476
Hello 10477
Hello 10478
Hello 10479
Hello 10480
Hello 10481
Hello 10482
Hello 10483
Hello 10484
Hello 10485
Hello 10486
Hello 10487
Hello 10488
Hello 10489
Hello 10490
Hello 10491
Hello 10492
Hello 10493
Hello 10494
Hello 10495
Hello 10496
Hello 10497
Hello 10498
Hello 10499
Hello 10500
Hello 10501
Hello 10502
Hello 10503
Hello 10504
Hello 10505
Hello 10506
Hello 10507
Hello 10508
Hello 10509
Hello 10510
Hello 10511
Hello 10512
Hello 10513
Hello 10514
Hello 10515
Hello 10516
Hello 10517
Hello 10518
Hello 10519
Hello 10520
Hello 10521
Hello 10522
Hello 10523
Hello 10524
Hello 10525
Hello 10526
Hello 10527

 88%|████████▊ | 10570/12000 [00:24<00:04, 351.40it/s]

Hello 10528
Hello 10529
Hello 10530
Hello 10531
Hello 10532
Hello 10533
Hello 10534
Hello 10535
Hello 10536
Hello 10537
Hello 10538
Hello 10539
Hello 10540
Hello 10541
Hello 10542
Hello 10543
Hello 10544
Hello 10545
Hello 10546
Hello 10547
Hello 10548
Hello 10549
Hello 10550
Hello 10551
Hello 10552
Hello 10553
Hello 10554
Hello 10555
Hello 10556
Hello 10557
Hello 10558
Hello 10559
Hello 10560
Hello 10561
Hello 10562
Hello 10563
Hello 10564
Hello 10565
Hello 10566
Hello 10567
Hello 10568
Hello 10569
Hello 10570
Hello 10571
Hello 10572
Hello 10573
Hello 10574
Hello 10575
Hello 10576
Hello 10577
Hello 10578
Hello 10579
Hello 10580
Hello 10581

 89%|████████▉ | 10655/12000 [00:24<00:03, 367.89it/s]

Hello 10582
Hello 10583
Hello 10584
Hello 10585
Hello 10586
Hello 10587
Hello 10588
Hello 10589
Hello 10590
Hello 10591
Hello 10592
Hello 10593
Hello 10594
Hello 10595
Hello 10596
Hello 10597
Hello 10598
Hello 10599
Hello 10600
Hello 10601
Hello 10602
Hello 10603
Hello 10604
Hello 10605
Hello 10606
Hello 10607
Hello 10608
Hello 10609
Hello 10610
Hello 10611
Hello 10612
Hello 10613
Hello 10614
Hello 10615
Hello 10616
Hello 10617
Hello 10618
Hello 10619
Hello 10620
Hello 10621
Hello 10622
Hello 10623
Hello 10624
Hello 10625
Hello 10626
Hello 10627
Hello 10628
Hello 10629
Hello 10630
Hello 10631
Hello 10632
Hello 10633
Hello 10634
Hello 10635
Hello 10636
Hello 10637
Hello 10638
Hello 10639
Hello 10640
Hello 10641
Hello 10642
Hello 10643
Hello 10644
Hello 10645
Hello 10646
Hello 10647
Hello 10648
Hello 10649
Hello 10650
Hello 10651
Hello 10652
Hello 10653
Hello 10654
Hello 10655
Hello 10656
Hello 10657
Hello 10658
Hello 10659
Hello 10660
Hello 10661
Hello 10662
Hello 10663
Hello 10664
Hello 10665
Hello 10666
Hello 10667
Hello 10668
Hello 10669
Hello 10670
Hello 10671
Hello 10672
Hello 10673
Hello 10674
Hello 10675
Hello 10676
Hello 10677
Hello 10678
Hello 10679

 89%|████████▉ | 10730/12000 [00:24<00:03, 338.76it/s]

Hello 10680
Hello 10681
Hello 10682
Hello 10683
Hello 10684
Hello 10685
Hello 10686
Hello 10687
Hello 10688
Hello 10689
Hello 10690
Hello 10691
Hello 10692
Hello 10693
Hello 10694
Hello 10695
Hello 10696
Hello 10697
Hello 10698
Hello 10699
Hello 10700
Hello 10701
Hello 10702
Hello 10703
Hello 10704
Hello 10705
Hello 10706
Hello 10707
Hello 10708
Hello 10709
Hello 10710
Hello 10711
Hello 10712
Hello 10713
Hello 10714
Hello 10715
Hello 10716
Hello 10717
Hello 10718
Hello 10719
Hello 10720
Hello 10721
Hello 10722
Hello 10723
Hello 10724
Hello 10725
Hello 10726
Hello 10727
Hello 10728
Hello 10729
Hello 10730
Hello 10731
Hello 10732
Hello 10733
Hello 10734
Hello 10735
Hello 10736
Hello 10737
Hello 10738
Hello 10739
Hello 10740
Hello 10741
Hello 10742
Hello 10743
Hello 10744
Hello 10745
Hello 10746
Hello 10747
Hello 10748
Hello 10749

 90%|█████████ | 10819/12000 [00:24<00:03, 373.98it/s]

Hello 10750
Hello 10751
Hello 10752
Hello 10753
Hello 10754
Hello 10755
Hello 10756
Hello 10757
Hello 10758
Hello 10759
Hello 10760
Hello 10761
Hello 10762
Hello 10763
Hello 10764
Hello 10765
Hello 10766
Hello 10767
Hello 10768
Hello 10769
Hello 10770
Hello 10771
Hello 10772
Hello 10773
Hello 10774
Hello 10775
Hello 10776
Hello 10777
Hello 10778
Hello 10779
Hello 10780
Hello 10781
Hello 10782
Hello 10783
Hello 10784
Hello 10785
Hello 10786
Hello 10787
Hello 10788
Hello 10789
Hello 10790
Hello 10791
Hello 10792
Hello 10793
Hello 10794
Hello 10795
Hello 10796
Hello 10797
Hello 10798
Hello 10799
Hello 10800
Hello 10801
Hello 10802
Hello 10803
Hello 10804
Hello 10805
Hello 10806
Hello 10807
Hello 10808
Hello 10809
Hello 10810
Hello 10811
Hello 10812
Hello 10813
Hello 10814
Hello 10815
Hello 10816
Hello 10817
Hello 10818
Hello 10819
Hello 10820
Hello 10821
Hello 10822
Hello 10823
Hello 10824
Hello 10825
Hello 10826

 90%|█████████ | 10858/12000 [00:24<00:03, 364.34it/s]

Hello 10827
Hello 10828
Hello 10829
Hello 10830
Hello 10831
Hello 10832
Hello 10833
Hello 10834
Hello 10835
Hello 10836
Hello 10837
Hello 10838
Hello 10839
Hello 10840
Hello 10841
Hello 10842
Hello 10843
Hello 10844
Hello 10845
Hello 10846
Hello 10847
Hello 10848
Hello 10849
Hello 10850
Hello 10851
Hello 10852
Hello 10853
Hello 10854
Hello 10855
Hello 10856
Hello 10857
Hello 10858
Hello 10859
Hello 10860
Hello 10861
Hello 10862
Hello 10863
Hello 10864
Hello 10865
Hello 10866
Hello 10867
Hello 10868
Hello 10869
Hello 10870
Hello 10871
Hello 10872
Hello 10873
Hello 10874
Hello 10875
Hello 10876
Hello 10877
Hello 10878
Hello 10879
Hello 10880
Hello 10881
Hello 10882
Hello 10883
Hello 10884
Hello 10885
Hello 10886
Hello 10887
Hello 10888
Hello 10889
Hello 10890
Hello 10891
Hello 10892
Hello 10893
Hello 10894
Hello 10895
Hello 10896
Hello 10897
Hello 10898
Hello 10899
Hello 10900
Hello 10901
Hello 10902
Hello 10903
Hello 10904
Hello 10905
Hello 10906
Hello 10907
Hello 10908
Hello 10909
Hello 10910
Hello 10911
Hello 10912
Hello 10913
Hello 10914
Hello 10915
Hello 10916
Hello 10917
Hello 10918
Hello 10919
Hello 10920
Hello 10921
Hello 10922
Hello 10923
Hello 10924

 91%|█████████▏| 10971/12000 [00:25<00:02, 357.30it/s]

Hello 10925
Hello 10926
Hello 10927
Hello 10928
Hello 10929
Hello 10930
Hello 10931
Hello 10932
Hello 10933
Hello 10934
Hello 10935
Hello 10936
Hello 10937
Hello 10938
Hello 10939
Hello 10940
Hello 10941
Hello 10942
Hello 10943
Hello 10944
Hello 10945
Hello 10946
Hello 10947
Hello 10948
Hello 10949
Hello 10950
Hello 10951
Hello 10952
Hello 10953
Hello 10954
Hello 10955
Hello 10956
Hello 10957
Hello 10958
Hello 10959
Hello 10960
Hello 10961
Hello 10962
Hello 10963
Hello 10964
Hello 10965
Hello 10966
Hello 10967
Hello 10968
Hello 10969
Hello 10970

 92%|█████████▏| 11031/12000 [00:25<00:02, 410.14it/s]

Hello 10971
Hello 10972
Hello 10973
Hello 10974
Hello 10975
Hello 10976
Hello 10977
Hello 10978
Hello 10979
Hello 10980
Hello 10981
Hello 10982
Hello 10983
Hello 10984
Hello 10985
Hello 10986
Hello 10987
Hello 10988
Hello 10989
Hello 10990
Hello 10991
Hello 10992
Hello 10993
Hello 10994
Hello 10995
Hello 10996
Hello 10997
Hello 10998
Hello 10999
Hello 11000
Hello 11001
Hello 11002
Hello 11003
Hello 11004
Hello 11005
Hello 11006
Hello 11007
Hello 11008
Hello 11009
Hello 11010
Hello 11011
Hello 11012
Hello 11013
Hello 11014
Hello 11015
Hello 11016
Hello 11017
Hello 11018
Hello 11019
Hello 11020
Hello 11021
Hello 11022
Hello 11023
Hello 11024
Hello 11025
Hello 11026
Hello 11027
Hello 11028
Hello 11029
Hello 11030
Hello 11031
Hello 11032
Hello 11033
Hello 11034
Hello 11035
Hello 11036
Hello 11037
Hello 11038
Hello 11039
Hello 11040
Hello 11041
Hello 11042
Hello 11043
Hello 11044
Hello 11045
Hello 11046
Hello 11047
Hello 11048
Hello 11049
Hello 11050
Hello 11051
Hello 11052
Hello 11053
Hello 11054
Hello 11055
Hello 11056
Hello 11057
Hello 11058
Hello 11059
Hello 11060
Hello 11061
Hello 11062
Hello 11063
Hello 11064
Hello 11065
Hello 11066
Hello 11067
Hello 11068
Hello 11069
Hello 11070
Hello 11071
Hello 11072
Hello 11073
Hello 11074
Hello 11075
Hello 11076
Hello 11077
Hello 11078
Hello 11079
Hello 11080
Hello 11081
Hello 11082
Hello 11083
Hello 11084

 93%|█████████▎| 11136/12000 [00:25<00:01, 456.88it/s]

Hello 11085
Hello 11086
Hello 11087
Hello 11088
Hello 11089
Hello 11090
Hello 11091
Hello 11092
Hello 11093
Hello 11094
Hello 11095
Hello 11096
Hello 11097
Hello 11098
Hello 11099
Hello 11100
Hello 11101
Hello 11102
Hello 11103
Hello 11104
Hello 11105
Hello 11106
Hello 11107
Hello 11108
Hello 11109
Hello 11110
Hello 11111
Hello 11112
Hello 11113
Hello 11114
Hello 11115
Hello 11116
Hello 11117
Hello 11118
Hello 11119
Hello 11120
Hello 11121
Hello 11122
Hello 11123
Hello 11124
Hello 11125
Hello 11126
Hello 11127
Hello 11128
Hello 11129
Hello 11130
Hello 11131
Hello 11132
Hello 11133
Hello 11134
Hello 11135
Hello 11136
Hello 11137
Hello 11138
Hello 11139
Hello 11140
Hello 11141
Hello 11142
Hello 11143
Hello 11144
Hello 11145
Hello 11146
Hello 11147
Hello 11148
Hello 11149
Hello 11150
Hello 11151
Hello 11152
Hello 11153
Hello 11154
Hello 11155
Hello 11156
Hello 11157
Hello 11158
Hello 11159
Hello 11160
Hello 11161
Hello 11162
Hello 11163
Hello 11164
Hello 11165
Hello 11166
Hello 11167
Hello 11168
Hello 11169
Hello 11170
Hello 11171
Hello 11172
Hello 11173
Hello 11174
Hello 11175
Hello 11176
Hello 11177
Hello 11178
Hello 11179
Hello 11180
Hello 11181
Hello 11182
Hello 11183
Hello 11184
Hello 11185
Hello 11186
Hello 11187
Hello 11188
Hello 11189
Hello 11190

 94%|█████████▍| 11325/12000 [00:25<00:01, 578.20it/s]

Hello 11191
Hello 11192
Hello 11193
Hello 11194
Hello 11195
Hello 11196
Hello 11197
Hello 11198
Hello 11199
Hello 11200
Hello 11201
Hello 11202
Hello 11203
Hello 11204
Hello 11205
Hello 11206
Hello 11207
Hello 11208
Hello 11209
Hello 11210
Hello 11211
Hello 11212
Hello 11213
Hello 11214
Hello 11215
Hello 11216
Hello 11217
Hello 11218
Hello 11219
Hello 11220
Hello 11221
Hello 11222
Hello 11223
Hello 11224
Hello 11225
Hello 11226
Hello 11227
Hello 11228
Hello 11229
Hello 11230
Hello 11231
Hello 11232
Hello 11233
Hello 11234
Hello 11235
Hello 11236
Hello 11237
Hello 11238
Hello 11239
Hello 11240
Hello 11241
Hello 11242
Hello 11243
Hello 11244
Hello 11245
Hello 11246
Hello 11247
Hello 11248
Hello 11249
Hello 11250
Hello 11251
Hello 11252
Hello 11253
Hello 11254
Hello 11255
Hello 11256
Hello 11257
Hello 11258
Hello 11259
Hello 11260
Hello 11261
Hello 11262
Hello 11263
Hello 11264
Hello 11265
Hello 11266
Hello 11267
Hello 11268
Hello 11269
Hello 11270
Hello 11271
Hello 11272
Hello 11273
Hello 11274
Hello 11275
Hello 11276
Hello 11277
Hello 11278
Hello 11279
Hello 11280
Hello 11281
Hello 11282
Hello 11283
Hello 11284
Hello 11285
Hello 11286
Hello 11287
Hello 11288
Hello 11289
Hello 11290
Hello 11291
Hello 11292
Hello 11293
Hello 11294
Hello 11295
Hello 11296
Hello 11297
Hello 11298
Hello 11299
Hello 11300
Hello 11301
Hello 11302
Hello 11303
Hello 11304
Hello 11305
Hello 11306
Hello 11307
Hello 11308
Hello 11309
Hello 11310
Hello 11311
Hello 11312
Hello 11313
Hello 11314
Hello 11315
Hello 11316
Hello 11317
Hello 11318
Hello 11319
Hello 11320
Hello 11321
Hello 11322
Hello 11323
Hello 11324

 95%|█████████▍| 11385/12000 [00:26<00:01, 463.05it/s]

Hello 11325
Hello 11326
Hello 11327
Hello 11328
Hello 11329
Hello 11330
Hello 11331
Hello 11332
Hello 11333
Hello 11334
Hello 11335
Hello 11336
Hello 11337
Hello 11338
Hello 11339
Hello 11340
Hello 11341
Hello 11342
Hello 11343
Hello 11344
Hello 11345
Hello 11346
Hello 11347
Hello 11348
Hello 11349
Hello 11350
Hello 11351
Hello 11352
Hello 11353
Hello 11354
Hello 11355
Hello 11356
Hello 11357
Hello 11358
Hello 11359
Hello 11360
Hello 11361
Hello 11362
Hello 11363
Hello 11364
Hello 11365
Hello 11366
Hello 11367
Hello 11368
Hello 11369
Hello 11370
Hello 11371
Hello 11372
Hello 11373
Hello 11374
Hello 11375
Hello 11376
Hello 11377
Hello 11378
Hello 11379
Hello 11380
Hello 11381
Hello 11382
Hello 11383
Hello 11384
Hello 11385
Hello 11386
Hello 11387
Hello 11388
Hello 11389
Hello 11390
Hello 11391
Hello 11392
Hello 11393
Hello 11394
Hello 11395
Hello 11396
Hello 11397
Hello 11398
Hello 11399
Hello 11400
Hello 11401
Hello 11402
Hello 11403
Hello 11404
Hello 11405
Hello 11406
Hello 11407
Hello 11408
Hello 11409

 96%|█████████▌| 11486/12000 [00:26<00:01, 439.83it/s]

Hello 11410
Hello 11411
Hello 11412
Hello 11413
Hello 11414
Hello 11415
Hello 11416
Hello 11417
Hello 11418
Hello 11419
Hello 11420
Hello 11421
Hello 11422
Hello 11423
Hello 11424
Hello 11425
Hello 11426
Hello 11427
Hello 11428
Hello 11429
Hello 11430
Hello 11431
Hello 11432
Hello 11433
Hello 11434
Hello 11435
Hello 11436
Hello 11437
Hello 11438
Hello 11439
Hello 11440
Hello 11441
Hello 11442
Hello 11443
Hello 11444
Hello 11445
Hello 11446
Hello 11447
Hello 11448
Hello 11449
Hello 11450
Hello 11451
Hello 11452
Hello 11453
Hello 11454
Hello 11455
Hello 11456
Hello 11457
Hello 11458
Hello 11459
Hello 11460
Hello 11461
Hello 11462
Hello 11463
Hello 11464
Hello 11465
Hello 11466
Hello 11467
Hello 11468
Hello 11469
Hello 11470
Hello 11471
Hello 11472
Hello 11473
Hello 11474
Hello 11475
Hello 11476
Hello 11477
Hello 11478
Hello 11479
Hello 11480
Hello 11481
Hello 11482
Hello 11483
Hello 11484
Hello 11485

 97%|█████████▋| 11585/12000 [00:26<00:00, 458.39it/s]

Hello 11486
Hello 11487
Hello 11488
Hello 11489
Hello 11490
Hello 11491
Hello 11492
Hello 11493
Hello 11494
Hello 11495
Hello 11496
Hello 11497
Hello 11498
Hello 11499
Hello 11500
Hello 11501
Hello 11502
Hello 11503
Hello 11504
Hello 11505
Hello 11506
Hello 11507
Hello 11508
Hello 11509
Hello 11510
Hello 11511
Hello 11512
Hello 11513
Hello 11514
Hello 11515
Hello 11516
Hello 11517
Hello 11518
Hello 11519
Hello 11520
Hello 11521
Hello 11522
Hello 11523
Hello 11524
Hello 11525
Hello 11526
Hello 11527
Hello 11528
Hello 11529
Hello 11530
Hello 11531
Hello 11532
Hello 11533
Hello 11534
Hello 11535
Hello 11536
Hello 11537
Hello 11538
Hello 11539
Hello 11540
Hello 11541
Hello 11542
Hello 11543
Hello 11544
Hello 11545
Hello 11546
Hello 11547
Hello 11548
Hello 11549
Hello 11550
Hello 11551
Hello 11552
Hello 11553
Hello 11554
Hello 11555
Hello 11556
Hello 11557
Hello 11558
Hello 11559
Hello 11560
Hello 11561
Hello 11562
Hello 11563
Hello 11564
Hello 11565
Hello 11566
Hello 11567
Hello 11568
Hello 11569
Hello 11570
Hello 11571
Hello 11572
Hello 11573
Hello 11574
Hello 11575
Hello 11576
Hello 11577
Hello 11578
Hello 11579
Hello 11580
Hello 11581
Hello 11582
Hello 11583
Hello 11584

 97%|█████████▋| 11695/12000 [00:26<00:00, 497.77it/s]

Hello 11585
Hello 11586
Hello 11587
Hello 11588
Hello 11589
Hello 11590
Hello 11591
Hello 11592
Hello 11593
Hello 11594
Hello 11595
Hello 11596
Hello 11597
Hello 11598
Hello 11599
Hello 11600
Hello 11601
Hello 11602
Hello 11603
Hello 11604
Hello 11605
Hello 11606
Hello 11607
Hello 11608
Hello 11609
Hello 11610
Hello 11611
Hello 11612
Hello 11613
Hello 11614
Hello 11615
Hello 11616
Hello 11617
Hello 11618
Hello 11619
Hello 11620
Hello 11621
Hello 11622
Hello 11623
Hello 11624
Hello 11625
Hello 11626
Hello 11627
Hello 11628
Hello 11629
Hello 11630
Hello 11631
Hello 11632
Hello 11633
Hello 11634
Hello 11635
Hello 11636
Hello 11637
Hello 11638
Hello 11639
Hello 11640
Hello 11641
Hello 11642
Hello 11643
Hello 11644
Hello 11645
Hello 11646
Hello 11647
Hello 11648
Hello 11649
Hello 11650
Hello 11651
Hello 11652
Hello 11653
Hello 11654
Hello 11655
Hello 11656
Hello 11657
Hello 11658
Hello 11659
Hello 11660
Hello 11661
Hello 11662
Hello 11663
Hello 11664
Hello 11665
Hello 11666
Hello 11667
Hello 11668
Hello 11669
Hello 11670
Hello 11671
Hello 11672
Hello 11673
Hello 11674
Hello 11675
Hello 11676
Hello 11677
Hello 11678
Hello 11679
Hello 11680
Hello 11681
Hello 11682
Hello 11683
Hello 11684
Hello 11685
Hello 11686
Hello 11687
Hello 11688
Hello 11689
Hello 11690
Hello 11691
Hello 11692
Hello 11693
Hello 11694

 98%|█████████▊| 11746/12000 [00:26<00:00, 458.45it/s]

Hello 11695
Hello 11696
Hello 11697
Hello 11698
Hello 11699
Hello 11700
Hello 11701
Hello 11702
Hello 11703
Hello 11704
Hello 11705
Hello 11706
Hello 11707
Hello 11708
Hello 11709
Hello 11710
Hello 11711
Hello 11712
Hello 11713
Hello 11714
Hello 11715
Hello 11716
Hello 11717
Hello 11718
Hello 11719
Hello 11720
Hello 11721
Hello 11722
Hello 11723
Hello 11724
Hello 11725
Hello 11726
Hello 11727
Hello 11728
Hello 11729
Hello 11730
Hello 11731
Hello 11732
Hello 11733
Hello 11734
Hello 11735
Hello 11736
Hello 11737
Hello 11738
Hello 11739
Hello 11740
Hello 11741
Hello 11742
Hello 11743
Hello 11744
Hello 11745
Hello 11746
Hello 11747
Hello 11748
Hello 11749
Hello 11750
Hello 11751
Hello 11752
Hello 11753
Hello 11754
Hello 11755
Hello 11756
Hello 11757
Hello 11758
Hello 11759
Hello 11760
Hello 11761
Hello 11762
Hello 11763
Hello 11764
Hello 11765
Hello 11766
Hello 11767
Hello 11768
Hello 11769
Hello 11770
Hello 11771
Hello 11772
Hello 11773
Hello 11774
Hello 11775
Hello 11776
Hello 11777
Hello 11778
Hello 11779
Hello 11780
Hello 11781

 98%|█████████▊| 11795/12000 [00:26<00:00, 466.34it/s]

Hello 11782
Hello 11783
Hello 11784
Hello 11785
Hello 11786
Hello 11787
Hello 11788
Hello 11789
Hello 11790
Hello 11791
Hello 11792
Hello 11793
Hello 11794
Hello 11795
Hello 11796
Hello 11797
Hello 11798
Hello 11799
Hello 11800
Hello 11801
Hello 11802
Hello 11803
Hello 11804
Hello 11805
Hello 11806
Hello 11807
Hello 11808
Hello 11809
Hello 11810
Hello 11811
Hello 11812
Hello 11813
Hello 11814
Hello 11815
Hello 11816
Hello 11817
Hello 11818
Hello 11819
Hello 11820
Hello 11821
Hello 11822
Hello 11823
Hello 11824
Hello 11825
Hello 11826
Hello 11827
Hello 11828
Hello 11829
Hello 11830
Hello 11831
Hello 11832
Hello 11833
Hello 11834
Hello 11835
Hello 11836
Hello 11837
Hello 11838
Hello 11839
Hello 11840
Hello 11841
Hello 11842

100%|█████████▉| 11946/12000 [00:27<00:00, 444.50it/s]

Hello 11843
Hello 11844
Hello 11845
Hello 11846
Hello 11847
Hello 11848
Hello 11849
Hello 11850
Hello 11851
Hello 11852
Hello 11853
Hello 11854
Hello 11855
Hello 11856
Hello 11857
Hello 11858
Hello 11859
Hello 11860
Hello 11861
Hello 11862
Hello 11863
Hello 11864
Hello 11865
Hello 11866
Hello 11867
Hello 11868
Hello 11869
Hello 11870
Hello 11871
Hello 11872
Hello 11873
Hello 11874
Hello 11875
Hello 11876
Hello 11877
Hello 11878
Hello 11879
Hello 11880
Hello 11881
Hello 11882
Hello 11883
Hello 11884
Hello 11885
Hello 11886
Hello 11887
Hello 11888
Hello 11889
Hello 11890
Hello 11891
Hello 11892
Hello 11893
Hello 11894
Hello 11895
Hello 11896
Hello 11897
Hello 11898
Hello 11899
Hello 11900
Hello 11901
Hello 11902
Hello 11903
Hello 11904
Hello 11905
Hello 11906
Hello 11907
Hello 11908
Hello 11909
Hello 11910
Hello 11911
Hello 11912
Hello 11913
Hello 11914
Hello 11915
Hello 11916
Hello 11917
Hello 11918
Hello 11919
Hello 11920
Hello 11921
Hello 11922
Hello 11923
Hello 11924
Hello 11925
Hello 11926
Hello 11927
Hello 11928
Hello 11929
Hello 11930
Hello 11931
Hello 11932
Hello 11933
Hello 11934
Hello 11935
Hello 11936
Hello 11937
Hello 11938
Hello 11939
Hello 11940
Hello 11941
Hello 11942
Hello 11943
Hello 11944
Hello 11945

100%|██████████| 12000/12000 [00:27<00:00, 437.21it/s]

Hello 11946
Hello 11947
Hello 11948
Hello 11949
Hello 11950
Hello 11951
Hello 11952
Hello 11953
Hello 11954
Hello 11955
Hello 11956
Hello 11957
Hello 11958
Hello 11959
Hello 11960
Hello 11961
Hello 11962
Hello 11963
Hello 11964
Hello 11965
Hello 11966
Hello 11967
Hello 11968
Hello 11969
Hello 11970
Hello 11971
Hello 11972
Hello 11973
Hello 11974
Hello 11975
Hello 11976
Hello 11977
Hello 11978
Hello 11979
Hello 11980
Hello 11981
Hello 11982
Hello 11983
Hello 11984
Hello 11985
Hello 11986
Hello 11987
Hello 11988
Hello 11989
Hello 11990
Hello 11991
Hello 11992
Hello 11993
Hello 11994
Hello 11995
Hello 11996
Hello 11997
Hello 11998
Hello 11999

In [103]:
X

[array([-8.98565203e-02,  3.87762785e-01,  2.05360174e-01,  1.50030404e-01,
         6.38756901e-02, -3.05261046e-01,  6.76080510e-02,  5.57710648e-01,
        -1.47208616e-01, -2.35968530e-01, -1.09447107e-01, -3.56476605e-01,
        -6.74124458e-04,  2.45878845e-02,  2.21960247e-01, -2.59236395e-01,
         1.22386113e-01, -4.55549479e-01,  1.13357320e-01, -4.74740028e-01,
         1.07560176e-02, -3.37780565e-02,  1.13953739e-01, -2.02800229e-01,
         1.25958353e-01,  2.75423340e-02, -4.46792126e-01, -1.72838226e-01,
        -2.16379613e-01,  3.85077000e-02,  3.72475654e-01, -1.03327915e-01,
         1.17802694e-01, -1.90871432e-01, -8.73666795e-05,  3.17168921e-01,
         4.30279896e-02, -2.03564703e-01, -1.04588397e-01, -6.05051935e-01,
        -2.16424450e-01, -1.55330271e-01, -1.12652436e-01,  7.72234201e-02,
         1.44078448e-01, -1.56761959e-01, -2.56482750e-01,  1.72060486e-02,
         1.73376650e-01,  3.56437147e-01,  1.32949084e-01, -2.41995707e-01,
        -1.08442299e-01,  1.13072596e-01, -4.35221434e-01,  2.48176903e-01,
         1.71418741e-01, -1.12090316e-02, -4.29876894e-01,  1.68863133e-01,
        -5.31228520e-02,  1.58250064e-01, -2.12222397e-01,  1.19151995e-02,
        -2.40203187e-01,  2.54862756e-01,  9.51913092e-03,  2.38334641e-01,
        -4.07331347e-01,  3.53971958e-01, -1.31454363e-01,  4.62326169e-01,
         3.81581903e-01, -1.61847010e-01,  2.90032625e-01,  7.36619085e-02,
        -6.89191595e-02,  1.92289352e-01, -2.59026498e-01, -5.20918518e-03,
        -2.26052001e-01, -2.29874323e-03, -2.58772194e-01,  5.17115057e-01,
        -1.98363438e-01,  6.44628555e-02, -9.99881979e-03,  3.03569943e-01,
         4.42375004e-01,  7.21868202e-02,  4.19569045e-01,  1.84962362e-01,
        -2.24462584e-01,  7.94297457e-02,  5.30012012e-01,  1.54455170e-01,
        -2.13434352e-04, -3.81335616e-01,  2.93653924e-02, -4.42467742e-02],
       dtype=float32),
 array([-2.70865351e-01,  2.93324739e-01,  1.80738300e-01,  1.96180627e-01,
         2.75928020e-01, -2.89328963e-01,  4.26689804e-01,  7.24418879e-01,
        -5.69799006e-01, -3.58217746e-01, -1.45489601e-02, -2.36873835e-01,
         8.90244357e-03,  3.74116838e-01,  2.52861679e-01, -2.37213239e-01,
         4.03168768e-01, -2.20328897e-01, -2.58399963e-01, -1.04349840e+00,
        -1.89002290e-01,  1.83477715e-01,  2.18684867e-01, -3.50862443e-01,
         6.44266699e-03, -1.32048413e-01, -5.49148381e-01, -4.43879291e-02,
        -4.55455512e-01,  9.23711881e-02,  2.62284547e-01, -1.44247010e-01,
         5.19908130e-01, -4.45677012e-01, -3.63648117e-01,  5.38184941e-01,
        -1.88469701e-02, -1.92200705e-01, -5.70239052e-02, -4.64233041e-01,
        -1.53034767e-02, -3.34653437e-01, -3.49464208e-01,  1.20461285e-01,
         4.30618554e-01, -1.01421736e-01, -1.68435380e-01, -3.21656406e-01,
         4.05946255e-01,  4.07969266e-01,  3.78867358e-01, -1.97920337e-01,
        -2.28789151e-01,  3.45758855e-01, -3.66795242e-01,  4.00240719e-01,
         2.60813951e-01, -8.24375916e-03, -6.72340989e-01,  3.17310810e-01,
         1.06647260e-01, -8.34205449e-02,  1.91114709e-01, -9.13634747e-02,
        -3.25947255e-01,  6.08738959e-01,  1.86780497e-01,  2.77655244e-01,
        -5.82337260e-01,  5.41140556e-01,  2.60598697e-02,  3.11316401e-01,
         6.68533146e-01,  3.06363046e-01,  4.26741779e-01, -1.80409595e-01,
         2.17693642e-01,  3.22339922e-01, -3.36125076e-01, -2.10690379e-01,
        -1.67341158e-01,  2.38431618e-01, -4.80431169e-01,  5.81625164e-01,
         4.46946251e-05, -2.43315920e-02,  2.30504915e-01,  3.23659658e-01,
         6.28098071e-01,  2.35570475e-01,  7.97532856e-01,  3.17857832e-01,
        -8.37303996e-02,  2.10884660e-01,  3.71768653e-01,  2.74756223e-01,
         1.74113765e-01, -4.67070252e-01, -7.49534508e-03, -5.12968227e-02],
       dtype=float32),
 array([-0.25358468,  0.31606543,  0.25597554,  0.06025433,  0.20209984,
        -0.3631681 ,  0.40509844,  0.7461571 , -0.28350502, -0.3408106 ,
        -0.11170282, -0.3816239 , -0.16441032,  0.28677303,  0.13334925,
        -0.298713  ,  0.21315074, -0.2617013 , -0.05396507, -0.7768561 ,
         0.01022633,  0.16771106,  0.21666837, -0.20242624, -0.01617033,
         0.06085556, -0.43165627, -0.2084457 , -0.40596944, -0.00923485,
         0.22016943, -0.02968267,  0.22437212, -0.4671444 , -0.11810114,
         0.42063445, -0.01320981, -0.06641027, -0.09752508, -0.42664042,
        -0.09272718, -0.36183316, -0.19604148,  0.17868753,  0.40863237,
        -0.04039351, -0.22361448, -0.15915878,  0.4336272 ,  0.32945535,
         0.26412326, -0.18142328, -0.04883936,  0.16580424, -0.2967946 ,
         0.21153268,  0.1630706 , -0.05952286, -0.5310384 ,  0.26650783,
         0.03911658,  0.07019585,  0.03389262, -0.07130792, -0.20748293,
         0.4921394 ,  0.13152747,  0.330032  , -0.49876934,  0.4543473 ,
        -0.04663204,  0.39331153,  0.42735243,  0.06933643,  0.43053842,
         0.12210838,  0.11444022,  0.22165342, -0.24302888, -0.14422515,
        -0.22054346,  0.12721106, -0.36078575,  0.3722167 ,  0.04190961,
         0.03320622,  0.3194024 ,  0.29882145,  0.41873783,  0.22984084,
         0.62573206,  0.21756777, -0.031363  ,  0.12708676,  0.43194112,
         0.32538763,  0.13531604, -0.3586962 , -0.03827345,  0.0315081 ],
       dtype=float32),
 array([-4.3905371e-01,  2.6106170e-01,  1.7425202e-01,  5.1882006e-02,
         2.0824756e-01, -3.5703412e-01,  2.8652442e-01,  7.2932214e-01,
        -2.5291955e-01, -2.7069998e-01, -3.7767056e-01, -3.3240125e-01,
        -2.6052946e-01,  2.2228916e-01,  1.0257669e-01, -3.7043840e-01,
         6.6839218e-02,  3.1998027e-02, -6.4764321e-02, -7.6980537e-01,
        -5.7055339e-02,  1.3733000e-01,  1.8807200e-01, -1.5150197e-01,
        -7.4710339e-02,  4.9079560e-02, -4.6436450e-01, -2.4933107e-01,
        -4.5474648e-01,  9.1247030e-02,  2.3548201e-01,  9.8564468e-02,
         2.4733540e-01, -5.4454052e-01,  7.8280987e-03,  3.3648923e-01,
         4.4896513e-02,  1.5239124e-01, -2.9723070e-04, -1.0224383e-01,
         1.1557750e-01, -4.9923694e-01, -3.6475202e-01,  2.1126768e-01,
         3.2082066e-01, -1.7386606e-01,  7.4278447e-03, -1.6083394e-01,
         4.9419302e-01,  3.7732995e-01,  2.9016423e-01, -2.8190947e-01,
         1.3337976e-01,  2.8692404e-02, -5.1981419e-02,  2.5440592e-01,
         1.6052790e-01, -2.0796302e-01, -3.3509332e-01,  2.2161116e-01,
        -4.9887896e-02,  1.9544585e-02,  1.8017158e-01, -2.2558111e-01,
        -2.6735073e-01,  3.5029739e-01,  2.9603168e-01,  2.5669149e-01,
        -6.3755023e-01,  4.4557449e-01,  1.7762443e-02,  3.7475452e-01,
         3.8807407e-01,  4.8697285e-02,  4.3634841e-01,  1.9725931e-01,
         8.2090631e-02,  1.1696614e-01, -1.8514617e-01, -5.8765456e-02,
        -1.5913542e-01,  1.5324630e-01, -3.6182311e-01,  2.4605730e-01,
         3.4878582e-01,  6.0897853e-02,  2.7394989e-01,  4.6999317e-01,
         4.7181988e-01,  3.2780489e-01,  3.8386497e-01, -1.4854581e-03,
         8.6324662e-02, -1.2699791e-03,  3.9431319e-01,  3.4022558e-01,
         3.3419794e-01, -2.8607801e-01, -1.0394902e-01, -2.1937406e-01],
       dtype=float32),
 array([ 0.09219649,  0.49771535, -0.09521024, -0.07814603, -0.19671145,
        -0.26820007,  0.47932276,  0.8491735 , -0.4309573 , -0.33499137,
         0.08791769, -0.7042051 , -0.2314548 ,  0.23094814,  0.18224093,
        -0.25649834,  0.51218474, -0.37049127, -0.48835886, -0.9455505 ,
        -0.0155927 ,  0.31000543,  0.36640272, -0.26662797, -0.09155866,
         0.2128932 , -0.22017477, -0.08747213, -0.32743362,  0.14130923,
         0.14118896, -0.1463725 ,  0.32508922, -0.5004958 , -0.41004753,
         0.41289616,  0.00790317, -0.21678767, -0.08286757, -0.5801486 ,
        -0.0463338 , -0.31444287,  0.00930378,  0.09037476,  0.49056235,
         0.02274681, -0.29442534, -0.00214403,  0.20212644,  0.40661725,
         0.00911964, -0.24447478, -0.18649472,  0.03197776, -0.35011232,
         0.05915215,  0.27914217,  0.08422472, -0.4393233 ,  0.28952676,
         0.27918527, -0.00262491, -0.01155359,  0.2192256 , -0.24519745,
         0.68064255,  0.15702592,  0.4817917 , -0.44088113,  0.47268894,
        -0.06225095,  0.07208725,  0.48008728,  0.04478081,  0.41531655,
         0.1964317 ,  0.10536065,  0.02238771, -0.27914792, -0.12081686,
        -0.05320565, -0.06008345, -0.31273213,  0.42299575,  0.0062267 ,
         0.03219266,  0.38987216, -0.01108534,  0.17955874,  0.04648703,
         0.60667604,  0.32058418,  0.37872094,  0.10488951,  0.40063167,
         0.21384537,  0.31787738, -0.52724606,  0.0286508 ,  0.04474027],
       dtype=float32),
 array([-0.38797563,  0.33150667,  0.14989358,  0.15403777,  0.2386305 ,
        -0.32773712,  0.14683239,  0.7071744 , -0.13979979, -0.20804906,
        -0.28157136, -0.3079922 , -0.17468266,  0.03900815,  0.17884234,
        -0.3300105 ,  0.01358592, -0.28991958,  0.14355296, -0.62126666,
         0.01201999, -0.05641166,  0.02810139, -0.17965971,  0.04495064,
        -0.13841555, -0.48643124, -0.24715015, -0.36101887,  0.03466136,
         0.3500112 ,  0.02753797,  0.14675139, -0.3146552 ,  0.01294469,
         0.30256248,  0.00870726,  0.04439434, -0.10204336, -0.30594337,
        -0.09228257, -0.30890173, -0.21700014,  0.15028441,  0.28191978,
        -0.16277507, -0.09844992,  0.05495267,  0.2799492 ,  0.4886687 ,
         0.3105429 , -0.10132941,  0.00865573,  0.05985294, -0.26204985,
         0.23193578,  0.24366659, -0.11353914, -0.3696545 ,  0.16609694,
        -0.11456118,  0.25447223, -0.07226001, -0.1581682 , -0.21520826,
         0.17495495,  0.1118532 ,  0.17481187, -0.5278139 ,  0.23747522,
         0.08895617,  0.5017979 ,  0.4032361 , -0.07310066,  0.33469808,
         0.08783131,  0.15148567,  0.18611467, -0.22447407,  0.11897937,
        -0.18814613,  0.11290748, -0.25927904,  0.37153453,  0.08178825,
         0.03468411,  0.03345825,  0.516873  ,  0.57184213,  0.16447401,
         0.36420426,  0.15674326, -0.14030524,  0.0506734 ,  0.5354281 ,
         0.21186298,  0.16623345, -0.38839683, -0.04201138, -0.12290859],
       dtype=float32),
 array([-0.2894722 ,  0.27496073,  0.32902306,  0.26135966,  0.27161637,
        -0.50029826,  0.0623897 ,  0.6385741 , -0.23262462, -0.37408358,
        -0.088832  , -0.31529772, -0.08235127,  0.18714073,  0.21091309,
        -0.2553531 ,  0.16231352, -0.3750873 ,  0.1081721 , -0.54799736,
         0.03863369, -0.11201071,  0.20806341, -0.26676372,  0.20311034,
        -0.06615675, -0.55578756, -0.01923352, -0.31820577,  0.10966282,
         0.37587366, -0.13859665,  0.27632946, -0.20629087,  0.04513871,
         0.304913  ,  0.1063748 , -0.2531865 , -0.10791371, -0.4243484 ,
        -0.2150709 , -0.31958076, -0.3461542 , -0.03832546,  0.13949545,
        -0.02521952, -0.22831973, -0.13075864,  0.22954673,  0.38300508,
         0.3629887 , -0.31812197, -0.12105292,  0.2605371 , -0.5318895 ,
         0.38552403,  0.18050165, -0.0859322 , -0.49287096,  0.2442516 ,
        -0.19541349,  0.07001628, -0.12064286, -0.17203653, -0.24788001,
         0.3655143 ,  0.129408  ,  0.18828031, -0.45512512,  0.4508604 ,
        -0.1723058 ,  0.46790063,  0.48670742,  0.00787527,  0.35634676,
        -0.08310468, -0.0304398 ,  0.3428471 , -0.2157502 , -0.09244511,
        -0.29871374,  0.11417959, -0.2496203 ,  0.46558908, -0.22150522,
         0.12819451,  0.11259338,  0.19587591,  0.6592131 ,  0.18420896,
         0.5468185 ,  0.21565104, -0.24907398,  0.09569255,  0.52440643,
         0.21677125, -0.03367516, -0.39111805, -0.13558042,  0.03349428],
       dtype=float32),
 array([-0.18603538,  0.28229463,  0.2468705 ,  0.12663181,  0.21948193,
        -0.42496887,  0.32182893,  0.68468577, -0.3325793 , -0.38151088,
        -0.10392203, -0.36980113,  0.02311678,  0.33029327,  0.16304556,
        -0.26985776,  0.24322341, -0.19538546, -0.10374767, -0.8400307 ,
        -0.12785502,  0.07358894,  0.22855805, -0.2770696 , -0.05442853,
        -0.02672162, -0.47886205, -0.06769899, -0.33855695,  0.13738239,
         0.28596443, -0.05577218,  0.31127745, -0.4149113 , -0.10266283,
         0.45139927,  0.06811777, -0.11990248,  0.00810757, -0.37995288,
         0.02343633, -0.3706352 , -0.3008376 ,  0.0469945 ,  0.25380692,
        -0.1274491 , -0.18941593, -0.262819  ,  0.33208448,  0.30952564,
         0.34449247, -0.39768878, -0.03327659,  0.2194623 , -0.28404695,
         0.43205082,  0.20981905, -0.00224865, -0.5524444 ,  0.25427595,
        -0.01672268, -0.06278727,  0.03967681, -0.13386394, -0.2445894 ,
         0.513767  ,  0.16073658,  0.22336055, -0.5015114 ,  0.43236545,
        -0.09428797,  0.26711625,  0.52896255,  0.14313464,  0.5068051 ,
         0.00873393,  0.00124472,  0.16635193, -0.19485074, -0.14256786,
        -0.23942225,  0.15559003, -0.41228637,  0.43166485,  0.00611586,
         0.16027245,  0.28776893,  0.24144317,  0.55949014,  0.2903442 ,
         0.5534095 ,  0.15922065, -0.00380517,  0.0690471 ,  0.437352  ,
         0.2803155 ,  0.14402075, -0.37808436, -0.05185863, -0.21954304],
       dtype=float32),
 array([-5.6228584e-01,  5.6664234e-01,  5.4870999e-01,  1.6489926e-01,
         2.8742963e-01, -2.3484597e-01,  4.6991980e-01,  7.8266174e-01,
        -4.1986272e-01, -5.3263384e-01,  2.7595796e-02, -1.8554831e-01,
        -3.0797589e-01,  4.9054715e-01,  2.4893166e-01, -4.5402271e-01,
         3.6529657e-01, -2.0916939e-01, -3.1653541e-01, -8.9404571e-01,
        -1.0971476e-01,  2.8676063e-01,  3.9124042e-01, -1.0904049e-01,
         9.9058755e-02,  1.9641447e-01, -4.7950512e-01, -4.2472307e-02,
        -6.4330840e-01,  8.0934890e-02,  2.0987722e-01, -3.4707648e-01,
         5.8149993e-01, -6.5355992e-01, -2.6586941e-01,  3.5300639e-01,
         4.4690073e-02, -9.4983459e-02,  4.1125458e-02, -2.6692745e-01,
        -1.9815920e-01, -5.2099586e-01, -2.7599630e-01,  2.9106858e-01,
         5.4384500e-01,  1.5053391e-02, -1.4073986e-01, -4.7272837e-01,
         6.4598370e-01,  3.5539272e-01,  2.4989016e-01, -1.6840051e-01,
        -9.3615107e-02,  2.0103011e-01, -4.3063882e-01,  1.6653551e-01,
        -2.1984268e-02, -6.2065866e-02, -6.8091339e-01,  4.0090701e-01,
         2.2352706e-01, -9.7739056e-02,  2.3014681e-01, -3.3877827e-02,
        -1.1228518e-01,  7.4326032e-01,  3.8217515e-01,  5.5133224e-01,
        -6.0937822e-01,  7.8979307e-01, -1.7332339e-01,  5.0236601e-01,
         5.3175646e-01,  3.4899360e-01,  4.0105727e-01,  8.9276955e-02,
        -1.5563873e-03,  5.7089674e-01, -1.1888198e-01, -6.1905110e-01,
        -1.9808204e-01,  4.7820382e-02, -4.7520623e-01,  3.3469254e-01,
         1.3286792e-04, -1.1160985e-01,  4.9656284e-01, -2.0755995e-02,
         4.3314329e-01,  1.8108357e-01,  8.9382499e-01,  1.9904894e-01,
        -6.1559997e-02,  1.3563943e-01,  2.4541196e-01,  3.9409688e-01,
         2.3978087e-01, -1.9931886e-01, -2.1133028e-01,  3.3253735e-01],
       dtype=float32),
 array([-0.05122916,  0.32417634,  0.01688978,  0.15219519,  0.24432486,
        -0.21205117,  0.50871444,  0.6731644 , -0.1789892 , -0.20317516,
         0.00983515, -0.29258233,  0.15625156,  0.26362357,  0.15258774,
        -0.2346796 ,  0.38054273, -0.15205409, -0.18815733, -0.94171846,
        -0.34266916,  0.0962567 ,  0.14063823, -0.32830253, -0.08620502,
        -0.19430438, -0.4550144 , -0.16875514, -0.28297684,  0.12160626,
         0.15105635, -0.1541534 ,  0.41216743, -0.335515  , -0.29905367,
         0.43382102,  0.07523085, -0.10641397,  0.12198957, -0.50867844,
        -0.01970888, -0.13972403, -0.2922201 ,  0.07844991,  0.34415582,
        -0.20794527, -0.22817859, -0.01403312,  0.28362638,  0.25724098,
         0.31819466, -0.40744722, -0.10913566,  0.31829703, -0.35088715,
         0.56972384,  0.39482626, -0.02243362, -0.5486316 ,  0.16566779,
         0.1448949 , -0.00098866,  0.08031818, -0.04794906, -0.40452793,
         0.61099994, -0.13409482,  0.20831618, -0.63467145,  0.35084537,
         0.08393703,  0.22029676,  0.65165734,  0.08052135,  0.35625786,
        -0.21532872,  0.10344675,  0.15052368, -0.5840074 , -0.11587428,
        -0.24291292,  0.21977864, -0.52377915,  0.46556827,  0.19722843,
         0.0948891 ,  0.19918697,  0.32746905,  0.56531453,  0.26258314,
         0.5506245 ,  0.16066568, -0.09462987,  0.24072944,  0.58808446,
         0.1639014 ,  0.1521399 , -0.4099359 , -0.09290667, -0.26429316],
       dtype=float32),
 array([ 0.05716854,  0.5416452 , -0.02369188,  0.08592977, -0.11714481,
        -0.22595735,  0.44716987,  0.65871066, -0.37296945, -0.29034913,
        -0.04749004, -0.63668185,  0.03583875,  0.24874844,  0.10856842,
        -0.12436533,  0.45859182, -0.2643152 , -0.3460245 , -0.9177691 ,
        -0.04953427,  0.28775877,  0.43494797, -0.30032757, -0.15788577,
         0.24112079, -0.41719025, -0.1125657 , -0.26399723,  0.10899172,
         0.2128455 , -0.08151975,  0.35573962, -0.45801723, -0.3996453 ,
         0.48326275,  0.0902839 , -0.21310933, -0.1603698 , -0.6116865 ,
        -0.09815849, -0.1275444 , -0.10087202,  0.08555482,  0.43646413,
        -0.08116698, -0.2626975 , -0.14532839,  0.2803761 ,  0.35515493,
        -0.05364169, -0.2910588 , -0.1058751 , -0.02041609, -0.3595582 ,
         0.13025229,  0.26344138,  0.09204726, -0.5065931 ,  0.3566634 ,
         0.22434326, -0.10647099, -0.03075764,  0.19415998, -0.2581869 ,
         0.49854535,  0.06653442,  0.40095016, -0.45256957,  0.5698734 ,
        -0.10215233,  0.21134686,  0.51473546,  0.0440231 ,  0.31908357,
         0.05531163,  0.0296097 , -0.02896232, -0.33826208, -0.1574532 ,
        -0.31295058, -0.07520806, -0.4727176 ,  0.52369535, -0.11882558,
        -0.09356422,  0.33543062,  0.18988934,  0.25068796,  0.06580917,
         0.5214323 ,  0.3190338 ,  0.10183726,  0.06645653,  0.4673816 ,
         0.16989435,  0.1227651 , -0.4753707 ,  0.17721428,  0.05419819],
       dtype=float32),
 array([ 0.01038859,  0.1425712 , -0.20997262,  0.27569863,  0.05960137,
        -0.1372355 ,  0.56579894,  0.88302827, -0.59502095, -0.1713783 ,
         0.06887688, -0.37709376, -0.0126647 ,  0.29754797,  0.16259305,
        -0.01492698,  0.42369518, -0.11508525, -0.5701967 , -1.2307059 ,
        -0.3544105 ,  0.31558564,  0.28638557, -0.1630026 , -0.15072522,
        -0.11074752, -0.59553087, -0.00630341, -0.24051555,  0.14281254,
         0.13333727, -0.04259633,  0.541892  , -0.49636805, -0.44426176,
         0.5918897 ,  0.13235374,  0.08098349,  0.08440319, -0.5682265 ,
         0.09024035, -0.28860545, -0.37998033,  0.30464196,  0.4095963 ,
        -0.22452271, -0.3667014 , -0.39679894,  0.6387004 ,  0.29181907,
         0.23149581, -0.2741033 , -0.2307326 ,  0.34797093,  0.04811064,
         0.5400403 ,  0.48248836,  0.01266179, -0.47400331,  0.09974828,
         0.09060734,  0.01916081,  0.17581652,  0.01577862, -0.59557265,
         0.81498355,  0.13019925,  0.44964013, -0.48696497,  0.5033806 ,
         0.04692321,  0.15923251,  0.7206936 ,  0.3132232 ,  0.58565605,
         0.08649947,  0.20259489,  0.09287951, -0.4889419 , -0.3742533 ,
        -0.1677274 ,  0.10694167, -0.42583403,  0.6116707 ,  0.14487155,
         0.09352351,  0.10692692,  0.44282243,  0.42384514,  0.4418228 ,
         0.5933814 ,  0.12207419,  0.2752359 ,  0.15830298,  0.4843668 ,
         0.39782754,  0.19230998, -0.46216485, -0.01562068, -0.37903044],
       dtype=float32),
 array([ 0.2514619 ,  0.55901843,  0.13593219, -0.1721084 ,  0.03939861,
        -0.34811166,  0.44399706,  0.79313934, -0.27808693, -0.5973827 ,
        -0.11320323, -0.78806645, -0.00336581,  0.4274168 ,  0.17196561,
        -0.04314953,  0.40831497, -0.08402666, -0.4681028 , -0.92198646,
        -0.2693029 ,  0.35417715,  0.38195392, -0.32276398, -0.31702068,
         0.43194172, -0.22619246, -0.12486132, -0.27781454,  0.2231454 ,
         0.09981008, -0.15510315,  0.13908277, -0.5811498 , -0.38671398,
         0.61420405,  0.06450879, -0.23667996, -0.01282354, -0.5955797 ,

In [139]:
len(X)

12000

In [140]:
len(X[0])

300

In [141]:
X_new = np.array(X) ## Independent features

In [142]:
X_new

array([[-0.12602839,  0.21216978,  0.05791929, ..., -0.11422826,
         0.1027656 , -0.02246523],
       [ 0.00401904,  0.29901856, -0.01577082, ..., -0.06145341,
         0.17020682, -0.45911247],
       [-0.04185131,  0.31235206,  0.03077697, ..., -0.0947139 ,
         0.12274544, -0.24670768],
       ...,
       [-0.09416368,  0.26481453,  0.10208146, ..., -0.11082809,
         0.17866176, -0.29074425],
       [-0.15823609,  0.24932368,  0.13921222, ..., -0.12642452,
         0.02706823, -0.10393531],
       [-0.04373935,  0.31934878,  0.03305769, ..., -0.08438205,
         0.17265658, -0.29857504]], dtype=float32)

In [143]:
X_new.shape

(12000, 300)

In [144]:
y.shape

(12000,)

In [145]:
X[0].reshape(1,-1).shape

(1, 300)

In [146]:
import pandas as pd
import numpy as np

# Collect all rows in a list
rows = [X[i].reshape(1, -1) for i in range(len(X))]

# Stack them into a single array
data = np.vstack(rows)

# Create the DataFrame
df = pd.DataFrame(data)

In [147]:
df

,0,1,2,3,4,5,6,7,8,9,...,290,291,292,293,294,295,296,297,298,299
0,-0.126028,0.212170,0.057919,0.044803,0.040409,-0.252738,0.187907,0.391472,0.008116,-0.108074,...,0.168263,0.281721,0.354730,-0.024799,0.213111,0.263395,0.054876,-0.114228,0.102766,-0.022465
1,0.004019,0.299019,-0.015771,-0.039356,0.175069,-0.442357,0.208580,0.519794,0.055820,-0.202520,...,0.218321,0.525841,0.290962,0.010535,0.435065,0.382836,0.030655,-0.061453,0.170207,-0.459112
2,-0.041851,0.312352,0.030777,0.035836,0.097506,-0.314744,0.134745,0.565621,0.060011,-0.151141,...,0.133859,0.411283,0.281815,0.029858,0.386333,0.391807,0.020609,-0.094714,0.122745,-0.246708
3,-0.061959,0.399133,-0.042239,0.019151,0.153162,-0.253321,0.071363,0.558269,0.171631,-0.113668,...,0.172338,0.419226,0.120395,0.081008,0.438552,0.256135,0.051594,-0.069030,0.163617,-0.264279
4,0.079922,0.297725,0.062131,0.142736,0.011197,-0.322196,0.276043,0.540084,-0.108656,-0.175119,...,0.114664,0.380119,0.291070,-0.004073,0.297604,0.408116,-0.037723,-0.055605,-0.023246,-0.364994
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,-0.049001,0.135533,-0.032620,0.137519,0.010867,-0.153407,0.311421,0.363807,0.256731,-0.110045,...,0.020640,0.294651,0.239040,-0.005813,0.151108,0.327515,0.054771,-0.167714,0.071519,0.106376
11996,0.096860,0.357477,-0.094065,0.107660,0.105343,-0.300440,0.185283,0.602243,0.162612,-0.126696,...,0.122869,0.524393,0.165412,0.036736,0.472899,0.503781,-0.020512,-0.061508,0.154319,-0.470776
11997,-0.094164,0.264815,0.102081,-0.078819,0.192008,-0.382970,0.211288,0.468754,0.053573,-0.205256,...,0.240598,0.486346,0.341956,0.058143,0.395311,0.295550,-0.048047,-0.110828,0.178662,-0.290744
11998,-0.158236,0.249324,0.139212,0.162547,-0.046729,-0.264889,0.243943,0.489469,-0.235991,-0.060993,...,0.172396,0.154232,0.458431,-0.110339,0.136807,0.291405,-0.019171,-0.126425,0.027068,-0.103935
11999,-0.043739,0.319349,0.033058,0.013104,0.165726,-0.339299,0.183728,0.510896,0.037666,-0.160365,...,0.223043,0.454801,0.234794,0.020190,0.344004,0.293465,-0.003387,-0.084382,0.172657,-0.298575

In [148]:
## Independent features
X = df
## Dependent features
y = y

In [149]:
## Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20)

In [150]:
from sklearn.naive_bayes import GaussianNB

nb_word2vec_model = GaussianNB().fit(X_train, y_train)

In [151]:
nb_word2vec_model

GaussianNB()

In [153]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
y_pred = nb_word2vec_model.predict(X_test)

print(f"Word2Vec Accuracy : {accuracy_score(y_test, y_pred)}")

Word2Vec Accuracy : 0.7233333333333334

In [ ]:
confusion_matrix(y_test, y_pred)

array([[ 575,  181],
       [ 483, 1161]], dtype=int64)