In [431]:
import pandas as pd
messages = pd.read_csv('spam.csv')

In [432]:
messages

   label                                            message
0    ham      Hey, are we still on for dinner tonight at 7?
1   spam  Congratulations! You've won a free iPhone. Cli...
2    ham    Can you send me the notes from today's meeting?
3   spam  Get rich quick! Earn $5000/week from home. Sig...
4    ham  Don't forget to bring your ID for the exam tom...
..   ...                                                ...
93  spam            You’ve won a smartwatch! Claim it here!
94   ham       Can you print the report before the meeting?
95  spam            Your mobile recharge failed. Retry now!
96   ham                     Let’s plan a movie night soon.
97  spam            Get free access to premium TV channels!

[98 rows x 2 columns]

#### Take ind. feature X = messages as above. Create embeddings using BOW.

In [433]:
import re
import nltk
nltk.download('stopwords')

from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()

corpus = []
for i in range(0, len(messages)):
  review = re.sub('[^a-zA-z]', ' ', messages['message'][i]) ## for each sentence take only alphabets
  review = review.lower()
  review = review.split() ## split all words
  
  review = [lemmatizer.lemmatize(word) for word in review if not word in stopwords.words('english')] ## remove all stopwords

  review = ' '.join(review) ## join back
  corpus.append(review)

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\ayush\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

In [434]:
corpus

['hey still dinner tonight',
 'congratulation free iphone click claim prize bit ly freephone',
 'send note today meeting',
 'get rich quick earn week home sign',
 'forget bring id exam tomorrow',
 'exclusive deal buy get free limited time offer',
 'late minute stuck traffic',
 'account suspended verify fakebank com login',
 'happy birthday hope great day',
 'selected cash reward click claim',
 'let catch weekend coffee',
 'win trip bali answer question hurry',
 'review resume send',
 'drill gift card',
 'meeting rescheduled pm please update calendar',
 'unlock full potential miracle supplement',
 'thanks help yesterday really appreciate',
 'act lowest mortgage rate history apply today',
 'lunch new place near office',
 'mobile number call',
 'email project file tonight',
 'limited offer get luxury watch',
 'watch match last night crazy ending',
 'claim free netflix subscription credit card needed',
 'let know free quick call',
 'final notice car warranty expire',
 'good luck interview tomorrow',
 'make money sleep join affiliate program',
 'pick grocery way back',
 'pre approved lakh loan apply',
 'call done meeting',
 'get free trial weight loss pill today',
 'worry everything fine',
 'computer infected download antivirus',
 'see gym later',
 'earn daily zero investment',
 'landed text reach hotel',
 'shopping voucher worth',
 'help presentation slide',
 'click claim free crypto token',
 'let plan trip next month maybe goa',
 'otp share anyone',
 'working home tomorrow',
 'get instant approval credit card',
 'thanks reminder join call',
 'download app earn reward instantly',
 'book cab tomorrow morning',
 'lucky number drawn call win',
 'bring snack movie night',
 'investment opportunity last long act',
 'send location',
 'chosen free cruise confirm',
 'minute',
 'get cashback first purchase limited time',
 'let meet caf near office',
 'kyc pending update immediately avoid suspension',
 'loved movie thanks recommending',
 'buy get electronics',
 'please bring laptop workshop',
 'loan approved click proceed',
 'forget water plant today',
 'claim free amazon voucher',
 'drop lunch',
 'free dinner two book',
 'share contact detail vendor',
 'get paid take survey join today',
 'let go hiking weekend',
 'account risk verify immediately',
 'send draft evening',
 'limited seat available register webinar',
 'thanks birthday wish',
 'sim blocked update detail',
 'help math homework',
 'get free access premium course enroll today',
 'stuck traffic late',
 'win participating lucky draw',
 'let order pizza tonight',
 'email prize click claim',
 'offline hour',
 'download get instantly',
 'check parcel arrived',
 'selected free health checkup',
 'let video call later today',
 'get dream job secret strategy',
 'bring charger tomorrow',
 'bank account need verification click',
 'send recipe',
 'earn reward inviting friend start',
 'meeting room pm',
 'subscription expiring renew',
 'let go walk dinner',
 'get gb free data activate',
 'ping done',
 'smartwatch claim',
 'print report meeting',
 'mobile recharge failed retry',
 'let plan movie night soon',
 'get free access premium tv channel']

In [435]:
y = pd.get_dummies(messages['label'])

In [436]:
y = y.astype('int')
y

    ham  spam
0     1     0
1     0     1
2     1     0
3     0     1
4     1     0
..  ...   ...
93    0     1
94    1     0
95    0     1
96    1     0
97    0     1

[98 rows x 2 columns]

In [437]:
## Take the 'ham' row only so we have all containing 0s and 1s for overall data
y = y.iloc[:, 0].values

### Take output feature y = label as above. Convert it into 0 and 1 as they are just output so we don't need to embed it.

In [438]:
## Train-Test Split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(corpus, y, test_size = 0.20)

## Create Bag Of Words for Embeddings

In [439]:
## Create BOG
from sklearn.feature_extraction.text import CountVectorizer
## for Binary BOW enable binary=True
## Here we go with non-binary that means count of words (ex. [2, 1, 0] count is considered here) will be considered
cv = CountVectorizer(
  max_features = 2500, ## this means the top 2500 words having the maximum frequency = max_features
  ngram_range = (1,2)
)

### X = independent features
### Embedded using BOW.

In [440]:
X_train = cv.fit_transform(X_train).toarray()
X_test = cv.transform(X_test).toarray() # to prevent data leakage

In [441]:
import numpy as np
np.set_printoptions(edgeitems=30, linewidth=100000,
                    formatter=dict(float=lambda x: "%.3g" % x))
X_train

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       ...,
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ..., 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [442]:
X_test.shape

(20, 483)

In [443]:
cv.vocabulary_

{'chosen': 60,
 'free': 146,
 'cruise': 84,
 'confirm': 73,
 'chosen free': 61,
 'free cruise': 149,
 'cruise confirm': 85,
 'earn': 113,
 'daily': 88,
 'zero': 481,
 'investment': 211,
 'earn daily': 114,
 'daily zero': 89,
 'zero investment': 482,
 'get': 162,
 'dream': 107,
 'job': 216,
 'secret': 385,
 'strategy': 409,
 'get dream': 163,
 'dream job': 108,
 'job secret': 217,
 'secret strategy': 386,
 'send': 392,
 'draft': 102,
 'evening': 124,
 'send draft': 393,
 'draft evening': 103,
 'location': 243,
 'send location': 394,
 'let': 231,
 'catch': 54,
 'weekend': 466,
 'coffee': 68,
 'let catch': 232,
 'catch weekend': 55,
 'weekend coffee': 467,
 'see': 387,
 'gym': 180,
 'later': 230,
 'see gym': 388,
 'gym later': 181,
 'help': 186,
 'math': 264,
 'homework': 196,
 'help math': 187,
 'math homework': 265,
 'shopping': 398,
 'voucher': 452,
 'worth': 478,
 'shopping voucher': 399,
 'voucher worth': 453,
 'selected': 389,
 'health': 184,
 'checkup': 59,
 'selected free': 391,
 'free health': 152,
 'health checkup': 185,
 'cash': 52,
 'reward': 375,
 'click': 65,
 'claim': 62,
 'selected cash': 390,
 'cash reward': 53,
 'reward click': 376,
 'click claim': 66,
 'minute': 273,
 'go': 172,
 'hiking': 189,
 'let go': 233,
 'go hiking': 173,
 'hiking weekend': 190,
 'access': 0,
 'premium': 344,
 'course': 78,
 'enroll': 122,
 'today': 427,
 'get free': 165,
 'free access': 147,
 'access premium': 1,
 'premium course': 345,
 'course enroll': 79,
 'enroll today': 123,
 'meeting': 270,
 'room': 383,
 'pm': 338,
 'meeting room': 272,
 'room pm': 384,
 'unlock': 442,
 'full': 160,
 'potential': 340,
 'miracle': 275,
 'supplement': 415,
 'unlock full': 443,
 'full potential': 161,
 'potential miracle': 341,
 'miracle supplement': 276,
 'crypto': 86,
 'token': 428,
 'claim free': 63,
 'free crypto': 150,
 'crypto token': 87,
 'download': 98,
 'app': 15,
 'instantly': 210,
 'download app': 100,
 'app earn': 16,
 'earn reward': 115,
 'reward instantly': 377,
 'netflix': 292,
 'subscription': 412,
 'credit': 82,
 'card': 50,
 'needed': 291,
 'free netflix': 155,
 'netflix subscription': 293,
 'subscription credit': 413,
 'credit card': 83,
 'card needed': 51,
 'dinner': 95,
 'two': 440,
 'book': 38,
 'free dinner': 151,
 'dinner two': 96,
 'two book': 441,
 'rescheduled': 368,
 'please': 336,
 'update': 444,
 'calendar': 45,
 'meeting rescheduled': 271,
 'rescheduled pm': 369,
 'pm please': 339,
 'please update': 337,
 'update calendar': 445,
 'order': 311,
 'pizza': 327,
 'tonight': 430,
 'let order': 235,
 'order pizza': 312,
 'pizza tonight': 328,
 'exclusive': 129,
 'deal': 91,
 'buy': 41,
 'limited': 237,
 'time': 425,
 'offer': 306,
 'exclusive deal': 130,
 'deal buy': 92,
 'buy get': 42,
 'free limited': 154,
 'limited time': 239,
 'time offer': 426,
 'check': 57,
 'parcel': 315,
 'arrived': 25,
 'check parcel': 58,
 'parcel arrived': 316,
 'download get': 101,
 'get instantly': 167,
 'win': 470,
 'participating': 317,
 'lucky': 251,
 'draw': 104,
 'win participating': 471,
 'participating lucky': 318,
 'lucky draw': 252,
 'worry': 476,
 'everything': 125,
 'fine': 142,
 'worry everything': 477,
 'everything fine': 126,
 'thanks': 421,
 'birthday': 31,
 'wish': 473,
 'thanks birthday': 422,
 'birthday wish': 33,
 'trial': 433,
 'weight': 468,
 'loss': 245,
 'pill': 323,
 'free trial': 156,
 'trial weight': 434,
 'weight loss': 469,
 'loss pill': 246,
 'pill today': 324,
 'offline': 309,
 'hour': 200,
 'offline hour': 310,
 'drill': 109,
 'gift': 170,
 'drill gift': 110,
 'gift card': 171,
 'trip': 435,
 'bali': 29,
 'answer': 11,
 'question': 354,
 'hurry': 201,
 'win trip': 472,
 'trip bali': 436,
 'bali answer': 30,
 'answer question': 12,
 'question hurry': 355,
 'plan': 331,
 'next': 296,
 'month': 282,
 'maybe': 266,
 'goa': 175,
 'let plan': 236,
 'plan trip': 333,
 'trip next': 437,
 'next month': 297,
 'month maybe': 283,
 'maybe goa': 267,
 'yesterday': 479,
 'really': 362,
 'appreciate': 19,
 'thanks help': 423,
 'help yesterday': 188,
 'yesterday really': 480,
 'really appreciate': 363,
 'amazon': 9,
 'free amazon': 148,
 'amazon voucher': 10,
 'kyc': 220,
 'pending': 319,
 'immediately': 204,
 'avoid': 26,
 'suspension': 418,
 'kyc pending': 221,
 'pending update': 320,
 'update immediately': 447,
 'immediately avoid': 205,
 'avoid suspension': 27,
 'watch': 458,
 'match': 262,
 'last': 226,
 'night': 298,
 'crazy': 80,
 'ending': 121,
 'watch match': 459,
 'match last': 263,
 'last night': 227,
 'night crazy': 299,
 'crazy ending': 81,
 'number': 303,
 'drawn': 105,
 'call': 46,
 'lucky number': 253,
 'number drawn': 305,
 'drawn call': 106,
 'call win': 47,
 'final': 140,
 'notice': 301,
 'car': 48,
 'warranty': 456,
 'expire': 131,
 'final notice': 141,
 'notice car': 302,
 'car warranty': 49,
 'warranty expire': 457,
 'walk': 454,
 'go walk': 174,
 'walk dinner': 455,
 'smartwatch': 405,
 'smartwatch claim': 406,
 'account': 2,
 'risk': 381,
 'verify': 449,
 'account risk': 3,
 'risk verify': 382,
 'verify immediately': 451,
 'forget': 143,
 'bring': 39,
 'id': 202,
 'exam': 127,
 'tomorrow': 429,
 'forget bring': 144,
 'bring id': 40,
 'id exam': 203,
 'exam tomorrow': 128,
 'working': 474,
 'home': 193,
 'working home': 475,
 'home tomorrow': 195,
 'expiring': 132,
 'renew': 367,
 'subscription expiring': 414,
 'expiring renew': 133,
 'computer': 71,
 'infected': 206,
 'antivirus': 13,
 'computer infected': 72,
 'infected download': 207,
 'download antivirus': 99,
 'late': 228,
 'stuck': 410,
 'traffic': 431,
 'late minute': 229,
 'minute stuck': 274,
 'stuck traffic': 411,
 'make': 260,
 'money': 280,
 'sleep': 403,
 'join': 218,
 'affiliate': 7,
 'program': 351,
 'make money': 261,
 'money sleep': 281,
 'sleep join': 404,
 'join affiliate': 219,
 'affiliate program': 8,
 'movie': 286,
 'soon': 407,
 'plan movie': 332,
 'movie night': 287,
 'night soon': 300,
 'meet': 268,
 'caf': 43,
 'near': 289,
 'office': 308,
 'let meet': 234,
 'meet caf': 269,
 'caf near': 44,
 'near office': 290,
 'otp': 313,
 'share': 395,
 'anyone': 14,
 'otp share': 314,
 'share anyone': 396,
 'review': 373,
 'resume': 370,
 'review resume': 374,
 'resume send': 371,
 'tv': 438,
 'channel': 56,
 'premium tv': 346,
 'tv channel': 439,
 'suspended': 416,
 'fakebank': 136,
 'com': 69,
 'login': 244,
 'account suspended': 4,
 'suspended verify': 417,
 'verify fakebank': 450,
 'fakebank com': 137,
 'com login': 70,
 'loved': 247,
 'recommending': 366,
 'loved movie': 248,
 'movie thanks': 288,
 'thanks recommending': 424,
 'contact': 76,
 'detail': 93,
 'vendor': 448,
 'share contact': 397,
 'contact detail': 77,
 'detail vendor': 94,
 'pre': 342,
 'approved': 22,
 'lakh': 222,
 'loan': 240,
 'apply': 17,
 'pre approved': 343,
 'approved lakh': 24,
 'lakh loan': 223,
 'loan apply': 241,
 'act': 5,
 'lowest': 249,
 'mortgage': 284,
 'rate': 358,
 'history': 191,
 'act lowest': 6,
 'lowest mortgage': 250,
 'mortgage rate': 285,
 'rate history': 359,
 'history apply': 192,
 'apply today': 18,
 'happy': 182,
 'hope': 197,
 'great': 176,
 'day': 90,
 'happy birthday': 183,
 'birthday hope': 32,
 'hope great': 198,
 'great day': 177,
 'electronics': 117,
 'get electronics': 164,
 'drop': 111,
 'lunch': 254,
 'drop lunch': 112,
 'ping': 325,
 'done': 97,
 'ping done': 326,
 'email': 118,
 'prize': 347,
 'email prize': 119,
 'prize click': 349,
 'rich': 379,
 'quick': 356,
 'week': 464,
 'sign': 400,
 'get rich': 169,
 'rich quick': 380,
 'quick earn': 357,
 'earn week': 116,
 'week home': 465,
 'home sign': 194,
 'project': 352,
 'file': 138,
 'email project': 120,
 'project file': 353,
 'file tonight': 139,
 'mobile': 277,
 'recharge': 364,
 'failed': 134,
 'retry': 372,
 'mobile recharge': 279,
 'recharge failed': 365,
 'failed retry': 135,
 'luxury': 256,
 'limited offer': 238,
 'offer get': 307,
 'get luxury': 168,
 'luxury watch': 257,
 'instant': 208,
 'approval': 20,
 'get instant': 166,
 'instant approval': 209,
 'approval credit': 21,
 'new': 294,
 'place': 329,
 'lunch new': 255,
 'new place': 295,
 'place near': 330,
 'water': 460,
 'plant': 334,
 'forget water': 145,
 'water plant': 461,
 'plant today': 335,
 'pick': 321,
 'grocery': 178,
 'way': 462,
 'back': 28,
 'pick grocery': 322,
 'grocery way': 179,
 'way back': 463,
 'landed': 224,
 'text': 419,
 'reach': 360,
 'hotel': 199,
 'landed text': 225,
 'text reach': 420,
 'reach hotel': 361,
 'sim': 401,
 'blocked': 36,
 'sim blocked': 402,
 'blocked update': 37,
 'update detail': 446,
 'congratulation': 74,
 'iphone': 214,
 'bit': 34,
 'ly': 258,
 'freephone': 157,
 'congratulation free': 75,
 'free iphone': 153,
 'iphone click': 215,
 'claim prize': 64,
 'prize bit': 348,
 'bit ly': 35,
 'ly freephone': 259,
 'proceed': 350,
 'loan approved': 242,
 'approved click': 23,
 'click proceed': 67,
 'inviting': 212,
 'friend': 158,
 'start': 408,
 'reward inviting': 378,
 'inviting friend': 213,
 'friend start': 159,
 'traffic late': 432,
 'mobile number': 278,
 'number call': 304}

## Model Training

In [444]:
from sklearn.naive_bayes import MultinomialNB ## Supervised ML

In [445]:
spam_detect_model = MultinomialNB().fit(X_train, y_train)

In [446]:
spam_detect_model

MultinomialNB()

In [447]:
y_pred = spam_detect_model.predict(X_test)

In [448]:
from sklearn.metrics import accuracy_score, classification_report

In [449]:
accuracy_score(y_test, y_pred)

0.9

In [450]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.75      1.00      0.86         6
           1       1.00      0.86      0.92        14

    accuracy                           0.90        20
   macro avg       0.88      0.93      0.89        20
weighted avg       0.93      0.90      0.90        20